### PR TITLE
Elysium.Theme 2.0.4

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
Elysium.Theme 2.0.4

**Details:**
Add MPL-2.0 License

**Resolution:**
License Url: 
https://github.com/elysiumcoop/elysianne/blob/master/LICENSE

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [Elysium.Theme 2.0.4](https://clearlydefined.io/definitions/nuget/nuget/-/Elysium.Theme/2.0.4)

### CODE REVIEW

**Comment by TRQ3** [comment]
https://github.com/elysiumcoop/elysianne/blob/master/LICENSE

No tagged versions. Master license confirms MPL 2.0.

**Comment by capfei** [comment]
@TRQ3 Can you point to me where on the NuGet package it lists the site they provided?

**Comment by capfei** [comment]
@ariel11 @AE49 I'm not seeing in the source or NuGet license link where it states MPL, but MIT instead. Do you agree that it should be MIT?

**Comment by ariel11** [comment]
@capfei (and @TRQ3) - I agree - the license link on the NuGet page goes to MIT and the CodePlex download for the source code says MIT.

**Review by capfei — APPROVED** [review]

**Pull request merged**
