### PR TITLE
regex 2020.7.14

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
regex 2020.7.14

**Details:**
Add Python-2.0 License

**Resolution:**
License Url: 
https://opensource.org/licenses/Python-2.0

Description:
License is listed in Pypi portal

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [regex 2020.7.14](https://clearlydefined.io/definitions/pypi/pypi/-/regex/2020.7.14)

### CODE REVIEW

**Comment by capfei** [comment]
Need to get clarification if the Python 2.0 or CNRI Python license applies or both. Headers from the forked module it based off of list CNRI, but it also apart of the larger Python code.

**Comment by RicardoPadillaMicrosoft** [comment]
I believe you are right, headers state the License is CNRI and PyPi webpage only states "Python Software Foundation License". I if we base off the contents of the module CNRI is the correct License.

**Comment by royaljust** [comment]
@capfei I agree with @RicardoPadillaMicrosoft. Based on this: https://bitbucket.org/mrabarnett/mrab-regex/issues/362/any-license-work-for-this-project, it appears that the author wants to license this under the PSF license with the CNRI license included. Maybe we should reach out to the author for clarification? Perhaps we should say Python 2.0, which includes the CNRI license? https://spdx.org/licenses/Python-2.0.html? @pombredanne @bduranc what are your thoughts here?

**Comment by capfei** [comment]
Closing since we couldn't come to an agreement on how this should curated.

**Comment by capfei** [comment]
I'm reopening this since I found in the Python 1.6 license FAQ that derivative works can use a different license as long as it was compatible. I have provided the links to the author and waiting to see his response.

https://www.python.org/download/releases/1.6.1/license-faq Bullets 13 and 14

**Comment by dciborow** [comment]
Could use this PR to complete. Thanks!

**Comment by RicardoPadillaMicrosoft** [comment]
@capfei Is there any update from component author? We would like to have this merged.

**Comment by capfei** [comment]
@RicardoPadillaMicrosoft I responded to the author letting him know that it should be OK to add the Apache license and state that some portions are covered under CRNI. Hopefully, he will see that and make the updates.

**Review by capfei — APPROVED** [review]

**Comment by capfei** [comment]
The author has declared the license as Apache 2.0. Updated this PR to reflect that.
https://bitbucket.org/mrabarnett/mrab-regex/issues/362/any-license-work-for-this-project

**Pull request merged**
