### PR TITLE
Hic.Mustache.MSBuild 0.0.67

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
Hic.Mustache.MSBuild 0.0.67

**Details:**
Add MIT License

**Resolution:**
License Url:
https://github.com/oyvindh/Mustache.MSBuild/blob/main/LICENSE

Description:
This is the LICENSE file in the component's github repo. Explicitly defining it as having an MIT license. 
The repo is also tagged as having an MIT License in github.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [Hic.Mustache.MSBuild 0.0.67](https://clearlydefined.io/definitions/nuget/nuget/-/Hic.Mustache.MSBuild/0.0.67)

### CODE REVIEW

**Review by capfei — APPROVED** [review]

**Comment by capfei** [comment]
No license info in package, no source package listed, and the author's other package also has no license/source information. Updated to NONE.

**Comment by formalatist** [comment]
Can you clarify? Is the LICENSE file in the repo that is linked, https://github.com/oyvindh/Mustache.MSBuild/blob/main/LICENSE, not enough?

**Comment by capfei** [comment]
@formalatist There is nothing in the package linking to this repo to indicate that this should be the license for the package.

**Comment by formalatist** [comment]
@capfei Is this a valid way of fixing this? https://github.dev/formalatist/curated-data/tree/patch-1. License info is included in latest version of the package, as you can see here https://www.nuget.org/packages/Hic.Mustache.MSBuild/0.0.68/License

**Comment by capfei** [comment]
@formalatist Absolutely! Getting the author to add the license info and/or source location is a great help and I can use that to apply license info to previous versions.

**Pull request merged**
