### PR TITLE
SixLabors.ImageSharp 3.0.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
SixLabors.ImageSharp 3.0.1

**Details:**
Add LicenseRef-scancode-six-labors-split-1.0 License

**Resolution:**
License Url: 
https://scancode-licensedb.aboutcode.org/six-labors-split-1.0.html

Description:
This license is found in the repository of the ImageSharp library

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [SixLabors.ImageSharp 3.0.1](https://clearlydefined.io/definitions/nuget/nuget/-/SixLabors.ImageSharp/3.0.1)

### CODE REVIEW

**Comment by capfei** [comment]
@AE49 Based on the license information, I think this should be Apache-2.0 OR OTHER. What do you think?
https://www.nuget.org/packages/SixLabors.ImageSharp/3.0.1/License

**Comment by AE49** [comment]
@capfei I agree with you.

**Comment by ariel11** [comment]
@AE49 and @capfei - I think this should be curated OTHER.  In this case, all end users do not have the choice between Apache-2.0 and a commercial license.  The license here is "Six Labors Split License," which we'd curate as OTHER.  Within the 'Six Labors Split License" is the option for _a limited set of users_ who meet the "Six Labors Split License" requirements to use the code under Apache. However, that is not a license choice for everyone.  So I would curate the "Six Labors Split License" on the whole simply as "OTHER."  If you agree, please update the curation.  Thanks

**Comment by capfei** [comment]
@ariel11 Tried getting other feedback from the discord community but received no responses. After thinking on it a bit, I agree that this is just the "Six Labors Split License". I will get versions 3.0.0 and higher updated to `OTHER`.

**Pull request merged**
