### PR TITLE
Revert "dotnet/runtime 38017c3935de95d0335bac04f4901ddfc2718656"

### PR DESCRIPTION
**Pull request by AE49**
Reverts clearlydefined/curated-data#7179

### CODE REVIEW

**Comment by AE49** [comment]
Should add OTHER for the Patent.txt

**Comment by AE49** [comment]
@capfei I merged this and realized after there is a Patent.txt file and I need to add OTHER for it. I did a Revert thinking it would give me the option to fix the file and approve again but that doesn't seem to be right. How do I make the fix?

**Comment by jeffmendoza** [comment]
Just make a new curation to add OTHER

**Comment by capfei** [comment]
@AE49 I agree with @jeffmendoza

**Pull request closed without merging**
