### PR TITLE
husky 5.2.0

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
husky 5.2.0

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/typicode/husky

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [husky 5.2.0](https://clearlydefined.io/definitions/npm/npmjs/-/husky/5.2.0)

### CODE REVIEW

**Comment by LandOfBliss** [comment]
Looked in the "Files" section on the ClearlyDefined definition.  Multiple license files and not clear which applies to package.
NPM does not include a license link
Github source indicates: MIT
Conclusion:  Declared license is MIT

**Comment by AE49** [comment]
@LandOfBliss @capfei I'm not sure how to handle the Parity and Patron license files in the repo, if they are discovered licenses? https://github.com/typicode/husky/blob/main/package.json 

There are a couple of places where I see only MIT mentioned.
"After the early access, husky v5 will be MIT again" (https://www.npmjs.com/package/husky/v/5.2.0)
https://typicode.github.io/husky/#/?id=license

Are we in agreement on MIT or should this be "MIT AND OTHER"?

**Comment by capfei** [comment]
@AE49 @LandOfBliss The package.json states `Parity-7.0.0 AND MIT WITH Patron-1.0.0`. They didn't actually switch back to MIT until version 6.0.0. See https://github.com/typicode/husky/issues/857.

I have the same question on #10155. I think it should be `OTHER AND MIT WITH OTHER`.

**Comment by ariel11** [comment]
Looks like there is SPDX for Parity-7.0.0. Thoughts on going with Parity-7.0.0 WITH OTHER AND MIT @capfei ?

**Review by AE49 — APPROVED** [review]

**Comment by capfei** [comment]
@AE49 #10155 has been updated with "MIT AND Parity-7.0.0 AND OTHER". Since this version has the same license, I would go with that.

**Pull request merged**
