### PR TITLE
zeromq/libzmq 2cb1240db64ce1ea299e00474c646a2453a8435b

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
zeromq/libzmq 2cb1240db64ce1ea299e00474c646a2453a8435b

**Details:**
Add LGPL-3.0 License

**Resolution:**
License Url: 
https://github.com/zeromq/libzmq/blob/master/COPYING.LESSER

Description:
Provided in the project repo - https://github.com/zeromq/libzmq/blob/master/COPYING.LESSER

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [libzmq 2cb1240db64ce1ea299e00474c646a2453a8435b](https://clearlydefined.io/definitions/git/github/zeromq/libzmq/2cb1240db64ce1ea299e00474c646a2453a8435b)

### CODE REVIEW

**Comment by TRQ3** [comment]
1. Package files points to LGPL version 3 or later. 
2. Source repo for specific commit shows LGPL version 3 or later. 
3. src file looks to confirm LGPL version 3 or later. 

Should be curated as LGPL version 3 or later.

**Comment by ariel11** [comment]
@TRQ3 - I agree with "LGPL-3.0-or-later," though there's also additional licensing text.  The text is close to the classpath exception, but does not match.  We've been using "WITH OTHER" in situations like this, so I think this would be "LGPL-3.0-or-later WITH OTHER."  @capfei  - do you agree? 

image

**Comment by capfei** [comment]
@ariel11 Yes, I agree with 'WITH OTHER'.

**Comment by ariel11** [comment]
@TRQ3 - capfei confirmed and I have now updated  the "Files changed" tab to LGPL-3.0-or-later WITH OTHER.  Thanks!

**Review by TRQ3 — APPROVED** [review]

**Review by TRQ3 — APPROVED** [review]

**Pull request merged**
