### PR TITLE
johnlonganecker/libpostal-rest babf16cee439f891fbdbaa22c9a86724a4720d75

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
johnlonganecker/libpostal-rest babf16cee439f891fbdbaa22c9a86724a4720d75

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/johnlonganecker/libpostal-rest/blob/master/LICENSE

Description:
The MIT license looks good, and we're not distributing our product to entities outside Microsoft

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [libpostal-rest babf16cee439f891fbdbaa22c9a86724a4720d75](https://clearlydefined.io/definitions/git/github/johnlonganecker/libpostal-rest/babf16cee439f891fbdbaa22c9a86724a4720d75)

### CODE REVIEW

**Comment by LandOfBliss** [comment]
Looked in the "Files" section on the ClearlyDefined definition. Readme links to source code project.
No Nuget License field.
Source code project includes MIT
Conclusion:  Declared license is MIT

**Comment by ariel11** [comment]
@LandOfBliss - this is a GitHub commit vs. a package.  I don't see any license info in this commit.  The reference to the MIT license in the GitHub UI under "About" is not commit specific.  It looks like the MIT License was added Apr 16, 2021.  The date of this particular commit is  May 3, 2017.  So, for this commit, I would curate the declared license as "NONE."

Adding @capfei for her thoughts

**Comment by AE49** [comment]
@ariel11 @LandOfBliss @capfei I agree there's no license for this commit. With that said, there is a license for a newer version of the component and I'm thinking we can apply #3 Troubleshooting in Curation Guidelines. Thoughts?

**Comment by ariel11** [comment]
@AE49 - I recently updated the curation guidelines to make it more clear that the [troubleshooting guideline](https://github.com/clearlydefined/clearlydefined/blob/master/docs/curation-guidelines.md#troubleshooting) number 3 is just for _packages_, not commits.  I think it makes sense for git commits to stay commit specific.  I'll update this to "NONE."

Cc: @LandOfBliss  and @capfei

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
