### PR TITLE
com.guardsquare:proguard-base 7.1.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
com.guardsquare:proguard-base 7.1.1

**Details:**
Add GPL-2.0-only License

**Resolution:**
License Url: 
https://github.com/Guardsquare/proguard/blob/master/LICENSE

Description:
The link above is to the source code on github.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [proguard-base 7.1.1](https://clearlydefined.io/definitions/maven/mavencentral/com.guardsquare/proguard-base/7.1.1)

### CODE REVIEW

**Comment by LandOfBliss** [comment]
Looked in the “Files” section on the ClearlyDefined definition. Nuspec License URL links GPL-2.0-only
Maven POM includes GPL-2.0-only
Conclusion:  Declared license is GPL-2.0-only

**Comment by capfei** [comment]
@LandOfBliss The license text for "only" and "or-later" are the same. Checking the file headers in the source code is how you distinguish which ones applies. From https://spdx.org/licenses/GPL-2.0-only.html:

> This license was released: June 1991. This license identifier refers to the choice to use the code under GPL-2.0-only, as distinguished from use of code under GPL-2.0-or-later (i.e., GPL-2.0 or some later version). ___**The license notice (as seen in the Standard License Header field below) states which of these applies to the code in the file.**___ The example in the exhibit to the license shows the license notice for the "or later" approach.

Looking in the source files, it looks to be GPL 2.0 or later:
```
/*
 * ProGuard -- shrinking, optimization, obfuscation, and preverification
 *             of Java bytecode.
 *
 * Copyright (c) 2002-2020 Guardsquare NV
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */
```

Do you agree that it should be GPL-2.0-or-later?

**Comment by BrianGreenMS** [comment]
Updated https://github.com/clearlydefined/curated-data/pull/14603

**Comment by capfei** [comment]
Closing in favor of #14603

**Pull request closed without merging**
