### PR TITLE
ProjNET4GeoAPI 1.4.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
ProjNET4GeoAPI 1.4.1

**Details:**
Add LGPL-2.1-only License

**Resolution:**
License Url: 
https://github.com/NetTopologySuite/ProjNet4GeoAPI/blob/develop/LICENSE

Description:
As specified on project's github page.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [ProjNET4GeoAPI 1.4.1](https://clearlydefined.io/definitions/nuget/nuget/-/ProjNET4GeoAPI/1.4.1)

### CODE REVIEW

**Comment by TRQ3** [comment]
1. No info in package files. 
2. Meta data points to LGPL 2.1 only. https://raw.githubusercontent.com/NetTopologySuite/ProjNet4GeoAPI/master/LICENSE
3. Source repo for tagged version points to LGPL 2.1 only. https://github.com/NetTopologySuite/ProjNet4GeoAPI/blob/v1.4/LICENSE
4. Nuspec links to same link from meta data showing LGPL 2.1 only. 

Should be curated as LGPL-2.1-only.

**Comment by AE49** [comment]
@TRQ3 The license expression noted in the scr folder in the repo is "LGPL-2.1-or-later" - https://github.com/NetTopologySuite/ProjNet4GeoAPI/blob/develop/src/ProjNet/ProjNET.csproj. Thoughts?

**Comment by TRQ3** [comment]
@AE49 I saw that, but figured that reference may have been in error or discovered, because the source repo, meta data, and Nuspec all pointed to LGPL 2.1 only. How do you think we should treat the "LGPL 2.1 or later" language in the src then?

**Comment by AE49** [comment]
@ariel11 Can we get our opinion on this? I think it should be LGPL-2.1-or-later and @TRQ3 is saying LGPL-2.1-only, same as Data Contributor. See details in our comments.

**Comment by ariel11** [comment]
@AE49 and @TRQ3 - Taking a look... The "License info" link for the NuGet goes to a copy of the LGPL-2.1 license.  Going to the "Project" link and looking at the source, I don't see a tagged version for 1.4.1, so looking at commit dates.  The NuGet was published 8/28/2018.  Found a commit matching that date here: https://github.com/NetTopologySuite/ProjNet4GeoAPI/tree/27c822ea83dda3e0c142851619f654d92c384b7f.   

Example file https://github.com/NetTopologySuite/ProjNet4GeoAPI/blob/27c822ea83dda3e0c142851619f654d92c384b7f/ProjNet/CoordinateSystems/FittedCoordinateSystem.cs.  Note the text says version "2," not "2.1."  So, I actually think we could curate this as "LGPL-2.0-or-later."  That would cover both this text _and_ LGPL-2.1...  Thoughts?  

image

I am also thinking of Section 13 of the LGPL-2.1 license that says:  "If the Library specifies a version number of this License which applies to it and "any later version", you have the option of following the terms and conditions either of that version or of any later version published by the Free Software Foundation.  "

**Comment by AE49** [comment]
@ariel11 @TRQ3 The copyright on the LGPL 2.0 text seems from earlier releases so I'm not convinced we need to cover it.

**Comment by ariel11** [comment]
@AE49 - "LGPL-2.0-or-later" works for both the source headers and the LGPL-2.1 LICENSE file.  The current src files have this same header referencing LGPL-2.0-or later - e.g. https://github.com/NetTopologySuite/ProjNet4GeoAPI/blob/develop/src/ProjNet/CoordinateSystemServices.cs.  

We can ask @royaljust or @capfei for an opinion.  

Thanks!

**Comment by AE49** [comment]
@ariel11 That makes sense. I agree with "LGPL-2.0-or-later" @TRQ3

**Review by TRQ3 — APPROVED** [review]

**Pull request merged**
