### PR TITLE
xlsx2csv 0.7.7

### PR DESCRIPTION
**Pull request by ariel11**
**Type:** Missing

**Summary:**
xlsx2csv 0.7.7

**Details:**
Inconsistent license info - LICENSE.txt is GPL-3.0, file header is GPL-2.0-or-later, and COPYING file is LGPL-2.0.  

**Resolution:**
Curating as GPL-2.0-or-later.

**Affected definitions**:
- [xlsx2csv 0.7.7](https://clearlydefined.io/definitions/pypi/pypi/-/xlsx2csv/0.7.7/0.7.7)

### CODE REVIEW

**Comment by ariel11** [comment]
Note - the repo has an open issue asking about the licensing inconsistency.  I curated based on the license information in the xlsx2csv.py file - GPL-2.0-or-later.  The "or-later" covers or includes the GPL-3.0 LICENSE.txt.
image

**Comment by capfei** [comment]
@ariel11 How confusing... Since it has a COPYING file, should we wait and see what they determine the correct license should be? I thought COPYING applied over LICENSE in a distribution. Please correct me if I am wrong.

**Comment by ariel11** [comment]
@capfei - Yes, let's wait for confirmation from the author on Issue 147.  (I see COPYING and LICENSE as equivalent file names for a project's main/primary license file.)

**Comment by capfei** [comment]
@ariel11 I submitted a PR to change license info to GPL 2.0. We'll see if the author accepts.

https://github.com/dilshod/xlsx2csv/issues/147
https://github.com/dilshod/xlsx2csv/pull/210

**Review by capfei — APPROVED** [review]

**Comment by capfei** [comment]
@ariel11 The author accepted my PR. Merging this.

**Pull request merged**
