### PR TITLE
python 3.7.5

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
python 3.7.5

**Details:**
Add PSF-2.0 License

**Resolution:**
License Url: 
https://docs.python.org/3.7/license.html

Description:
Reading the license URL it seems to be the only choice which fits?

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [python 3.7.5](https://clearlydefined.io/definitions/nuget/nuget/-/python/3.7.5)

### CODE REVIEW

**Comment by TRQ3** [comment]
1. Package files shows a rather long and unclear license file. Points to PSF 2.0. https://clearlydefined.io/file/1e28cb23e7511a272d5395e154e6540149a066e41903e72967c54df2582987ef
2. Meta data links to same long and unclear license language as above. https://www.nuget.org/packages/python/3.7.5/License
3. Nuspec does not show clear license, linking to a Microsoft site handling deprecated licenses. 

Leaning toward PSF 2.0, but curious to hear if you agree @ariel11. There is a difference between Python 2.0 and PSF 2.0. The language in the license files mentioned above shows a differing license schedule for various versions, this specific package falling in the latest license indication.

**Comment by AE49** [comment]
@capfei Declared license has been suggested as PSF-2.0. When I run the diff tool it seems the closest match is Pyton-2.0 but there are still some differences in the license text. How would you Declare this one?

@TRQ3

**Comment by capfei** [comment]
@AE49 I would curate as Python-2.0 since this is the Python license for Python 3.7.
https://docs.python.org/3.7/license.html

@ariel11 Thoughts?

**Comment by ariel11** [comment]
@TRQ3 - I am unclear on this one given the changes made to the license file.  Let's discuss with broader community.  Thanks

**Comment by ariel11** [comment]
Checking with SPDX: https://github.com/spdx/license-list-XML/issues/1200

**Comment by ariel11** [comment]
@capfei / @royaljust - The below shows a compare between the actual Python project license file and the SPDX "Python-2.0."  Given the differences, I think our guidelines (and the SPDX matching guidelines) would indicate we should curate this as "OTHER."  Do you agree?  If a SPDX identifier is later created for the actual Python project license, we could submit a PR to update these.

image

**Pull request merged**
