### PR TITLE
javax.servlet:jsp-api 2.0

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
javax.servlet:jsp-api 2.0

**Details:**
Add NONE License

**Resolution:**
License Url: 

Description:
Both CDDL, GPL2.0 are specified as licenses for javax.servlet:jsp-api in mvn. I am not sure which one to specify, so I picked No License.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [jsp-api 2.0](https://clearlydefined.io/definitions/maven/mavencentral/javax.servlet/jsp-api/2.0)

### CODE REVIEW

**Comment by LandOfBliss** [comment]
Looked in the “Files” section on the ClearlyDefined definition. Downloaded files indicate Apache-2.0
Maven does not include license field
Maven does not include source code page link.
Conclusion:  Declared license is Apache-2.0

**Comment by capfei** [comment]
@LandOfBliss I'm not finding any Apache license info. Where are you find it?

**Comment by ariel11** [comment]
There are several files in the "Resources" folder that have an Apache-2.0 license in the header.   https://mvnrepository.com/artifact/javax.servlet/jsp-api/2.0 indicates the license is GPL-2.0 and CDDL.  No info on POM.  Will check with curation community.

**Review by ariel11 — APPROVED** [review]

**Comment by ariel11** [comment]
Raised with ClearlyDefined community with Hen and the consensus is Apache-2.0, which matches the license info we found in the sources.jar.

**Pull request merged**
