### PR TITLE
Microsoft.FeatureManagement/1.0.0-preview-009000001-1251

### PR DESCRIPTION
**Pull request by TRQ3**
**Type:** Missing

**Summary:**
Microsoft.FeatureManagement/1.0.0-preview-009000001-1251

**Details:**
No info in package files. Meta data appears to link to wrong package. Found in github and confirmed MIT. 

**Resolution:**
https://github.com/microsoft/FeatureManagement-Dotnet/blob/1.0.0-preview-009000001-1251/LICENSE

**Affected definitions**:
- [Microsoft.FeatureManagement 1.0.0-preview-009000001-1251](https://clearlydefined.io/definitions/nuget/nuget/-/Microsoft.FeatureManagement/1.0.0-preview-009000001-1251/1.0.0-preview-009000001-1251)

### CODE REVIEW

**Comment by capfei** [comment]
@TRQ3 This looks to be apart of Azure App Configuration, so the license info could be correct. Did you open an issue with the source to confirm if the license info is correct or not?

**Comment by TRQ3** [comment]
@capfei I did not open an issue. Should we do that? I defer to your recommendation.

**Comment by capfei** [comment]
@TRQ3 Yes, if you feel there is mismatched information you should reach out to the author's for clarification. This is advised in the ClearlyDefined [curation guidelines](https://github.com/clearlydefined/clearlydefined/blob/master/docs/curation-guidelines.md#canonical-locations-for-the-declared-license-for-package-definitions).

I went ahead and opened an issue. We'll see if we get a response. :smile:
https://github.com/microsoft/FeatureManagement-Dotnet/issues/86

**Comment by ariel11** [comment]
@capfei - Looks like we can close this as a duplicate of https://github.com/clearlydefined/curated-data/pull/5347?

**Comment by capfei** [comment]
Closing

**Pull request closed without merging**
