### PR TITLE
Updating License for the component

### PR DESCRIPTION
**Pull request by vineetsetia**
**Type:** Missing

**Summary:**
Updating License for the component

**Details:**
The license for this component is shared at https://github.com/microsoft/fluentui/blob/master/LICENSE

**Resolution:**
This PR resolves issues related to License missing information.

**Affected definitions**:
- [react-icons-mdl2-branded 1.1.16](https://clearlydefined.io/definitions/npm/npmjs/@fluentui/react-icons-mdl2-branded/1.1.16/1.1.16)

### CODE REVIEW

**Comment by vineetsetia** [comment]
This is same as this PR:- https://github.com/clearlydefined/curated-data/pull/15245

**Comment by capfei** [comment]
@vineetsetia The package.json states:
```
"license": "SEE LICENSE IN LICENSE",
```
The license file in the package contents states:
```
@fluentui/react-icons-mdl2-branded

Copyright (c) Microsoft Corporation

All rights reserved.

Microsoft Fabric Assets License

Usage of the branded icons in this package is subject to the terms listed at https://aka.ms/fluentui-assets-license
```

This is a EULA, not MIT. The EULA is also listed in the README. EULAs are curated as OTHER. Do you agree that this should be OTHER? This will also be the same for #15245.

**Comment by vineetsetia** [comment]
I see similar components like @fluentui/react-icons-mdl2 are marked as MIT. Should those other components be changed to EULA/Other too?
https://www.npmjs.com/package/@fluentui/react-icons-mdl2

**Comment by capfei** [comment]
No, `@fluentui/react-icons-mdl2` does not need to changed since it licensed as MIT. It looks like some fluentui packages are licensed differently due to included icons.
```
This package contains branded icons from the MDL2 SVG icon set. Usage of these icons is subject to the Microsoft Fabric Assets License.
```

**Comment by vineetsetia** [comment]
Ok. It sounds good. We can mark it as "Other"

**Review by capfei — APPROVED** [review]

**Pull request merged**
