### PR TITLE
Missing declared license

### PR DESCRIPTION
**Pull request by capfei**
**Type:** Missing

**Summary:**
Missing declared license

**Details:**
Missing license

**Resolution:**
MIT: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/LICENSE

**Affected definitions**:
- [Microsoft.IdentityModel.Clients.ActiveDirectory 5.2.2](https://clearlydefined.io/definitions/nuget/nuget/-/Microsoft.IdentityModel.Clients.ActiveDirectory/5.2.2/5.2.2)

### CODE REVIEW

**Comment by ariel11** [comment]
@geneh - Can you please resolve the conflicts.  Thanks!

**Comment by capfei** [comment]
@ariel11 I can help resolve merge conflicts, if needed. Let me know.

**Comment by ariel11** [comment]
@capfei - Yes, that would be great if you could resolve the conflicts.  Maybe you can show me how to do it sometime.

**Comment by capfei** [comment]
Conflict resolved!

**Pull request merged**
