### PR TITLE
webrtc-uwp/libjpeg_turbo efcf55ff0e457a10aee8c6b6293dd74d778ef82d

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
webrtc-uwp/libjpeg_turbo efcf55ff0e457a10aee8c6b6293dd74d778ef82d

**Details:**
Add IJG License

**Resolution:**
License Url: 
https://raw.githubusercontent.com/webrtc-uwp/libjpeg_turbo/master/LICENSE.md

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [libjpeg_turbo efcf55ff0e457a10aee8c6b6293dd74d778ef82d](https://clearlydefined.io/definitions/git/github/webrtc-uwp/libjpeg_turbo/efcf55ff0e457a10aee8c6b6293dd74d778ef82d)

### CODE REVIEW

**Comment by TRQ3** [comment]
Package files have license file that links to source repo for this specific commit, but license language is unclear. https://github.com/webrtc-uwp/libjpeg_turbo/blob/efcf55ff0e457a10aee8c6b6293dd74d778ef82d/LICENSE.md

Can you make sense of this license language and how to curate, @AE49, @ariel11?

**Comment by AE49** [comment]
@TRQ3 @ariel11 I would Declare all three licenses for this package as outlined in the repo (see below). Declare field: "IJG AND BSD-3-Clause AND Zlib". Thoughts?

libjpeg-turbo is covered by three compatible BSD-style open source licenses:

The IJG (Independent JPEG Group) License, which is listed in README.ijg

This license applies to the libjpeg API library and associated programs (any code inherited from libjpeg, and any modifications to that code.)

The Modified (3-clause) BSD License, which is listed in turbojpeg.c

This license covers the TurboJPEG API library and associated programs.

The zlib License, which is listed in simd/jsimdext.inc

This license is a subset of the other two, and it covers the libjpeg-turbo SIMD extensions.

**Comment by ariel11** [comment]
@TRQ3 and @AE49 - this one doesn't fit neatly in our classification system of "discovered" vs. "declared," as they don't seem to give one overarching project license.  Rather, they break the project up into 3 parts, each with its own license.  I think it is fine to curate all 3 licenses in this case as "declared."

**Comment by AE49** [comment]
@TRQ3 I updated the yaml file. You can approve and merge

**Review by TRQ3 — APPROVED** [review]

**Pull request merged**
