### PR TITLE
git-python 1.0.3

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
git-python 1.0.3

**Details:**
Add BSD-3-Clause License

**Resolution:**
License Url: 
https://github.com/gitpython-developers/GitPython/blob/master/LICENSE

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [git-python 1.0.3](https://clearlydefined.io/definitions/pypi/pypi/-/git-python/1.0.3)

### CODE REVIEW

**Comment by peggymoloney** [comment]
No License in Files

setup.py has no License

No License in Download files

Curate as NONE

**Comment by ariel11** [comment]
@peggymoloney  - I think I agree with NONE, as the package does not have any license info and it links to a repo (https://github.com/pynickle/git-python) without any license info.  What is in the package/repo may come from here (https://github.com/gitpython-developers/GitPython), however as far as the package goes, I agree with "NONE" for the "Declared" license.  Do you agree @capfei ?

**Review by ariel11 — APPROVED** [review]

**Comment by ariel11** [comment]
@nellshamrell - there seems to be a bug with merging "NONE."

**Comment by peggymoloney** [comment]
@nellshamrell Hi Nell, can you fix the bug with "NONE" as declared license so we can merge please.

Thanks.
Peggy

**Comment by nellshamrell** [comment]
Closing in favor of #11160

**Comment by nellshamrell** [comment]
Hi @peggymoloney! Looks like the bug was fixed, but we need to open a new pull request in order for the validation to pass. I opened a new one at #11160

**Pull request closed without merging**
