### PR TITLE
xpp3:xpp3 1.1.3.3

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
xpp3:xpp3 1.1.3.3

**Details:**
Add Apache-1.1 License

**Resolution:**
License Url: 
https://mvnrepository.com/artifact/xpp3/xpp3

Description:
Says apache 1.1

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [xpp3 1.1.3.3](https://clearlydefined.io/definitions/maven/mavencentral/xpp3/xpp3/1.1.3.3)

### CODE REVIEW

**Comment by peggymoloney** [comment]
I'm not finding a license anywhere in this repository https://mvnrepository.com/artifact/xpp3/xpp3/1.1.3.3 checked pom and jar - also opened "view all" https://repo1.maven.org/maven2/xpp3/xpp3/1.1.3.3/ and didn't find any license info in any of those files?

**Comment by ariel11** [comment]
@peggymoloney  - I dont see a sources.jar either.  I am not sure how to open and view class files.  I am not see any license info but lets check with @capfei.

**Comment by capfei** [comment]
@ariel11 I know the later versions of this package have source jars and license info, but I couldn't find anything in this version. The site no longer exists and the archived site is a bit of a pain to navigate.

**Comment by ariel11** [comment]
@capfei - I see what you mean.  We can curate a version based on license info from another version, per the curation guidelines.  Do you agree the Indiana University Extreme! Lab Software License, vesion 1.1.1 license would be the "declared" license and the other licenses "discovered"?
image

Doing a search, I think this at least gives us a copy of the Indiana University Extreme! Lab Software License, vesion 1.1.1 license.  No SPDX for this that I see.
image

**Comment by capfei** [comment]
@ariel11 👍 Yep, I would go with OTHER since the other licenses clearly state they are for specific files, not the overall project.

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
