### PR TITLE
Declared License

### PR DESCRIPTION
**Pull request by AE49**
**Type:** Incomplete

**Summary:**
Declared License

**Details:**
Adding Other. Under a Microsoft EULA.

**Resolution:**
https://docs.microsoft.com/en-us/ef/ef6/resources/licenses/ef5/enu

**Affected definitions**:
- [EntityFramework 5.0.0](https://clearlydefined.io/definitions/nuget/nuget/-/EntityFramework/5.0.0/5.0.0)

### CODE REVIEW

**Comment by ariel11** [comment]
@fossygirl - do you want us to curate "other" for Microsoft EULAs?

**Comment by fossygirl** [comment]
@ariel11 No, these should not be curated, they're not open source.

**Comment by ariel11** [comment]
@fossygirl - I will close this PR then (w/o merging).  Thanks!

**Comment by ariel11** [comment]
Closing as not OSS

**Pull request closed without merging**
