### PR TITLE
AE49_180824_215616.966

### PR DESCRIPTION
**Pull request by AE49**
Add MIT (https://github.com/icsharpcode/SharpZipLib/blob/master/LICENSE.txt)

### CODE REVIEW

**Comment by AE49** [comment]
@capfei On the NuGet page, the license link is showing MIT for version 0.87.20170615.10 (https://www.nuget.org/packages/JetBrains.SharpZipLib.Stripped/0.87.20170615.10), and the project link on the same page directing to GitHub also has MIT. Does this help?

**Comment by capfei** [comment]
Thank you for the link, but that points to a different NuGet package. The one listed in the pull request is [SharpLibZib@0.86.0](https://www.nuget.org/packages/SharpZipLib/0.86.0). The link you provided is for JetBrains.SharpZipLib.Stripped@0.87.20170615.10. Going by the source repo at the time the package was published, it looks like the license should be [GPL 2.0](https://github.com/icsharpcode/SharpZipLib/blob/0.86.0.518/doc/COPYING.txt).

If this looks correct to you, I can update the pull request.

**Comment by ariel11** [comment]
@capfei - SharpZipLib 0.86.0 is GPLv2 + special exception

**Comment by fossygirl** [comment]
@ariel11 @capfei I've updated the YAML per our discussion

**Pull request merged**
