### PR TITLE
WebDriver.IEDriver.32-bit 2.33.0

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
WebDriver.IEDriver.32-bit 2.33.0

**Details:**
Add Unlicense License

**Resolution:**
License Url: 
https://www.nuget.org/packages/Selenium.WebDriver.IEDriver

Description:
The page says it follows the unlicense policy.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [WebDriver.IEDriver.32-bit 2.33.0](https://clearlydefined.io/definitions/nuget/nuget/-/WebDriver.IEDriver.32-bit/2.33.0)

### CODE REVIEW

**Comment by LandOfBliss** [comment]
1.  Looked in the "Files" section on the ClearlyDefined definition. License file is missing. Checked files with SPDX license indicated but did not find a license.   https://clearlydefined.io/definitions/nuget/nuget/-/WebDriver.IEDriver.32-bit/2.33.0   
2. Looked in package   metafile data.  No license file linked    https://www.nuget.org/packages/WebDriver.IEDriver.32-bit/2.33.0   3. Looked for source.  There isn’t source code but readme   indicates: “Archive of Selenium's issue tracker imported from Google Code”   and links to Archive, please see main selenium repo:  https://github.com/seleniumhq/selenium”  The Main Selenium repo indicates Apache   license:   https://github.com/SeleniumHQ/selenium/blob/trunk/LICENSE   
4.  The Resolution License   URL: https://www.nuget.org/packages/Selenium.WebDriver.IEDriver page includes a link to the license as: Unlicense.   This appears to be a different component   and/or version 3.150.1.2) https://licenses.nuget.org/Unlicense  
5. Conclusion: Apache likely

**Comment by ariel11** [comment]
@LandOfBliss - I think I'd go with "NONE" here because the "Project Site" link (https://github.com/seleniumhq/selenium-google-code-issue-archive) goes to a repo without a license file.  I do see the link to the "new" repo but that repo's LICENSE file was added in 2015 whereas this NuGet package was published in 2013.

@capfei  - do you see any license info that dates back to 2013 for this package?

**Comment by capfei** [comment]
@ariel11 I would agree with Apache since the license points to an issue repo that states that the main repo is located at https://github.com/SeleniumHQ/selenium/. Looking at version 2.33.0, it has a COPYING file instead a license file.

https://github.com/SeleniumHQ/selenium/blob/selenium-2.33.0/COPYING

**Comment by ariel11** [comment]
@capfei  - good catch.  The COPYING file goes back to 2009.  However, do we see evidence that this NuGet is built from this repo?  I am not initially seeing the IEDriverServer here, which looks like the exe in this NuGet?  I see [this](https://github.com/SeleniumHQ/selenium/blob/selenium-2.33.0/dotnet/src/WebDriver/IE/InternetExplorerDriverService.cs), which says it "Exposes the service provided by the native IEDriverServer executable."  Thoughts?

**Comment by capfei** [comment]
@ariel11 I found it in the `cpp` folder: https://github.com/SeleniumHQ/selenium/tree/selenium-2.33.0/cpp/IEDriverServer

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
