### PR TITLE
encoding_rs 0.8.30

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
encoding_rs 0.8.30

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/hsivonen/encoding_rs/blob/master/LICENSE-MIT

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [encoding_rs 0.8.30](https://clearlydefined.io/definitions/crate/cratesio/-/encoding_rs/0.8.30)

### CODE REVIEW

**Comment by ariel11** [comment]
@AE49 - I think this would be "MIT OR Apache-2.0" per https://clearlydefined.io/file/11789f45bb180841cd362a5eee6789c68ddb573a11105e30768c308a6add0190.  Do you agree?

**Comment by AE49** [comment]
@ariel11 I agree with the MIT OR Apache-2.0 part. Do we also need to Declare the BSD-3-Clause license as well?
https://github.com/hsivonen/encoding_rs#licensing

**Comment by ariel11** [comment]
@AE49 - I think the BSD reference would be "discovered."  Agree?

**Comment by AE49** [comment]
@ariel11 Agree.

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
