### PR TITLE
protobuf-net 2.3.7

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
protobuf-net 2.3.7

**Details:**
Add Apache-2.0 License

**Resolution:**
License Url: 
https://github.com/protobuf-net/protobuf-net/blob/master/Licence.txt

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [protobuf-net 2.3.7](https://clearlydefined.io/definitions/nuget/nuget/-/protobuf-net/2.3.7)

### CODE REVIEW

**Comment by capfei** [comment]
The license lists Apache and BSD (for Google), but it looks like the author states that the BSD license text is there as a courtesy and that the library (such as the DLLs) do not use Google code.
https://github.com/protobuf-net/protobuf-net/issues/316#issuecomment-341388096

The author does state there are some files from Google in the `Tools` folder, but the NuGet package does not contain these.

This package has been curated as `Apache-2.0 AND BSD-3-Clause` due to the language in the license, but it looks like only Apache applies to the NuGet package. What do others think? Should the other versions that have been curated be updated to Apache only?

**Comment by ariel11** [comment]
@capfei - I read the license as saying the original project was BSD licensed and this .NET implementation of that code is Apache.  So I think "BSD-3-Clause AND Apache-2.0" is correct.

**Comment by ariel11** [comment]
@royaljust - can you comment?

**Comment by royaljust** [comment]
Agree with Ariel here, translating some code into a C# NuGet implementation still might be considered a modification of the original BSD-3-Clause license code and that is what the developer is signaling. Thus, we should respect both. Interested in others thoughts. @pombredanne and @bduranc any thoughts?

**Comment by bduranc** [comment]
For this case, what Ariel suggested would probably make the most sense.

**Comment by capfei** [comment]
Thanks, everyone! I have updated the PR.

**Pull request merged**
