### PR TITLE
Coding4Fun.Toolkit.Controls 2.1.8

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
Coding4Fun.Toolkit.Controls 2.1.8

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/Coding4FunProjects/Coding4FunToolkit

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [Coding4Fun.Toolkit.Controls 2.1.8](https://clearlydefined.io/definitions/nuget/nuget/-/Coding4Fun.Toolkit.Controls/2.1.8)

### CODE REVIEW

**Comment by TRQ3** [comment]
https://github.com/Coding4FunProjects/Coding4FunToolkit

There are no tagged versions. The ReadMe mentions MIT license. Thoughts, @capfei?

**Comment by capfei** [comment]
@TRQ3 I'm inclined to go with MIT since the project was moved to GitHub after the release of 2.1.0 (that's the version listed in the nuspec in the CodePlex archive), even though the license link still points to CodePlex. They added the statement about MIT on January 23, 2015. 2.1.8 was published on May 12, 2016.

@ariel11 What do you think?

**Comment by ariel11** [comment]
@TRQ3 , @capfei - let's ask the curation community.  I'll add to Nov 9 agenda.

**Comment by ariel11** [comment]
Nov 11 - posted to curation community how to curate this one.  

Posted:  "Looking for curation thoughts on this one -  NuGet https://www.nuget.org/packages/Coding4Fun.Toolkit.Controls/2.1.8.
a.    License link says “MS-PL” and then goes to CodePlex.  I downloaded the CodePlex archive and it appears to be for older versions (not 2.1.8)
b.    Project Site link goes to repo.  The repo says "Disclaimer The code is licensed using MIT License and attribution is optional."  This text was added prior to the package publish date.  So, I would be inclined to go with "MIT" over "MS-PL."  However, what to do about the "...and attribution is optional."  Does that make the "declared" "OTHER" or "MIT WITH OTHER," as the additional text is more like an exception to the MIT license?"

**Comment by capfei** [comment]
@ariel11 I like `MIT WITH OTHER`. It keeps it consistent with the other exceptions.

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
