### PR TITLE
Corrected license info for NetMQ.

### PR DESCRIPTION
**Pull request by cgranade**
**Type:** Incorrect

**Summary:**
Corrected license info for NetMQ.

**Details:**
The license was marked as NOTDECLARED.

**Resolution:**
The license was updated to the correct definition of LGPL 3.0 (exact).

**Affected definitions**:
- [NetMQ 4.0.0.1](https://clearlydefined.io/definitions/nuget/nuget/-/NetMQ/4.0.0.1)

### CODE REVIEW

**Comment by pombredanne** [comment]
@cgranade thank you ++ for this
You may not have noticed but https://github.com/zeromq/netmq/blob/4.0.0.1/COPYING.LESSER#L171 has some extra terms at the end. 

The exception is this https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/zeromq-exception-lgpl-3.0.LICENSE but it is not known from SPDX.

Also it looks like all the notices in source code file point to an `LGPL-3.0-or-later` rather than a bare `LGPL-3.0-only`.

**Comment by ariel11** [comment]
@pombredanne - The extra language is so close to https://spdx.org/licenses/Classpath-exception-2.0.html#licenseExceptionText.  Here's the delta.
image.  It seems 'wrong' to curate this as "OTHER" due to this extra custom text, but that's what we have been doing in other instances...  @royaljust, thoughts?

Also, the ReadMe just says "This is an open source project licensed under the LGPLv3," so I would not have set the declared license to "or later" because that is not stated for the project level (just on some files).

**Comment by ariel11** [comment]
I would be included to curate this as "LGPL-3.0-only AND OTHER," where OTHER is for that extra text.  And I would do LGPL-3.0-only because the readme says "This is an open source project licensed under the LGPLv3."  Any files that say "or later' could be curated as such for that file.  Thoughts?

**Comment by ariel11** [comment]
Changing Declared license to "OTHER" due to non-SPDX recognized language on the license file.

**Pull request merged**
