### PR TITLE
Declaring license

### PR DESCRIPTION
**Pull request by ariel11**
**Type:** Missing

**Summary:**
Declaring license

**Details:**
NuGet license link 

**Resolution:**
https://raw.githubusercontent.com/OData/odata.net/master/LICENSE.txt

**Affected definitions**:
- [Microsoft.OData.Edm 7.6.0](https://clearlydefined.io/definitions/nuget/nuget/-/Microsoft.OData.Edm/7.6.0/7.6.0)

### CODE REVIEW

**Comment by ariel11** [comment]
Debated whether to do just MIT or MIT AND CC BY 3.0.  Both apply to the _repo_, though only MIT applies to the code. We should add what we decide to the trouble shooting section of the curation guidelines.

**Comment by capfei** [comment]
My first reaction is to say MIT since the NuGet doesn't contain any documentation, only code. I'll leave this open for a bit longer in case others want to provide their thoughts on this situation.

**Comment by capfei** [comment]
Adding a tag to help make it stand out

**Comment by ariel11** [comment]
@capfei - that makes sense.  And I think just MIT is consistent on other versions.   I am good with that.

**Pull request merged**
