### PR TITLE
MarkdownDeep.Full 1.5

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
MarkdownDeep.Full 1.5

**Details:**
Add Other License

**Resolution:**
License Url: 
https://www.toptensoftware.com/markdowndeep/license

Description:
This is the license linked on the Nuget page here: https://www.nuget.org/packages/MarkdownDeep.Full

**Affected definitions**:
- [markdowndeep.full 1.5.0](https://clearlydefined.io/definitions/nuget/nuget/-/markdowndeep.full/1.5.0)

### CODE REVIEW

**Comment by patricksimonson** [comment]
This is a PR from component governance's new missing license feature. Although, I submitted as Apache-2.0, it came through as declared: other. Looking into it.

**Comment by capfei** [comment]
@patricksimonson Let me know if you want this to stay open or if I can close it.

**Comment by patricksimonson** [comment]
@capfei - I don't have permissions to modify the branch. Any chance we can update this to be Apache-2.0 and go ahead with the curation?

**Comment by capfei** [comment]
@patricksimonson Yes, I will update it to Apache and then merge.

**Pull request merged**
