### PR TITLE
husky 5.1.3

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
husky 5.1.3

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/typicode/husky/blob/main/LICENSE

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [husky 5.1.3](https://clearlydefined.io/definitions/npm/npmjs/-/husky/5.1.3)

### CODE REVIEW

**Comment by capfei** [comment]
The package.json states the license:
```json
"license": "Parity-7.0.0 AND MIT WITH Patron-1.0.0"
```

Even though the README states:
> After the early access, husky v5 will be MIT again. 

It looks like that isn't the case. https://github.com/typicode/husky/issues/857

Per the declared license in the package.json, I think this should be "OTHER AND MIT WITH OTHER". @ariel11 What do you think?

**Comment by ariel11** [comment]
@capfei - What you suggested does follow the practice we've adopted of using the "WITH OTHER" expression for stated license exceptions that do not have a SPDX.  

However, I wonder if we can have "OTHER" here cover both Parity and Patron files, and just have "MIT AND OTHER?"

**Comment by capfei** [comment]
@ariel11 It looks they are stating that the Patron license is an exception to MIT per their license file:
```
License Zero Parity 7.0.0 (see LICENSE-PARITY file) and MIT (contributions, see LICENSE-MIT file) with exception License Zero Patron 1.0.0 (see LICENSE-PATRON file)
```

If we go by SPDX formatting, we should go with OTHER AND MIT WITH OTHER. 🤷‍♀️

**Comment by ariel11** [comment]
Looks like there is SPDX for Parity-7.0.0.  Thoughts on going with Parity-7.0.0 WITH OTHER AND MIT @capfei ?

**Review by capfei — APPROVED** [review]

**Comment by ariel11** [comment]
@capfei - I think I'm landing on "MIT AND Parity-7.0.0 AND OTHER," where OTHER stands for the Patron license.  That way the curation maps to the 3 license files and there's not a valid "WITH" SPDX exception to use here (nor is it clear, which license the Patron license goes 'with' or if its both).

**Comment by capfei** [comment]
It is valid! 🎉

**Pull request merged**
