### PR TITLE
Modernizr 2.7.1

### PR DESCRIPTION
**Pull request by LandOfBliss**
**Type:** Missing

**Summary:**
Modernizr 2.7.1

**Details:**
NuGet license field is MIT
Modernizr Licenes is MIT: https://modernizr.com/license/

**Resolution:**
MIT

**Affected definitions**:
- [Modernizr 2.7.1](https://clearlydefined.io/definitions/nuget/nuget/-/Modernizr/2.7.1/2.7.1)

### CODE REVIEW

**Comment by AE49** [comment]
@LandOfBliss The component is dual-licensed under "MIT and BSD" as noted in ClearlyDefined License file and GitHub repo page, although only the MIT license text is on the license file. I would curate as "MIT OR BSD-3-Clause". @ariel11 Thoughts?

https://clearlydefined.io/file/1e6227629cdb3e3630dabab6ab1f494d3d86eec7d6f5bee3e653a260dfea90c1
https://github.com/Modernizr/Modernizr/tree/v2.7.1

**Comment by capfei** [comment]
What is weird is when you look at the commit for this version, it says that it does not exist in any branches in the repo. Also, if you check commits around this commit, the file structure and license info is different. The Modernizr repo has been MIT only since [September 2012](https://github.com/Modernizr/Modernizr/commit/90e42c5de734ad74ff002b8086d48ece36d77559).

It looks like the commit for version 2.7.1 comes from this fork, https://github.com/patrickkettner/Modernizr/commits/v2.7.1, which doesn't seem to have updated the license change.
Repo history from version 2.7.1: https://github.com/Modernizr/Modernizr/commits/438b556b6232d3af53fd10a28e869d400b7019e0
History for the same date from the master branch: https://github.com/Modernizr/Modernizr/commits/b23aa04ac29bb71c28addd4cb6d5aae42249866e

Should we discuss this one further?

**Comment by ariel11** [comment]
We're thinking the declared license is just MIT due to the "license" file that is linked to from the package only having MIT.  Also, the repo had changed from dual licensed to just MIT by the time this package version was published.

**Comment by ariel11** [comment]
Updating version 2.7.2 to "MIT" per the above, as that package was also published past the license change in the repo.

**Review by AE49 — APPROVED** [review]

**Pull request merged**
