### PR TITLE
DnsRequestGroup 1.2.0

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
DnsRequestGroup 1.2.0

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/FakeItEasy/FakeItEasy/blob/master/License.txt

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [DnsRequestGroup 1.2.0](https://clearlydefined.io/definitions/nuget/nuget/-/DnsRequestGroup/1.2.0)

### CODE REVIEW

**Comment by peterysc** [comment]
Incorrect license mentioned here, please abort

**Comment by mihouc** [comment]
No license information on Clearly Defined
No license or repository information on Nuget site, no other versions listed
No license or repository information in package

License for package should be curated as NONE

**Comment by ariel11** [comment]
@mihouc - Agree with "NONE."  I updated the "Files changed" tab.

**Review by mihouc — APPROVED** [review]

**Comment by peterysc** [comment]
whats the reason for merging this?

**Comment by peterysc** [comment]
the given link is for fake easy package not dns request

**Comment by ariel11** [comment]
@peterysc - This PR was merged with "NONE" for the license information for this NuGet package https://www.nuget.org/packages/DnsRequestGroup/1.2.0.

**Comment by peterysc** [comment]
oh so for the ones that I could not find legal information, I could just list it as "NONE" and that is okay...?

**Comment by ariel11** [comment]
@peterysc - Yes, you can submit the PR with "NONE" for the license and we will double-check the PR before merging.

**Pull request merged**
