### PR TITLE
GnuWin32.Bin 0.6.3

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
GnuWin32.Bin 0.6.3

**Details:**
Add GPL-2.0-only License

**Resolution:**
License Url: 
http://gnuwin32.sourceforge.net/license.html

Description:
https://www.nuget.org/packages/GnuWin32.Bin/

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [GnuWin32.Bin 0.6.3](https://clearlydefined.io/definitions/nuget/nuget/-/GnuWin32.Bin/0.6.3)

### CODE REVIEW

**Comment by peggymoloney** [comment]
No License in Files

GnuWin LIcense in License Info http://gnuwin32.sourceforge.net/license.html

No License in the Project Site or Download package

Curate at OTHER

**Comment by ariel11** [comment]
@capfei  - The license file (http://gnuwin32.sourceforge.net/license.html) essentially states there is no "declared" license ("_GnuWin does not impose licenses other than those that hold for the original sources_.").  Im not sure whether the "declared" license would be OTHER (for "http://gnuwin32.sourceforge.net/license.html") or NONE, as there doesn't appear to be a "declared" license, but rather, a collection of licenses.  Thoughts?

**Comment by capfei** [comment]
@ariel11 I'm leaning towards OTHER since they are stating what you can do with it and requesting that you disclose sources for using and/or redistributing GnuWin. This seems like a license to me.

**Comment by ariel11** [comment]
@capfei - Yes, I suppose "OTHER" makes more sense than "NONE" because there is license info...just not a single "declared" license that I can tell.

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
