### PR TITLE
Orleans.Contrib.UniversalSilo 0.9.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
Orleans.Contrib.UniversalSilo 0.9.1

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/johnazariah/orleans-contrib-universalsilo/blob/main/LICENSE

Description:
The LICENSE file is provided in the GitHub repository for this package.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [Orleans.Contrib.UniversalSilo 0.9.1](https://clearlydefined.io/definitions/nuget/nuget/-/Orleans.Contrib.UniversalSilo/0.9.1)

### CODE REVIEW

**Comment by capfei** [comment]
@AE49 I'm not finding any license info. NONE?

**Comment by xinyi-joffre** [comment]
@capfei , I'm not sure I understand what the feedback requested is:

The link is here where the MIT license is provided (in the PR description): https://github.com/johnazariah/orleans-contrib-universalsilo/blob/main/LICENSE

It is not NONE, the PR marks it as MIT.

**Comment by capfei** [comment]
@xinyi-joffre The reason I'm suggesting NONE is the NuGet package does not contain any license information nor does it point to this repo.

**Comment by capfei** [comment]
I tried looking at other versions of this repo and couldn't find any that linked to the repo listed in the PR comment. If I missed it, please link to the version of this NuGet package that contains the link.

**Comment by xinyi-joffre** [comment]
I don't own the nuget package, but the owner for the nuget package and the github repo is the same, and the nuget namespace matches. We're updating the license for the latest version of the package, but the prior versions of this package are also listed as MIT.
https://www.nuget.org/packages/Orleans.Contrib.UniversalSilo/ => owned by [johnazariah](https://www.nuget.org/profiles/johnazariah)

https://github.com/johnazariah/orleans-contrib-universalsilo => owned by johnasariah

**Comment by capfei** [comment]
@ariel11 Can I get your opinion?

**Comment by AE49** [comment]
@capfei I agree with NONE based on our curation guidelines. This version of the NuGet package does not have a license nor is there a clear link to the GitHub repo.  If the author wants to apply MIT to all versions, seems they should add a link to the GitHub repo?

**Comment by ariel11** [comment]
@capfei and @AE49 - I think in the past if we could make a solid connection between the repo and the package we went with the repo's license.  Ideally, we'd see an actual package metadata file like a nuspec. The names between the package owner and this repo do match.  Thoughts on opening an Issue and asking if the repo's MIT license applies to this NuGet package? https://www.nuget.org/packages/Orleans.Contrib.UniversalSilo/

**Comment by capfei** [comment]
Opened an issue asking about the license for the NuGet: https://github.com/johnazariah/orleans-contrib-universalsilo/issues/70

**Comment by johnazariah** [comment]
> I don't own the nuget package, but the owner for the nuget package and the github repo is the same, and the nuget namespace matches. We're updating the license for the latest version of the package, but the prior versions of this package are also listed as MIT already in ClearlyDefined. This is not a new package.
> 
> https://www.nuget.org/packages/Orleans.Contrib.UniversalSilo/ => owned by [johnazariah](https://www.nuget.org/profiles/johnazariah)
> 
> https://github.com/johnazariah/orleans-contrib-universalsilo => owned by [johnasariah]

I'd be delighted to help with this. Is there an accepted way of adding this metadata while packing?

Should I do something like rename the `LICENSE` file to `LICENSE.txt` and put this in the `.fsproj`?

```
  <PropertyGroup>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
  </PropertyGroup>
  <ItemGroup>
      <None Include="licenses\LICENSE.txt" Pack="true" PackagePath="LICENSE.txt"/>
  </ItemGroup> 
```

or should I doing something else with the `licenseUrl`? 

Sorry for the n00b question

**Comment by ariel11** [comment]
@johnazariah - thank you!  For this license database (ClearlyDefined), we are trying to validate the license for these (https://www.nuget.org/packages/Orleans.Contrib.UniversalSilo/) NuGet packages because we aren't seeing any license information in the package. We usually see the license information on the [nuspec file](https://learn.microsoft.com/en-us/nuget/reference/nuspec). Did you intend for these NuGet packages to be MIT like the source code repo?  If that's the case, with author clarification, we can put "MIT" in this license database.  Thank you!

**Comment by johnazariah** [comment]
Yes MIT would be fine. And I appreciate the help!

**Review by capfei — APPROVED** [review]

**Pull request merged**
