### PR TITLE
License

### PR DESCRIPTION
**Pull request by AE49**
**Type:** Incomplete

**Summary:**
License

**Details:**
Add MIT

**Resolution:**
https://github.com/jamiebuilds/create-react-context/blob/v0.2.3/LICENSE

**Affected definitions**:
- create-react-context 0.2.3

### CODE REVIEW

**Comment by capfei** [comment]
@AE49 Not sure this should be MIT since it is modified and adds the restrictions on who can use it. I would leave it as "No Assertion", but would love to hear others input.

**Comment by AE49** [comment]
I've been informed by Cliff Allen the restriction in the Jamie Builds was lifted.

**Comment by capfei** [comment]
The license was updated two weeks after this NPM version was published so I wouldn't treat this curation any differently. Since the license in the NPM package and the tagged source version contain the restricted license, it should be NO ASSERTION.

**Comment by ariel11** [comment]
@capfei - I agree that leaving this version as NOASSERTION makes sense.

**Comment by capfei** [comment]
For now, I am closing this PR.

**Pull request closed without merging**
