### PR TITLE
@progress/kendo-angular-popup 3.0.7

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
@progress/kendo-angular-popup 3.0.7

**Details:**
Add Apache-2.0 License

**Resolution:**
License Url: 
https://www.telerik.com/purchase/license-agreement/kendo-ui?utm_medium=referral&utm_source=npm&utm_campaign=kendo-ui-angular-trial-npm-popup

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [kendo-angular-popup 3.0.7](https://clearlydefined.io/definitions/npm/npmjs/@progress/kendo-angular-popup/3.0.7)

### CODE REVIEW

**Comment by AE49** [comment]
@mihouc This component is part of Kendo UI for Angular which requires a Telerik commercial license. I would curate as "OTHER", do you agree?
See description details on page here - https://www.npmjs.com/package/@progress/kendo-schematics/v/1.2.0

**Comment by mihouc** [comment]
@AE49 I agree this requires a commercial license and should be curated as OTHER

**Comment by mihouc** [comment]
@AE49 I agree this requires a commercial license and should be curated as OTHER

**Comment by AE49** [comment]
@mihouc I made the edit to the yaml file. Can you please approve and merge? Thanks.

**Review by AE49 — APPROVED** [review]

**Pull request merged**
