### PR TITLE
Declared License

### PR DESCRIPTION
**Pull request by ariel11**
**Type:** Incomplete

**Summary:**
Declared License

**Details:**
Copied the (deprecated) SPDX license identifier given here: https://github.com/ms-iot/u-boot/tree/abec1328dd13df76b19f5fd5ae3a5f3275110c8c/Licenses

**Resolution:**
In the ReadMe: 
SPDX-License-Identifier: GPL-2.0

**Affected definitions**:
- [u-boot abec1328dd13df76b19f5fd5ae3a5f3275110c8c](https://clearlydefined.io/definitions/git/github/ms-iot/u-boot/abec1328dd13df76b19f5fd5ae3a5f3275110c8c/abec1328dd13df76b19f5fd5ae3a5f3275110c8c)

### CODE REVIEW

**Comment by AE49** [comment]
@pombredanne can we get your thoughts on this curation? @ariel11 copied the deprecated SPDX license and is wondering if we should keep the deprecated identifiers in the license option list.

**Comment by pombredanne** [comment]
We should always use the current latest version of ids. This is also what the latest scancode version does. Here we should use GPL-2.0-Only and not some legacy ids IMHO.

**Comment by ariel11** [comment]
Thanks @pombredanne and @AE49.  Given this https://github.com/ms-iot/u-boot/blob/abec1328dd13df76b19f5fd5ae3a5f3275110c8c/Licenses/Exceptions, I wonder if the "declared" field should actually be "GPL-2.0-only AND GPL-2.0-or later," since it says "U-Boot in general is covered by the GPL-2.0/GPL-2.0+."

**Comment by ariel11** [comment]
@AE49 - thoughts on the above?

**Comment by royaljust** [comment]
This further highlights the need for some consistency about how we think about our constructs of "declared" versus "discovered" licenses.  In this case, I'd go with GPL-2.0-only because, as a whole, this is the only way the component can be distributed, even though the majority of files might be GPL-2.0-or-later.

**Comment by ariel11** [comment]
Thanks, @royaljust.  I totally agree.  @AE49 - I updated the yaml so this should be ready to approve/merge.  Thanks everyone!

**Pull request merged**
