### PR TITLE
org.jruby:jruby 1.7.9

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
org.jruby:jruby 1.7.9

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/komiya-atsushi/lz4-ruby/blob/master/LICENSE.txt

Description:
This is the license for an Open Source Ruby gem, of which our repository is a fork.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [jruby 1.7.9](https://clearlydefined.io/definitions/maven/mavencentral/org.jruby/jruby/1.7.9)

### CODE REVIEW

**Comment by capfei** [comment]
@AE49 I can only find one version with license information, 1.7.0, which is already curated as CPL-1.0 OR GPL-2.0-or-later OR LGPL-2.1-or-later. Go with this?

**Comment by AE49** [comment]
@capfei In the source jar for version 1.7.9 I see this license information -

Bundle-License: http://www.gnu.org/licenses/gpl-3.0-standalone.html, h
 ttp://www.gnu.org/licenses/lgpl-3.0-standalone.html, http://www.eclip
 se.org/legal/epl-v10.html

Should this version be Declared as - EPL-1.0 OR GPL-3.0-only OR LGPL-3.0-only?

**Comment by capfei** [comment]
@AE49 I'm not seeing anything other than the MANIFEST (no license info) when I download 1.7.9 sources jar. Where are you finding this info?

**Comment by AE49** [comment]
@capfei Steps I followed (see "Bundle-License" below):

1.	[Maven Repository: org.jruby » jruby » 1.7.9 (mvnrepository.com)](https://mvnrepository.com/artifact/org.jruby/jruby/1.7.9)
2.	Clicked on “jar”
3.	Opened with 7zip and extracted files
4.	Text in the MANIFEST Word file:

Manifest-Version: 1.0
Built-By: enebo
Tool: Bnd-2.1.0.20130426-122213
Bundle-Name: JRuby 1.7.9
Created-By: Apache Maven Bundle Plugin
Bundle-Vendor: JRuby
Build-Jdk: 1.7.0_17
Bundle-Version: 1.7.9
Bnd-LastModified: 1386344841487
Bundle-ManifestVersion: 2
Bundle-License: http://www.gnu.org/licenses/gpl-3.0-standalone.html, h
 ttp://www.gnu.org/licenses/lgpl-3.0-standalone.html, http://www.eclip
 se.org/legal/epl-v10.html
Bundle-Description: JRuby 1.7.9 OSGi bundle
Bundle-SymbolicName: org.jruby.jruby
Bundle-DocURL: http://jruby.org
Archiver-Version: Plexus Archiver

**Comment by capfei** [comment]
@AE49 Ok, I see what I was doing wrong. I kept looking at the wrong jar! 🤦‍♀️ 

Looking into it a little more by following the link to http://jruby.org. This led me to the source repo and found that the 3.0 standalone licenses are an error: https://github.com/jruby/jruby/issues/4454

Also, I saw that they changed CPL to EPL with version 1.7.3: https://github.com/jruby/jruby/commit/330fef3b0fc18af477ccea19bd278669667f31bb

So, I think this should be `EPL-1.0 OR GPL-2.0-or-later OR LGPL-2.1-or-later` based on the above issues, the `COPYING` file in the source repo and the file headers.
https://github.com/jruby/jruby/tree/1.7.9?tab=readme-ov-file#license
https://github.com/jruby/jruby/blob/1.7.9/COPYING
https://github.com/jruby/jruby/blob/1.7.9/core/src/main/java/org/jruby/util/GenericMap.java

**Comment by AE49** [comment]
@capfei I agree with your Declared License - EPL-1.0 OR GPL-2.0-or-later OR LGPL-2.1-or-later. 

Thanks for sending the file headers - for some reason I was having a hard time finding 'or later' references.

**Review by capfei — APPROVED** [review]

**Pull request merged**
