### PR TITLE
Missing license for Mono.Security/5.4.0.201

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
Missing license for Mono.Security/5.4.0.201

**Details:**
Adding license, which currently shows as "No Assertion".

**Resolution:**
Source:
https://github.com/mono/mono/tree/2017-06
MIT License:
https://github.com/mono/mono/blob/2017-06/LICENSE

**Affected definitions**:
- [Mono.Security 5.4.0.201](https://clearlydefined.io/definitions/nuget/nuget/-/Mono.Security/5.4.0.201/5.4.0.201)

### CODE REVIEW

**Comment by ariel11** [comment]
@pombredanne - This NuGet - https://www.nuget.org/packages/Mono.Security/5.4.0.201 - doesn't have a license, source, or project link.  Do you see a connection between this NuGet and the source tree the curator gives above?  For packages with no license, source, or project links, I wonder if we curate "none?"

**Comment by pombredanne** [comment]
@AE49 @ariel11 the thing is that we need a clear trace ... I can see ` The owner has unlisted this package. This could mean that the package is deprecated or shouldn't be used anymore. `  on the home page https://www.nuget.org/packages/Mono.Security/5.4.0.201 AND this is a security-related package. For all these reason and unless you can reach out to the actual author/owner of the package for a statement, or that could explain and trace exactly how the binaries were built from the source I would not make the source location a curated thing. But may be there is a note field we can use instead to provide a clue?

**Comment by ariel11** [comment]
@pombredanne - Thanks! It sounds like we agree on not assuming the source location.  However, what do you think of curating the "declared" license field as "NONE," when we have no source/repo or license information on a package (such as this one)?  I can edit the 'declared' field on the .yaml to say "NONE" and merge, but I want at least 1 other person to chime in on that approach for a situation like this. I do see that #6 here (https://github.com/clearlydefined/clearlydefined/blob/master/docs/curation-guidelines.md) does say: "Curate the declared license as NONE when the component verifiably and intentionally has no license."  As an unlisted package with no source/license info, that sounds applicable here.

**Comment by pombredanne** [comment]
@ariel11 re:

> I do see that #6 here (https://github.com/clearlydefined/clearlydefined/blob/master/docs/curation-guidelines.md) does say: "Curate the declared license as NONE when the component verifiably and intentionally has no license." As an unlisted package with no source/license info, that sounds applicable here.

Agreed. NONE is the way to go for now

**Comment by pombredanne** [comment]
I wished we could have notes of sorts that show in the definition though

**Pull request merged**
