### PR TITLE
org.locationtech.jts.io:jts-io-common 1.16.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
org.locationtech.jts.io:jts-io-common 1.16.1

**Details:**
Add NONE License

**Resolution:**
License Url: 
https://github.com/locationtech/jts/blob/master/LICENSE_EDLv1.txt

Description:
https://mvnrepository.com/artifact/org.locationtech.jts.io/jts-io-common/1.16.1

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [jts-io-common 1.16.1](https://clearlydefined.io/definitions/maven/mavencentral/org.locationtech.jts.io/jts-io-common/1.16.1)

### CODE REVIEW

**Comment by LandOfBliss** [comment]
Looked in the “Files” section on the ClearlyDefined definition. Header indicates EPL-1.0
Pom indicates: EPL-1.0
Source code project license is: EPL-1.0
Conclusion:  Declared license is EPL-1.0

**Comment by capfei** [comment]
@LandOfBliss I don't see any license information in the pom, but the source files state EPL 1.0 or EDL 1.0. I think this should be EPL-1.0 OR BSD-3-Clause.

@AE49 Do you agree?

**Comment by LandOfBliss** [comment]
@capfei I downloaded the GeoJsonConstants.java file and it indicates EPL v1.  Please see screenshot.
EPL v1

**Comment by capfei** [comment]
@LandOfBliss I see EPL 1.0, but it also states EDL 1.0. This why I think it should be EPL-1.0 OR BSD-3-Clause.

@AE49 @ariel11 What do you think?

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
