### PR TITLE
pypi/pypi/-/matplotlib/3.4.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Auto

**Summary:**
pypi/pypi/-/matplotlib/3.4.1

**Details:**
Add OTHER license

**Resolution:**
Auto-generated curation. Newly harvested version 3.4.1 matches existing version 3.3.4. 
Matching metadata: registryData.info.license: 'PSF'

**Affected definitions**:
- [matplotlib 3.4.1](https://clearlydefined.io/definitions/pypi/pypi/-/matplotlib/3.4.1)

### CODE REVIEW

**Comment by AE49** [comment]
@capfei This could be Declared as PSF-2.0. PyPI metadata is PSF. The license is a close enough match with references to PSF and Python customized, but main licensing text was not changed. https://matplotlib.org/stable/users/license.html. Thoughts?

**Comment by AE49** [comment]
Same as #10486. Changing to PSF-2.0

**Review by AE49 — APPROVED** [review]

**Comment by saheel1115** [comment]
@AE49 Thanks a lot for taking this up!

After your changes, looks like the ClearlyDefined curation check was unsuccessful. How can we resolve that and complete the pull request?

--
Saheel (dev at microsoft)

**Comment by capfei** [comment]
@saheel1115 Validation is still failing for PSF-2.0 due to an issue with the bot. Will merge when resolved. Tracking in #11048.

**Comment by saheel1115** [comment]
@capfei Thanks for the update! I'll pass it forward to others in my team.

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
