### PR TITLE
NReco.PdfGenerator 1.2.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
NReco.PdfGenerator 1.2.1

**Details:**
Add NONE License

**Resolution:**
License Url: 

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [NReco.PdfGenerator 1.2.1](https://clearlydefined.io/definitions/nuget/nuget/-/NReco.PdfGenerator/1.2.1)

### CODE REVIEW

**Comment by capfei** [comment]
@AE49 I'm not sure how to curate this one. The site doesn't actually provide any information other than yes, you can use it for free with limitations. Otherwise, commerical license purchase.

From the FAQ on the product page (also the NuGet license link):
>[1. Can I use PdfGenerator in my commercial project for FREE?](https://www.nrecosite.com/pdf_generator_net.aspx#faq1)
NReco.PdfGenerator can be used for FREE in .NET apps that have only one single-server production deployment.
> 
> A commercial license is required for:
> Applications with multiple deployments, or one multi-server production deployment
SaaS apps

I downloaded the free examples zip and found in the README:
```
License
-------
PdfGenerator can be used for FREE only in non-SaaS apps that have only one single-server production deployment. 
A commercial license (included into enterprise source code pack) is required for:
1) Applications for external redistribution (ISV), multi-server deployments
2) SaaS deployments
```

Should this be `OTHER OR OTHER` to differentiate the free and commercial offering or just `OTHER` as-if this is all part of an overall license?

**Comment by ariel11** [comment]
@capfei - I checked the curation guidelines and don't see anything there that would help.  In this case, there's not really a central "LICENSE" file and it does seem more like there's two separate licensing options, so I think "OTHER OR OTHER" makes sense.  We have done that before: https://github.com/search?q=repo%3Aclearlydefined%2Fcurated-data+%22OTHER+OR+OTHER%22&type=code. Thoughts?

**Comment by ariel11** [comment]
@capfei - thoughts?  Thanks!

**Review by capfei — APPROVED** [review]

**Comment by capfei** [comment]
Updated to `OTHER OR OTHER`.

**Pull request merged**
