### PR TITLE
cssmin 0.3.2

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
cssmin 0.3.2

**Details:**
Add BSD-2-Clause License

**Resolution:**
License Url: 
https://github.com/jbleuzen/node-cssmin/blob/master/package.json

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [cssmin 0.3.2](https://clearlydefined.io/definitions/npm/npmjs/-/cssmin/0.3.2)

### CODE REVIEW

**Comment by LandOfBliss** [comment]
1.	Looked in the "Files" section in the ClearlyDefined definition.  No license file found. 
2.	Looked in the package.json in the "Files" section on the ClearlyDefined definition.  Package.json includes link to:  http://github.com/jbleuzen/node-cssmin
3.	Package page on npmjs: https://www.npmjs.com/package/cssmin/v/0.3.2  indicates license as NONE and includes link to source: https://github.com/jbleuzen/node-cssmin
4.	Looked in Github source repository.  There is no license file but the Readme file committed on 2012-10-14 (https://github.com/jbleuzen/node-cssmin/tree/88bb35b24ca745f335bdc3daf96f7edc0ff8471c)  matches the release date of cssmin 0.3.2 and states “cssmin is released under a BSD License” and links to: https://opensource.org/licenses/bsd-license.php
Conclusion:  Discovered license should be BSD-2-Clause

**Comment by ariel11** [comment]
Per Section 9 of https://github.com/clearlydefined/clearlydefined/blob/master/docs/curation-guidelines.md#troubleshooting, we don't consider the license URL http://opensource.org/licenses/bsd-license.php to be indicating which version of the BSD license the author intends.  So, when a project only says "BSD," we curate the declared as "BSD-3-Clause."

**Review by ariel11 — APPROVED** [review]

**Comment by ariel11** [comment]
@LandOfBliss and @capfei  - I merged this as "BSD-3-Clause," per the above Troubleshooting guideline however, it looks like the author clarified he meant BSD-2-Clause on a later version (https://clearlydefined.io/definitions/npm/npmjs/-/cssmin/0.4.3).  I think  we can conclude he meant past versions to also be BSD-2-Clause.  Do you agree @capfei ?

**Comment by capfei** [comment]
@ariel11 Yes, I agree.

**Comment by ariel11** [comment]
@capfei - OK, correcting with https://github.com/clearlydefined/curated-data/pull/10174

**Pull request merged**
