### PR TITLE
OPCFoundation.NetStandard.Opc.Ua.Core 1.4.368.53

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
OPCFoundation.NetStandard.Opc.Ua.Core 1.4.368.53

**Details:**
Add OTHER License

**Resolution:**
License Url: 
https://opcfoundation.org/license/source/1.11/index.html

Description:
Included in the NuGet package.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [OPCFoundation.NetStandard.Opc.Ua.Core 1.4.368.53](https://clearlydefined.io/definitions/nuget/nuget/-/OPCFoundation.NetStandard.Opc.Ua.Core/1.4.368.53)

### CODE REVIEW

**Comment by capfei** [comment]
@ariel11 I think this should be `GPL-2.0-only` OR OTHER since the included license file states:
```
Following are basic rules on how the OPC Foundation licenses the
different components:

 1. OPC UA core components (OPC UA Stacks, OPC UA Local Discovery Server
    - LDS) follow a dual-license model:
      * *OPC Foundation Corporate Members*: RCL
        <https://opcfoundation.org/license/rcl.html>
        enables OPC Foundation corporate members to deploy their
        applications using the core component sources without being
        required to disclose the application code.
         
      * *Users that are not OPC Foundation corporate-members*: GPL 2.0
        <https://opcfoundation.org/license/gpl.html>
        Based on the GPL 2.0 license terms these users must disclose
        their application code when using the core component sources.
```

What do you think?

**Comment by karok2m** [comment]
I've set it to `OTHER` to follow the previous requests for this package as seen in #17667 and #18828.

**Comment by ariel11** [comment]
Follow-up note - I do see we are not being consistent, and the two PRs linked to above were curated just "OTHER".   However, this does look like a OPC UA core component, which would fall under the dual license.  I think updating them all to "GPL-2.0-only OR OTHER" makes sense to me.  @capfei and @AE49  - thoughts?

**Review by capfei — APPROVED** [review]

**Comment by ariel11** [comment]
@capfei -  I didn't look too closely yesterday at the other versions - thanks for checking!  All sounds good. :)

**Pull request merged**
