### PR TITLE
NHibernate.SqlAzure 2.1.6

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
NHibernate.SqlAzure 2.1.6

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/MRCollective/NHibernate.SqlAzure/blob/master/LICENSE

Description:
Info provided from main github repository 

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [NHibernate.SqlAzure 2.1.6](https://clearlydefined.io/definitions/nuget/nuget/-/NHibernate.SqlAzure/2.1.6)

### CODE REVIEW

**Comment by capfei** [comment]
@AE49 @ariel11  I think this should be Apache-2.0. The license says that there is a version with and a version without Microsoft Transient Fault Handling library. Looking at the license, the standalone version is MIT but the bundled version uses their license. 
https://web.archive.org/web/20170326124620/http://entlib.codeplex.com/license

What do you think?

**Comment by AE49** [comment]
@capfei @ariel11 I'm thinking "MIT OR Apache-2.0" to cover both versions of the package.

**Comment by capfei** [comment]
The version without is a separate package: NHibernate.SqlAzure.Standalone.
https://www.nuget.org/packages/NHibernate.SqlAzure.Standalone

**Comment by capfei** [comment]
Discussed on call and opened an issue with the authors for clarification.
https://github.com/MRCollective/NHibernate.SqlAzure/issues/39

**Review by capfei — APPROVED** [review]

**Pull request merged**
