### PR TITLE
ReportUnit 1.2.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
ReportUnit 1.2.1

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/reportunit/reportunit/blob/master/LICENSE

Description:
reportunit/reportunit is licensed under the

MIT License

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [ReportUnit 1.2.1](https://clearlydefined.io/definitions/nuget/nuget/-/ReportUnit/1.2.1)

### CODE REVIEW

**Comment by TRQ3** [comment]
1. No info in package files. 
2. Meta data links to a site that is unavailable. 
3. Nuspec links to the same unavailable site above. 
4. The source repo cited in curation notes above seems to be correct for this package, but it has been archived. License shows MIT . Oddly enough, the license file has been edited a number of times, but all of those edits took place on the day it was released on February 12, 2017. 

What do you think, @ariel11?

**Comment by ariel11** [comment]
@capfei - Under “Tools” in the “Files” section, I see "ReportUnit.exe” is identified by the tooling as MIT, though I can’t open it, as an executable.  The NuGet package was released  10/15/2015.  We may have found the project repo, however the license file only dates back to 2017.  So, it appears this package pre-dates the repo. I don't see any other info for the other package versions. Do we go with what the tooling found as "MIT" on the .exe?

**Comment by capfei** [comment]
@ariel11 I was able to open the .exe using 7zip and found these:

> R e p o r t U n i t   [ T e s t S u i t e   S u m m a r y ]   v 1 . 1   |   h t t p : / / r e p o r t u n i t . r e l e v a n t c o d e s . c o m / 
C r e a t e d   b y   A n s h o o   A r o r a   ( R e l e v a n t   C o d e s )   |   R e l e a s e d   u n d e r   t h e   M I T   l i c e n s e

> R e p o r t U n i t   [ F o l d e r   S u m m a r y ]   v 1 . 1   |   h t t p : / / r e p o r t u n i t . r e l e v a n t c o d e s . c o m / 
C r e a t e d   b y   A n s h o o   A r o r a   ( R e l e v a n t   C o d e s )   |   R e l e a s e d   u n d e r   t h e   M I T   l i c e n s e

Also, I was able to find a link to a GitHub repo on https://web.archive.org/web/20160705032625/http://relevantcodes.com/reportunit-report-generator in the comments. The author refers to https://github.com/reportunit/reportunit in several responses, which also lists MIT.

I would definitely go with MIT.

**Comment by ariel11** [comment]
@TRQ3 - see above.  OK to merge as MIT.  Thanks!

**Review by TRQ3 — APPROVED** [review]

**Pull request merged**
