### PR TITLE
tomcat/jasper-runtime 5.5.12

### PR DESCRIPTION
**Pull request by LandOfBliss**
**Type:** Missing

**Summary:**
tomcat/jasper-runtime 5.5.12

**Details:**
License is Apache-2.0: https://github.com/sonatype-nexus-community/search-maven-org/blob/master/LICENSE.txt

**Resolution:**
Apache-2.0

**Affected definitions**:
- [jasper-runtime 5.5.12](https://clearlydefined.io/definitions/maven/mavencentral/tomcat/jasper-runtime/5.5.12/5.5.12)

### CODE REVIEW

**Comment by capfei** [comment]
@LandOfBliss  I'm not finding any license info. Where is that link in the package?

**Comment by LandOfBliss** [comment]
> @LandOfBliss I'm not finding any license info. Where is that link in the package?

@capfei I didn't find it in the package but here: https://mvnrepository.com/artifact/tomcat/jasper-runtime

**Comment by capfei** [comment]
That isn't a reliable source for license information. @ariel11 What do you think? I'm not finding any license info. NONE?

**Comment by ariel11** [comment]
@capfei  and @LandOfBliss - Yes, mvnrepository site is not considered a canonical source for license info.  We do have that curation guideline that says if a different package version has license info we can use that for curation purposes.  I checked the most recent package version, but it doesn't loook like the .pom has any license info and does not look like they are publishing a sources jar?

**Review by capfei — APPROVED** [review]

**Comment by ariel11** [comment]
@capfei - For something else, I was looking at this version of this package: https://repo1.maven.org/maven2/tomcat/jasper-runtime/5.5.9/ and it does have a sources.jar and we can see the Apache-2.0 code comments in the file headers.  I think we can use the curation guideline to update this package version to Apache-2.0 based on this other package version.  Thoughts?

**Comment by capfei** [comment]
@ariel11 Yes, we can update it. I think I need to write a script to search through and look for versions with a sources.jar. Clicking through 20 versions to find the only 2 with a sources.jar is too frustrating and time consuming. 😠

**Pull request merged**
