### PR TITLE
sacremoses/0.0.41

### PR DESCRIPTION
**Pull request by TRQ3**
**Type:** Missing

**Summary:**
sacremoses/0.0.41

**Details:**
No info in package files. Meta data confirms MIT. 

**Resolution:**
https://github.com/alvations/sacremoses/blob/master/LICENSE

**Affected definitions**:
- [sacremoses 0.0.41](https://clearlydefined.io/definitions/pypi/pypi/-/sacremoses/0.0.41/0.0.41)

### CODE REVIEW

**Comment by ariel11** [comment]
@TRQ3 - Where do you see MIT in the metadata?  I see the following on the README in the package:
License
====

GNU Lesser General Public License version 2.1 or, at your option, any later version.

**Comment by TRQ3** [comment]
@ariel11 I found it here. https://github.com/alvations/sacremoses/blob/master/LICENSE and the readme in the repo shows MIT too.

**Comment by ariel11** [comment]
@TRQ3 - I see you opened an Issue at the repo to clarify.  It looks like the source is MIT, but the license identified on the README in the package (sacremoses-0.0.41.tar.gz) is LGPL.

image

@capfei - thoughts on how you would curate this?

**Comment by capfei** [comment]
@ariel11 I would say LGPL for this version because https://github.com/alvations/sacremoses/pull/93 was merged into the `master` branch on May 3, 2020. The license file has a date of April 12, 2020 because it was committed to the `relicense` branch, which was merged into `master` on May 3 and then deleted. 

The author had given a period of time to allow contributors to provide feedback on the potential change.
https://github.com/alvations/sacremoses/pull/93#issuecomment-623217299

**Pull request merged**
