### PR TITLE
nkokla/jquery.universal-smartbanner 6c38198b1119a43a937ff3523c4c3af0221a8e3c

### PR DESCRIPTION
**Pull request by AE49**
**Type:** Incomplete

**Summary:**
nkokla/jquery.universal-smartbanner 6c38198b1119a43a937ff3523c4c3af0221a8e3c

**Details:**
Declaring MIT

**Resolution:**
ClearlyDefined License file, same as GitHub repo license:
https://github.com/nkokla/jquery.universal-smartbanner/blob/6c38198b1119a43a937ff3523c4c3af0221a8e3c/LICENSE

**Affected definitions**:
- [jquery.universal-smartbanner 6c38198b1119a43a937ff3523c4c3af0221a8e3c](https://clearlydefined.io/definitions/git/github/nkokla/jquery.universal-smartbanner/6c38198b1119a43a937ff3523c4c3af0221a8e3c/6c38198b1119a43a937ff3523c4c3af0221a8e3c)

### CODE REVIEW

**Comment by capfei** [comment]
@AE49 Should we curate this as `Apache-2.0 AND MIT`? Line 2 in the license states
> 'jQuery Ultimate SmartBanner' is provided under the Apache License, 2.0.

File header:
``` javascript
/*!
 * jQuery Smart Banner
 * Copyright (c) 2014 Nicolas KOKLA
 * Forked from the Copyrighted project 'jquery.smartbanner' [Copyright (c) 2012 Arnold Daniels <arnold@jasny.net>]
 * Based on 'jQuery Smart Web App Banner' by Kurt Zenisek @ kzeni.com
 */
```

Let me know what you think.

**Comment by AE49** [comment]
@capfei  I did think about that, but I decided to curate as Apache 2.0 because it's a fork of the MIT licensed project and the forked version is what we're curating. If I understand correctly, a user can fork a project and license it under a different license. 
@ariel11 What is your opinion?

**Comment by ariel11** [comment]
@AE49 and @capfei - I agree with Apache-2.0 AND MIT.  We've had a practice of considering the original project's license on a fork as continuing forth as part of the 'declared' license field for the forked project.

**Review by capfei — APPROVED** [review]

**Comment by capfei** [comment]
Thanks, @ariel11! Update the PR to Apache-2.0 AND MIT.

**Pull request merged**
