### PR TITLE
socketcluster-sample 1.0.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
socketcluster-sample 1.0.1

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/SocketCluster/socketcluster/blob/f20bdfb7cb5714f2320a3271d97794ab92a26092/LICENSE

Description:
This is the license of the package at version 14.4.2, which is what our app's package-lock.json references.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [socketcluster-sample 1.0.1](https://clearlydefined.io/definitions/npm/npmjs/-/socketcluster-sample/1.0.1)

### CODE REVIEW

**Comment by TRQ3** [comment]
1. Package files seem to point to MIT. 
2. Meta data shows no license. 
3. Not clear which is proper source repo. 

Thoughts, @ariel11?

**Comment by ariel11** [comment]
Under "Files" in ClearlyDefined, I see “socketcluster.js” file is MIT and bootstrap files are Apache.  The MIT license has copyright Joyant, though that doesn’t appear to be who published this package.  I looked at the repo link provided on this PR and the license file has only existed since Dec 25, 2018.  This NPM was published 5 years ago.  Based on the NPM metadata and the other points above, I would conclude the ‘declared’ license for this NPM is NONE.  

Thoughts, @TRQ3?
Thoughts, @capfei ?

**Comment by TRQ3** [comment]
@ariel11 - I agree with that. NONE makes the most sense.

**Comment by ariel11** [comment]
@capfei - Do you agree with NONE on this one? Thank you!

**Comment by capfei** [comment]
@ariel11 I agree with NONE

**Comment by ariel11** [comment]
@TRQ3 - I updated the "Files changed" tab to "NONE," so this is ready to merge now.  Thanks!

**Review by TRQ3 — APPROVED** [review]

**Pull request merged**
