### PR TITLE
tsiclient 1.4.14

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
tsiclient 1.4.14

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/microsoft/tsiclient/blob/master/LICENSE

Description:
TSIClient is a Microsoft project, found on https://github.com/microsoft/tsiclient
The license URL above is the one corresponding to that project, found in the root of that repo.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [tsiclient 1.4.14](https://clearlydefined.io/definitions/npm/npmjs/-/tsiclient/1.4.14)

### CODE REVIEW

**Comment by LandOfBliss** [comment]
Looked in the “Files” section on the ClearlyDefined definition. Readme indicates MIT
NPMJS license field indicates NONE
MPNJS links to: https://github.com/microsoft/tsiclient/blob/7af6b15f9366e8ac04d3ef982ede6122ea34019e/LICENSE for source code project – license is MIT
Conclusion:  Declared license is MIT

**Review by capfei — APPROVED** [review]

**Comment by Zlatkovsky** [comment]
@LandOfBliss , @capfei : I just submitted a [new PR](https://github.com/clearlydefined/curated-data/pull/15103) for a patch version update of tsiclient (1.4.16 instead of 1.4.14). Is there something that the tsiclient project can do to ensure the ClearlyDefined automatically picks up the licensing info, to avoid needing to manually submit with each bump? E.g., if their package.json were to include `"license": "MIT"`, would that be sufficient for the tooling, or is there something else needed?

**Comment by ariel11** [comment]
@Zlatkovsky - yes, adding license info the NPM registry should enable the tooling to fill in the declared license automatically - see https://github.com/clearlydefined/service/blob/master/docs/determining-declared-license.md for more details. Thank you

**Comment by Zlatkovsky** [comment]
@ariel11 , great, thanks! I've put out a PR to the tsiclient repo to include the license info in the package.json file, hopefully they'll merge it in before the next update: https://github.com/microsoft/tsiclient/pull/340

**Pull request merged**
