### PR TITLE
OpenXmlPowerTools/4.5.3.2

### PR DESCRIPTION
**Pull request by TRQ3**
**Type:** Missing

**Summary:**
OpenXmlPowerTools/4.5.3.2

**Details:**
No info in package files. Meta data confirms MIT. 

**Resolution:**
https://github.com/OfficeDev/Open-Xml-PowerTools/blob/vNext/LICENSE

**Affected definitions**:
- [OpenXmlPowerTools 4.5.3.2](https://clearlydefined.io/definitions/nuget/nuget/-/OpenXmlPowerTools/4.5.3.2/4.5.3.2)

### CODE REVIEW

**Comment by capfei** [comment]
@TRQ3 It looks like they switched to MIT in 2019. The closest commit I could find around the publish date has the Microsoft Public License.
https://github.com/OfficeDev/Open-Xml-PowerTools/blob/28bf46725ae5ea5c441012fbb9285184d77641a1/LICENSE.txt

Do you agree this should be curated as `MS-PL`?

**Comment by TRQ3** [comment]
@capfei How did you find the MS-PL. I just retraced my steps and the source repo doesn't have any versions tagged. I only see MIT.

**Comment by capfei** [comment]
I looked in the commit history and found a commit that was close to the date since I couldn't find a tagged version.

image

**Comment by ariel11** [comment]
@capfei - I agree to MS-PL.  That was the license prior to the license change to MIT - https://github.com/OfficeDev/Open-Xml-PowerTools/commit/2f9134bd5abe0547fcf3d803b40b1401d6e58020

**Pull request merged**
