### PR TITLE
maven/mavencentral/org.eclipse.lsp4j/org.eclipse.lsp4j.jsonrpc/0.8.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Auto

**Summary:**
maven/mavencentral/org.eclipse.lsp4j/org.eclipse.lsp4j.jsonrpc/0.8.1

**Details:**
Add EPL-2.0 license

**Resolution:**
Automatically added versions based on https://github.com/clearlydefined/curated-data/pull/11858
 - 0.5.0
- 0.7.2

Matching metadata: manifest.summary.licenses: [{"license":[{"name":["Eclipse Public License, Version 2.0"],"url":["https://www.eclipse.org/legal/epl-2.0"]}]}]

**Affected definitions**:
- [org.eclipse.lsp4j.jsonrpc 0.5.0](https://clearlydefined.io/definitions/maven/mavencentral/org.eclipse.lsp4j/org.eclipse.lsp4j.jsonrpc/0.5.0)

### CODE REVIEW

**Comment by LandOfBliss** [comment]
Looked in the "Files" section on the ClearlyDefined definition.  No license file found.
Looked in Maven package license metadata indicates EPL-2.0
Source code linked to GitHub license file is EPL-2.0
Conclusion:  Declared license is EPL-2.0

**Comment by ariel11** [comment]
@LandOfBliss  - on this one, I see the .pom file just lists EPL-2.0, but then every file says the below.  So wondering if the "declared" license is more accurately "EPL-2.0 OR BSD-3-Clause."  Thoughts @capfei?

image

**Comment by capfei** [comment]
@ariel11 Yes, I agree with OR.

**Comment by capfei** [comment]
Closed by mistake! 😊

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
