### PR TITLE
TinyMCE 5.10.7

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
TinyMCE 5.10.7

**Details:**
Add GPL-2.0-only License

**Resolution:**
License Url: 
https://github.com/tinymce/tinymce/blob/release/5.10/LICENSE.TXT

Description:
This is the license file also contained in the NuGet package.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [TinyMCE 5.10.7](https://clearlydefined.io/definitions/nuget/nuget/-/TinyMCE/5.10.7)

### CODE REVIEW

**Comment by capfei** [comment]
License text is LGPL 2.1 and the file headers state:
```
/**
 * Copyright (c) Tiny Technologies, Inc. All rights reserved.
 * Licensed under the LGPL or a commercial license.
 * For LGPL see License.txt in the project root for license information.
 * For commercial licenses see https://www.tiny.cloud/
 */
/**
```

Based on this, I think this should be `LGPL-2.1-only OR OTHER`. @AE49 What do you think?

**Comment by ariel11** [comment]
@capfei - the thing is though the "license" link on the NuGet page goes to [MIT ](https://raw.githubusercontent.com/tinymce/tinymce/master/LICENSE.TXT)and it looks like the project was relicensed to MIT?  See: https://github.com/tinymce/tinymce/pull/7647.  Thoughts on this being curated as "MIT"?

**Comment by capfei** [comment]
The license for this release is still LGPL. It looks like starting MIT is going for with version 6.

**Comment by capfei** [comment]
I would also make the same assumption from their documentation. Version 6 calls out the change to MIT and version 5 does not.
V6 docs: https://www.tiny.cloud/docs/tinymce/6/changelog/#changed-4
v5 docs: https://www.tiny.cloud/docs/changelog/

**Comment by ariel11** [comment]
@capfei - OK, that makes sense.  I agree with your curation. 🚀

**Pull request merged**
