### PR TITLE
Xamarin.AndroidX.Fragment 1.3.0.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
Xamarin.AndroidX.Fragment 1.3.0.1

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://www.nuget.org/packages/Xamarin.AndroidX.Fragment/1.3.0.1/License

Description:
As specified, Xamarin.AndroidX.Fragment is licensed under the MIT License.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [Xamarin.AndroidX.Fragment 1.3.0.1](https://clearlydefined.io/definitions/nuget/nuget/-/Xamarin.AndroidX.Fragment/1.3.0.1)

### CODE REVIEW

**Review by AE49 — APPROVED** [review]

**Comment by MichaelTsengLZ** [comment]
@AE49 Do you know how to resolve conflicts?

**Comment by AE49** [comment]
@MichaelTsengLZ I don't. I'd like to know how if you want to show me? : ) 
@capfei

**Comment by MichaelTsengLZ** [comment]
1. Click the Resolve conflicts button in the PR.
image

2. From the next page, you could see where the conflict is. Version 1.3.1 already merged but this PR also wants to merge 1.3.0.1 in the same line. 
image

3. Resolve PR by first copy the declared license to 1.3.0.1 and then remove the conflict notice lines.
a. image
b. image

4. Finally, click the mark as resolve button on the top right.

**Comment by MichaelTsengLZ** [comment]
All other conflicts follow similar steps. If you are not sure whether your changes are correct or not, you could always tag me.

**Pull request merged**
