### PR TITLE
Defined new revisions for golang dep: github.com/ClickHouse/clickhouse-go

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**

### CODE REVIEW

**Comment by capfei** [comment]
@AndrienkoAleksandr This says the license is MIT: https://github.com/ClickHouse/clickhouse-go/blob/6b1ba590788873fd6993f50f823bb90274a23ba5/LICENSE

If you agree, I will update the PR.

**Comment by AndrienkoAleksandr** [comment]
> If you agree, I will update the PR.

Thanks, fixed.

**Comment by AndrienkoAleksandr** [comment]
I also fixed license info for all my another pr's...

**Comment by capfei** [comment]
Ran component through the scanners since I noticed it had not been harvested yet and it correctly declared the license. Closing PR as it is no longer needed.

**Pull request closed without merging**
