### PR TITLE
com.ibm.icu:icu4j 58.2

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
com.ibm.icu:icu4j 58.2

**Details:**
Add ICU License

**Resolution:**
License Url: 
https://home.unicode.org/basic-info/projects/#/icu/trunk/icu4j/main/shared/licenses/LICENSE

Description:
https://mvnrepository.com/artifact/com.ibm.icu/icu4j/58.2

Link to ICU license: https://home.unicode.org/basic-info/projects/#/icu/trunk/icu4j/main/shared/licenses/LICENSE

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [icu4j 58.2](https://clearlydefined.io/definitions/maven/mavencentral/com.ibm.icu/icu4j/58.2)

### CODE REVIEW

**Comment by ariel11** [comment]
@capfei - would this actually be "Unicode-TOU"?

**Comment by capfei** [comment]
@ariel11 The license file included in package looks like the https://spdx.org/licenses/Unicode-DFS-2016.html.
https://clearlydefined.io/file/2023a2d68dfcdb1f7b7c5dccb96f88aabba112f63f250cb9e533cc64625eff07

I know we had one that used this same license and I thought since it didn't have the full text, it was OTHER. I can post this one to Discord and see what they say.

**Comment by ariel11** [comment]
@capfei - I was looking at the POM - https://repo1.maven.org/maven2/com/ibm/icu/icu4j/58.2/icu4j-58.2.pom, where it says: License & terms of use: http://www.unicode.org/copyright.html#License.  That link goes to the Unicode Copyright and Terms of Use, though is not an exact match for "Unicode TOU."  The license info you found is close to "Unicode-DFS-2016" (the bottom part).  Yes, that would be great if you want to ask on Discord. 👍

**Comment by capfei** [comment]
@ariel11 Based on info provided in #7529, I would curate this as Unicode-DFS-2016.

**Review by capfei — APPROVED** [review]

**Comment by pombredanne** [comment]
IMHO you are missing out all the licenses in https://github.com/unicode-org/icu/blob/release-58-2/icu4j/main/shared/licenses/LICENSE which are much more than just https://spdx.org/licenses/Unicode-DFS-2016.html
The latest version of scancode detect this as `LicenseRef-scancode-unicode-icu-58` which is in fact a composite of many licenses:
multiple BSD-3-Clause, BSD-2-Clause, ICU, LicenseRef-scancode-naist-2003, LicenseRef-scancode-unicode, LicenseRef-scancode-public-domain.

**Pull request merged**
