### PR TITLE
Missing license for Microsoft.IdentityModel.Clients.ActiveDirectory/4.5.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
Missing license for Microsoft.IdentityModel.Clients.ActiveDirectory/4.5.1

**Details:**
Adding source, license, and attributions. 

**Resolution:**
Source:
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/tree/5e8d4df3f35e7c3df899eaf2037d15a866f3531b
MIT License:
Copyright (c) Microsoft Corporation
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/5e8d4df3f35e7c3df899eaf2037d15a866f3531b/LICENSE

**Affected definitions**:
- [Microsoft.IdentityModel.Clients.ActiveDirectory 4.5.1](https://clearlydefined.io/definitions/nuget/nuget/-/Microsoft.IdentityModel.Clients.ActiveDirectory/4.5.1)

### CODE REVIEW

**Comment by ariel11** [comment]
The curated source URL does not look right to me.  Goes to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/commit/5e8d4df3f35e7c3df899eaf2037d15a866f3531b, which looks like it is fixing a spelling issue in a changelog.txt file?  @AE49 or @royaljust if you want to look and comment?

**Comment by AE49** [comment]
@ariel11 5e8d4df and v4.5.1 both mentioned on this page - https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/ADAL-v4.5.1

License file here: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/ADAL-v4.5.1/LICENSE

**Comment by ariel11** [comment]
Thank you @AE49.  Seeing the tagged version with that commit looks right and the date matches the NuGet publication date too.  That seems good to me then.  Thanks!

**Comment by joseharriaga** [comment]
I was the one who submitted this PR via the clearlydefinedbot. This change was having issues originally but Gene was able to fix it with a few changes he added. Is this PR good to be merged? Let me know if there's anything else that needs to fixed and I'll take care of it. Thank you! @AE49

**Comment by AE49** [comment]
@joseharriaga Done.

**Comment by joseharriaga** [comment]
@AE49 Thank you!

**Pull request merged**
