### PR TITLE
geoip-api 1.3.1

### PR DESCRIPTION
**Pull request by LandOfBliss**
**Type:** Missing

**Summary:**
geoip-api 1.3.1

**Details:**
Maven license and link is LGPL-2.1-only: https://mvnrepository.com/artifact/com.maxmind.geoip/geoip-api/1.3.1
GitHub is LGPL-2.1-only: https://github.com/maxmind/geoip-api-java/blob/v1.3.1/LICENSE

**Resolution:**
LGPL-2.1-only

**Affected definitions**:
- [geoip-api 1.3.1](https://clearlydefined.io/definitions/maven/mavencentral/com.maxmind.geoip/geoip-api/1.3.1/1.3.1)

### CODE REVIEW

**Comment by ariel11** [comment]
@LandOfBliss - looks like LGPL-2.01-or-later.  Do you agree?
image

**Comment by capfei** [comment]
@ariel11 I would go with LGPL-2.1-only. The license info in the pom declares LGPL 2.1. Also, that is the license in the source repo and has been since 2009.

The LGPL 2.0 seems to come from them adding "Lesser" to the previous GPL 2.0 license info:
https://github.com/maxmind/geoip-api-java/commit/bf6df739e1db6e0a4d8e464a698a42707f7a09f6

**Comment by ariel11** [comment]
@capfei - I'm good with LGPL-2.1 as the declared license, but I'm not so sure about "only" vs. "or later."  Let's see what the group thinks. Thank you!

**Comment by ariel11** [comment]
We discussed and landed on LGPL-2.1-or-later.

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
