### PR TITLE
colt:colt 1.2.0

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
colt:colt 1.2.0

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://dst.lbl.gov/ACSSoftware/colt/license.html

Description:
Maven's website doesn't have the package, but has the Cern Logo. I found this and the 1.2.0 version matches up on the webpage. I believe this is a MIT License since the language matches that kind of license.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [colt 1.2.0](https://clearlydefined.io/definitions/maven/mavencentral/colt/colt/1.2.0)

### CODE REVIEW

**Comment by mihouc** [comment]
No obvious license information in .jar file
No license or repository information in .pom file
Older .pom file lists "The Colt Project" searches for that lead to https://dst.lbl.gov/ACSSoftware/colt/license.html, which is an old version of the MIT license

License for package should be curated as OTHER

**Comment by ariel11** [comment]
@mihouc - I am not finding an explicit link between https://dst.lbl.gov/ACSSoftware/colt/license.html, and this maven package.  Also, that license only applies to the following packages:  cern.colt* , cern.jet*, cern.clhep.  I can't tell if cern.colt is the same as the colt maven package.  I am inclined to put NONE for the maven package.

@capfei  - do you have any thoughts here?

**Comment by capfei** [comment]
@ariel11 The link provided does contain the same files, but the maven does not explicitly link to it in anyway and all of the licensing information was removed. My initial reaction would be to say NONE.

**Comment by ariel11** [comment]
@mihouc - I updated the "Files changed" to NONE, so this one is ready to merge.  Thanks!

**Review by mihouc — APPROVED** [review]

**Pull request merged**
