### PR TITLE
pyqt5-sip 4.19.18

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
pyqt5-sip 4.19.18

**Details:**
Add GPL-2.0-only License

**Resolution:**
License Url: 
https://pypi.org/project/PyQt5-sip/4.19.18/

Description:
The site says:

License
SIP is released under the GPL v2, GPL v3 licenses, and under a license similar to the BSD license.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [PyQt5-sip 4.19.18](https://clearlydefined.io/definitions/pypi/pypi/-/PyQt5-sip/4.19.18)

### CODE REVIEW

**Comment by peggymoloney** [comment]
No License in Files https://clearlydefined.io/definitions/pypi/pypi/-/PyQt5-sip/4.19.18

Landing page License is "GPL v2, GPL v3 licenses, and under a license similar to the BSD license" https://pypi.org/project/PyQt5-sip/4.19.18/

Homepage License is 
"SIP License. This is very similar to the Python Software Foundation license used for Python itself.
GNU General Public License v2
GNU General Public License v3"

Download Files license is "SIP is released under the GPL v2, GPL v3 licenses, and under a license similar
to the BSD license." at PyQt5_sip-4.19.18-cp35-cp35m-macosx_10_6_intel.whl (52.0 kB)

Source  https://www.riverbankcomputing.com/software/sip/download/. license info is GPL-2.0-only and GPL-3.0-only and OTHER

Curate as GPL-2.0-only and GPL-3.0-only and OTHER

**Comment by ariel11** [comment]
@peggymoloney  - I would interpret this to be "OR" - the package "homepage" link goes [here](https://www.riverbankcomputing.com/software/sip/), which says "SIP is available under the following licenses," meaning you have your choice of the following licenses.   I will update to "GPL-2.0-only OR GPL-3.0-ONLY OR OTHER."  Thanks!

**Review by ariel11 — APPROVED** [review]

**Comment by anairor** [comment]
Could somebody please look into this? If at all possible, I would appreciate receiving approval by tomorrow morning so I can release the code to a departing intern.

Thanks,
Oriana

**Comment by ariel11** [comment]
@anairor - I don't think this bug will be resolved in the next 24 hours.  I suggest following up with your frontline legal contact or the open source legal team directly.

**Pull request merged**
