### PR TITLE
empy 3.3.4

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
empy 3.3.4

**Details:**
Add LGPL-3.0-or-later License

**Resolution:**
License Url: 
https://web.archive.org/web/20220728054314/http://www.alcyone.com/software/empy/

Description:
The homepage for the project is no longer available apart from archive.org. However, on that page it states that the code is released under the LGPL. Similarly, the README in the source distribution states that the license is LGPL:

https://files.pythonhosted.org/packages/3b/95/88ed47cb7da88569a78b7d6fb9420298df7e99997810c844a924d96d3c08/empy-3.3.4.tar.gz

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [empy 3.3.4](https://clearlydefined.io/definitions/pypi/pypi/-/empy/3.3.4)

### CODE REVIEW

**Comment by capfei** [comment]
@AE49 I'm not finding anything other than "LGPL". Per our guidelines, do you agree with it begin LGPL-2.0-or later?

**Comment by grahamfletcher-ms** [comment]
I submitted this earlier today, and I would support LGPL-2.0-or later.

**Comment by AE49** [comment]
@capfei There is "LGPL" on this page - https://web.archive.org/web/20220728054314/http://www.alcyone.com/software/empy/ and when I click on the link it goes to a page with a redirect to LGPL-3.0 license text: https://web.archive.org/web/20220713073529/http://www.gnu.org/copyleft/lesser.html

ReadMe in ClearlyDefined files also points to LGPL-3.0 below

License

    This code is released under the "LGPL",
    http://www.gnu.org/copyleft/lesser.html.

Why wouldn't we Declare as LGPL-3.0-only?

**Comment by capfei** [comment]
@AE49 That link is not an indicator of license version. This project has stated LGPL since 2003, before LGPL 3.0 was published.
https://web.archive.org/web/20031203024132/http://www.alcyone.com/software/empy/
image


Since we do not have a declaration of which version of LGPL, just the lesser link, we don't which one is intended.

**Comment by AE49** [comment]
@capfei Thanks. Agree with LGPL-2.0-or later.

**Pull request merged**
