### PR TITLE
Missing license for Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator/1.1.0

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
Missing license for Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator/1.1.0

**Details:**
Adding source, license, and attributions. 

**Resolution:**
Source:
https://github.com/Azure/azure-functions-host/tree/d9f1af298b952204526fbc5d49c92949ba6c53a6
MIT License:
Copyright (c) .NET Foundation.  All rights reserved.
https://github.com/Azure/azure-functions-host/blob/d9f1af298b952204526fbc5d49c92949ba6c53a6/LICENSE.txt

**Affected definitions**:
- [Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator 1.1.0](https://clearlydefined.io/definitions/nuget/nuget/-/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator/1.1.0)

### CODE REVIEW

**Comment by joseharriaga** [comment]
@pombredanne Interesting. There seems to be a discrepancy between what's found on nuget.org and what's found on GitHub. I got the MIT license from the [source repository](https://github.com/Azure/azure-functions-host/tree/d9f1af298b952204526fbc5d49c92949ba6c53a6). The README found in there says:

> This project is under the benevolent umbrella of the .NET Foundation and is licensed under the MIT License

**Comment by ariel11** [comment]
@joseharriaga - yes, Microsoft sometimes releases NuGet packages under a Microsoft EULA, so I will close this PR as this NuGet package is not under an OSS license (points to https://go.microsoft.com/fwlink/?linkid=2028464). @fossygirl as FYI.

**Comment by pombredanne** [comment]
This is a mess indeed: there is also an Apache license text at the root of the repo and some Apache-licensed notice. No clarity! Would you know who to reach out to to clear this up?

**Comment by pombredanne** [comment]
@ariel11 why do you close this on the ground that this is not FOSS? It still is something that could be curated IMHO, especially since the work has been started.

**Comment by ariel11** [comment]
@pombredanne - I am following @fossygirl's orders that EULA-licensed packages should not be curated in ClearlyDefined.  The corresponding source repo under an OSS license, yes.  But to date, we have not curated non-FOSS licensed components.  We could bring up to the steering committee on whether we would curate as "OTHER"?

**Comment by pombredanne** [comment]
@ariel11  re: 

>  We could bring up to the steering committee on whether we would curate as "OTHER"?

I think having some curation is important here especially because these are not FOSS. So let's discuss it in the next curation meeting alright

**Pull request closed without merging**
