### PR TITLE
font-awesome 4.5.0

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
font-awesome 4.5.0

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://fontawesome.com/license/free

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [font-awesome 4.5.0](https://clearlydefined.io/definitions/nuget/nuget/-/font-awesome/4.5.0)

### CODE REVIEW

**Comment by mihouc** [comment]
License file in repository (https://github.com/FortAwesome/Font-Awesome/commit/24d46179c6784af24de50b3e13975b42d759111b#diff-61e0bdf7e1b43c5c93d9488b22e04170) seems to indicate multiple licenses apply to the package depending on the file type

**Comment by ariel11** [comment]
@mihouc - when I downloaded the package, the nuspec had this licenseurl: http://fontawesome.io/license/.  That goes to the Font Awesome Pro License.  I think I would curate OTHER for that.  @capfei - do you agree?

**Comment by capfei** [comment]
@mihouc and @ariel11 the file headers state OFL and MIT. 
```
/*!
 *  Font Awesome 4.5.0 by @davegandy - http://fontawesome.io - @fontawesome
 *  License - http://fontawesome.io/license (Font: SIL OFL 1.1, CSS: MIT License)
 */
```

Also, the license link in 2016 stated the same.
https://web.archive.org/web/20160304045305/http://fontawesome.io/license/

**Comment by ariel11** [comment]
@capfei - OK, when I downloaded the NuGet, I didn't see any file headers with license info.  Thank you for finding that.

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
