### PR TITLE
gmock1.11.0

### PR DESCRIPTION
**Pull request by AE49**
**Type:** Incomplete

**Summary:**
gmock1.11.0

**Details:**
Declaring BSD-3-Clause

**Resolution:**
https://www.nuget.org/packages/gmock/1.11.0/License

**Affected definitions**:
- [gmock 1.11.0](https://clearlydefined.io/definitions/nuget/nuget/-/gmock/1.11.0/1.11.0)

### CODE REVIEW

**Comment by ariel11** [comment]
@AE49 , @capfei - strange, it says Files Changed 0

**Comment by capfei** [comment]
@ariel11 @AE49 This version has already been curated. https://github.com/clearlydefined/curated-data/pull/16239

This issue has come up often. https://github.com/clearlydefined/website/issues/982

Looks like a new issue needs to be created.

**Comment by capfei** [comment]
Closing this PR since it is not needed.

**Comment by capfei** [comment]
https://github.com/clearlydefined/website/issues/1004

**Pull request closed without merging**
