### PR TITLE
MySql.Data 8.0.21

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
MySql.Data 8.0.21

**Details:**
Add GPL-2.0-only License

**Resolution:**
License Url: 
https://downloads.mysql.com/docs/licenses/connector-net-8.0-gpl-en.pdf

Description:
The PDF is linked from the Nuget. I'm very unclear on the correct license designation since the PDF appears to apply additional permissions on top of a base GPL 2.0.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [MySql.Data 8.0.21](https://clearlydefined.io/definitions/nuget/nuget/-/MySql.Data/8.0.21)

### CODE REVIEW

**Comment by AE49** [comment]
@capfei I think this should be curated as GPL v2.0 or later and OTHER (for the exception language in the License PDF found at the NuGet metadata). Thoughts?

"GPLv2 or any later version may be used, or where a choice of which version of the GPL is applied is
otherwise unspecified."

**Comment by capfei** [comment]
@AE49 It sounds like they elected GPL 2.0 only, but I could be mixing the language up.

> For the avoidance of doubt, except that if any license choice other than GPL or LGPL is available it will
apply instead, **Oracle elects to use only the General Public License version 2 (GPLv2) at this time** for
any software where a choice of GPL license versions is made available with the language indicating that
GPLv2 or any later version may be used, or where a choice of which version of the GPL is applied is
otherwise unspecified

So maybe it should be GPL-2.0-only WITH OTHER AND WITH Universal-FOSS-exception-1.0?

**Comment by capfei** [comment]
I'll add this one to the call 😄

**Comment by AE49** [comment]
@capfe What was the final outcome on this one?

**Comment by capfei** [comment]
The licenses I listed are correct, but I want to verify with the community how it is supposed to be with two WITH exceptions. I'm not sure if AND WITH is correct or not since this is the first one I've come across. 😆

**Comment by capfei** [comment]
For now, we should go with `GPL-2.0-only WITH (OTHER AND Universal-FOSS-exception-1.0)` based on https://github.com/spdx/spdx-spec/issues/479.

**Review by AE49 — APPROVED** [review]

**Pull request merged**
