### PR TITLE
google/boringssl b29b21a81b32ec273f118f589f46d56ad3332420

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
google/boringssl b29b21a81b32ec273f118f589f46d56ad3332420

**Details:**
Add OTHER License

**Resolution:**
License Url: 
https://github.com/google/boringssl/blob/b29b21a81b32ec273f118f589f46d56ad3332420/LICENSE

Description:
License should be "OpenSSL and ISC"

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [boringssl b29b21a81b32ec273f118f589f46d56ad3332420](https://clearlydefined.io/definitions/git/github/google/boringssl/b29b21a81b32ec273f118f589f46d56ad3332420)

### CODE REVIEW

**Comment by mihouc** [comment]
License file in repository (https://github.com/google/boringssl/blob/b29b21a81b32ec273f118f589f46d56ad3332420/LICENSE) states (BoringSSL is a fork of OpenSSL. As such, large parts of it fall under OpenSSL
licensing. Files that are completely new have a Google copyright and an ISC
license. This license is reproduced at the bottom of this file)

**Comment by AE49** [comment]
@mihouc @capfei I agree with the findings but not "OTHER" in the "Files changed". I would curate the Declared field as "OpenSSL and ISC". Do you agree?

https://github.com/google/boringssl/blob/b29b21a81b32ec273f118f589f46d56ad3332420/LICENSE

**Comment by capfei** [comment]
@ae49 @mihouc with today's community discussion, I'm guessing that the declared is ISC with OpenSSL under discovered. @ariel11 What do you think?

**Comment by AE49** [comment]
@capfei @ariel11 @mihouc I'm not so sure of using "WITH". I think this could be either "ISC AND OpenSSL" or just "ISC" and we treat the OpenSSL as a discovered license but given the OpenSSL portion was forked and a good portion of the code, I'm leaning towards "AND".

**Comment by capfei** [comment]
@AE49 Just to clarify, I'm not saying "WITH". Curate as "ISC" and leave OpenSSL as discovered.

**Comment by AE49** [comment]
@capfei @ariel11 @mihouc I believe from our recent discussion I would agree with Candice. Declare "ISC" for the new code. OpenSSL from the forked code as discovered license. Do we agree on this?

**Review by AE49 — APPROVED** [review]

**Pull request merged**
