### PR TITLE
mysql:mysql-connector-java 8.0.25

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
mysql:mysql-connector-java 8.0.25

**Details:**
Add GPL-2.0-only License

**Resolution:**
License Url: 
https://downloads.mysql.com/docs/licenses/connector-j-8.0-gpl-en.pdf

Description:
It was linked in legal notices for community release of MySQL Connector/J 8.0:
https://dev.mysql.com/doc/connector-j/8.0/en/preface.html

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [mysql-connector-java 8.0.25](https://clearlydefined.io/definitions/maven/mavencentral/mysql/mysql-connector-java/8.0.25)

### CODE REVIEW

**Comment by anuchandy** [comment]
Hi @LandOfBliss, I'm trying to understand the process to get `mysql-connector-java` into `clearlydefined` system. It looks like, even though this pr declares only ` GPL-2.0-only `, the system detected the following licenses as well (as per [this](https://clearlydefined.io/definitions/maven/mavencentral/mysql/mysql-connector-java/8.0.25/pr/12844))

> Apache-2.0 AND EPL-1.0 AND EPL-2.0 AND GPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-only AND MIT AND NOASSERTION

Here is the `mysql-connector-java` artifact in [maven](https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.25/).

I wonder opening a new PR with the above licenses is the resolution here? I'm new to this process, any help will be appreciated. thanks in advance!

**Comment by ariel11** [comment]
@anuchandy - you do not need to open another PR.  This project (ClearlyDefined) uses SPDX license identifiers, which is tricky for this component's license file (snippet pasted below).

@capfei  - are we in agreement per ClearlyDefined processes, that the below license will be curated as "OTHER"?  

image

**Comment by capfei** [comment]
@ariel11 Since this also includes the Universal FOSS exception, wouldn't it be OTHER WITH Universal-FOSS-exception-1.0?

**Comment by ariel11** [comment]
@royaljust - Hi, thoughts on the above boiling down to "OTHER" as there's not a valid SPDX expression we can string together that would cover the whole thing.  

Fore more details, see above - at one point we curated this as "GPL-2.0-only WITH (OTHER AND Universal-FOSS-exception-1.0)" ."  However, that failed the SPDX validator and as a project, ClearlyDefined decided to not use "WITH OTHER," as it is not SPDX compliant. 

Above, @capfei  is suggesting doing "OTHER WITH Universal-FOSS-exception-1.0."  

Thoughts on "OTHER" vs. "OTHER WITH Universal-FOSS-exception-1.0."

**Comment by capfei** [comment]
@ariel11 After discussing, I agree with OTHER.

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
