### PR TITLE
bitarray 1.2.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
bitarray 1.2.1

**Details:**
Add Python-2.0 License

**Resolution:**
License Url: 
https://spdx.org/licenses/Python-2.0

Description:
Because it is stated https://libraries.io/pypi/bitarray

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [bitarray 1.2.1](https://clearlydefined.io/definitions/pypi/pypi/-/bitarray/1.2.1)

### CODE REVIEW

**Comment by LandOfBliss** [comment]
Looked in the "Files" section on the ClearlyDefined definition.  PKG-INFO file indicates PSF
Pypi license field indicates Python Software Foundation License
Source code project includes Python Software Foundation License
Note:  This does not appear to be an exact match to Python-2.0 but I wasn’t able to find the instructions for Python.
Conclusion:  Declared license is NONE

**Comment by AE49** [comment]
@LandOfBliss Last email I could find on Python-2.0, we decided to Declare as OTHER because as you noted it's not an exact match. @ariel11 Please check me on this one. Should we declare as "OTHER"?

**Comment by capfei** [comment]
@LandOfBliss, @AE49  This appears to be PSF-2.0, which has a separate identifier from Python-2.0. PSF-2.0 is the first portion of the Python-2.0 license. Most of the differences are in the CNRI portion of Python-2.0, which is why we are using OTHER for Python-2.0, for now.

https://github.com/ilanschnell/bitarray/blob/1.2.1/LICENSE
https://spdx.org/licenses/PSF-2.0.html

Do you agree this should be PSF-2.0?

**Comment by ariel11** [comment]
@LandOfBliss , @AE49 , and @capfei  - yes, I agree the LICENSE is a match for the https://spdx.org/licenses/PSF-2.0.html.  If a project only uses the "PSF-2.0" license, that SPDX identifier is OK to use.  

Agree the problem we've run into is with the full "stacked" version of the python license, as shown in the SPDX "Python-2.0."  Projects that use the "stacked" license with BEOPEN and CNRI are often using  a version that does not meet the matching guidelines for "Python-2.0."

Agree this project matches "PSF-2.0."

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
