### PR TITLE
AspNet.ScriptManager.jQuery.UI.Combined 1.12.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
AspNet.ScriptManager.jQuery.UI.Combined 1.12.1

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://jquery.org/license/

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [AspNet.ScriptManager.jQuery.UI.Combined 1.12.1](https://clearlydefined.io/definitions/nuget/nuget/-/AspNet.ScriptManager.jQuery.UI.Combined/1.12.1)

### CODE REVIEW

**Comment by TRQ3** [comment]
Not seeing a GitHub repo for this. The jquery link does lead to a site that confirms MIT. Thoughts, @ariel11. https://jquery.org/license/

**Comment by ariel11** [comment]
@TRQ3 - I do not see anything that says this NuGet package is under the jquery license?  I would curate NONE here.  Thoughts?  

@royaljust - thoughts?

**Comment by ariel11** [comment]
@AE49 - thoughts on this one?  Thank you

**Comment by AE49** [comment]
@ariel11 @TRQ3 I would also curate as NONE. I was not able to find a license.

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
