### PR TITLE
itext7.licensekey 3.0.5

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
itext7.licensekey 3.0.5

**Details:**
Add OTHER License

**Resolution:**
License Url: 
https://itextpdf.com/en/resources/media/files/software-license-agreement-americas-region

Description:
a) The license is listed on the vendor's site. b) The service is configured to use volume licensing.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [itext7.licensekey 3.0.5](https://clearlydefined.io/definitions/nuget/nuget/-/itext7.licensekey/3.0.5)

### CODE REVIEW

**Comment by LandOfBliss** [comment]
Looked in the "Files" section on the ClearlyDefined definition.  Downloaded the nuspec and include license link that indicates AGPL-3.0-or-later
Nuget license field links to https://itextpdf.com/en/how-buy/legal with licensing options
The project site links to https://itextpdf.com/en which indicates an option to license under AGPL-3.0-or-later OR pay for a commercial license “OTHER”
Conclusion:  Declared license is AGPL-3.0-or-later OR OTHER

**Comment by ariel11** [comment]
@LandOfBliss - where do you see the "or-later" part to the AGPL-3.0?  I dug around what I think is the right repo for this NuGet and see AGPL-3.0-only - e.g. https://github.com/itext/itext7-dotnet/blob/5e5e8fd28151c1e498db9b3724e910a0d5c5a6df/itext/itext.layout/Properties/TypographyVersionAttribute.cs.  @capfei - what do you think?

**Comment by capfei** [comment]
@ariel11 I can't find this in the repo. When I look at the release info for the latest version, there isn't a link to GitHub. I couldn't find license info in the Maven package they release of this.
https://kb.itextpdf.com/home/it7kb/releases/release-licensekey-3-1-4#Release_licensekey_3.1.4

With what I found, I'm not confident to say this should be AGPL. My inclination is to go with OTHER for commercial, especially since the NuGet description states 
> The iText 7 license key library enables the use of iText 7 (and iTextSharp version 5.5.13 and newer) in non-AGPL mode, and also provides access to the iText 7 add-ons.

Maybe discuss with the group?
😕 🤷‍♀️

**Comment by ariel11** [comment]
We had a call on this one and agree the declared license would just be "OTHER" for commercial license.  Thanks

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
