### PR TITLE
fmtlib/fmt cd4af11efc9c622896a3e4cb599fa28668ca3d05

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
fmtlib/fmt cd4af11efc9c622896a3e4cb599fa28668ca3d05

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/fmtlib/fmt/blob/cd4af11efc9c622896a3e4cb599fa28668ca3d05/LICENSE.rst

Description:
The README.md file of the git repo shows the linsence is MIT:
{fmt} is distributed under the MIT license.

The link to the statement is here:
https://github.com/fmtlib/fmt/tree/cd4af11efc9c622896a3e4cb599fa28668ca3d05#license

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [fmt cd4af11efc9c622896a3e4cb599fa28668ca3d05](https://clearlydefined.io/definitions/git/github/fmtlib/fmt/cd4af11efc9c622896a3e4cb599fa28668ca3d05)

### CODE REVIEW

**Comment by AE49** [comment]
@capfei How would you handle this exception language in this MIT license?

https://github.com/fmtlib/fmt/blob/cd4af11efc9c622896a3e4cb599fa28668ca3d05/LICENSE.rst

**Comment by capfei** [comment]
@AE49 Not sure. I have a pending PR for this source, as well, and I did not get a consensus if it should be WITH or OR. I posted it to Discord so, hopefully, I'll get an answer soon.

**Comment by yelu** [comment]
> @AE49 Not sure. I have a pending PR for this source, as well, and I did not get a consensus if it should be WITH or OR. I posted it to Discord so, hopefully, I'll get an answer soon.

The statement should be fine. Starting from 6.0.0, here it says,
[Switched to the MIT license with an optional exception that allows distributing binary code without attribution.](https://github.com/fmtlib/fmt/releases/tag/6.0.0)

@AE49 @capfei

**Comment by yelu** [comment]
What else I could do to have this approved? :) @AE49

**Comment by capfei** [comment]
@ae49 I decided to update #6929 with `WITH OTHER` so I recommend the same for this PR.

**Review by AE49 — APPROVED** [review]

**Pull request merged**
