### PR TITLE
javax.jms:jms 1.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
javax.jms:jms 1.1

**Details:**
Add NONE License

**Resolution:**
License Url: 
https://mvnrepository.com/artifact/javax.jms/jms/1.1

Description:
Java Message Service » 1.1
The Java Message Service (JMS) API is a messaging standard that allows application components based on the Java 2 Platform, Enterprise Edition (J2EE) to create, send, receive, and read messages. It enables distributed communication that is loosely coupled, reliable, and asynchronous.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [jms 1.1](https://clearlydefined.io/definitions/maven/mavencentral/javax.jms/jms/1.1)

### CODE REVIEW

**Comment by LandOfBliss** [comment]
Looked in the “Files” section on the ClearlyDefined definition.  No files.
Maven license field indicates Apache-2.0
Source code project license is Apache-2.0:  https://github.com/ops4j/org.ops4j.pax.jms/blob/jms-1.1.0/LICENSE
Conclusion:  Declared license is Apache-2.0

**Comment by ariel11** [comment]
@LandOfBliss - that does not look like the right repo.  If you start at the maven location - https://repo1.maven.org/maven2/javax/jms/jms/1.1/, I only see a .pom and a couple xml files - no .jar or -sources.jar.  There is no license info on the .pom.  The .pom points to http://java.sun.com/products/jms/docs.html, which points to a spec here: https://jcp.org/en/jsr/detail?id=343.  That last link has license info on it, however, I am inclined to say the license info for this maven "package" is NONE.

Thoughts @LandOfBliss  and @capfei ?

**Comment by capfei** [comment]
@ariel11 I went on a link clicking ride and ended up at, what I believe to be, the source repo. 😆 

I'll provide my path and let you decide if we should go with it or not.

- From the pom: http://java.sun.com/products/jms/docs.html
- Clicked on "Get the Specification": https://jcp.org/en/jsr/detail?id=343
- Scrolled down a little and clicked on "Issue Tracker" under "Expert Group Transparency": http://java.net/jira/browse/JMS_SPEC
- I clicked on "For Java EE-related projects: https://javaee.github.io" since the Maven package states it is for Java 2 Enterprise Edition.
- Took me to the JavaEE GitHub org so I searched for "jms" and the repo for javax.jms is listed: https://github.com/javaee?q=jms&type=&language=&sort= (for some reason, I had to select "All" as the type)
- https://github.com/javaee/javax.jms
- Headers from when it was first imported list CDDL 1.1 or GPL 2.0 with Classpath: https://github.com/javaee/javax.jms/blob/704f4c700aca8db94d097db995a614785d065e25/src/main/java/javax/jms/BytesMessage.java

What do you think? 😪

**Comment by ariel11** [comment]
@capfei - good sleuthing. 😎  Hmm...it looks like the repo you found dates back to Nov 12, 2007.  The maven we are curating dates to 2006-11-06.  So, I think I'd still say that the _package_ license is "NONE."  Thoughts?

**Comment by capfei** [comment]
@ariel11 After thinking it over, I'm going with NONE. I don't know of a way to verify if those file headers existed in those files when the package was published. Probably, but, can't confirm.

**Review by capfei — APPROVED** [review]

**Pull request merged**
