### PR TITLE
deep-freeze 0.0.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
deep-freeze 0.0.1

**Details:**
Add CC0-1.0 License

**Resolution:**
License Url: 
https://github.com/substack/deep-freeze/blob/master/LICENSE

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [deep-freeze 0.0.1](https://clearlydefined.io/definitions/npm/npmjs/-/deep-freeze/0.0.1)

### CODE REVIEW

**Comment by ariel11** [comment]
@royaljust or @capfei - do you know how I could tell what date this sample code was published to this page? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze.  Per the [license terms ](https://developer.mozilla.org/en-US/docs/MDN/About#Copyrights_and_licenses)for this page, it is public domain if posted on or after August 20, 2010, or MIT if before.

**Comment by royaljust** [comment]
@ariel11 - take a look in the wayback machine! https://web.archive.org/web/*/https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze

**Comment by ariel11** [comment]
> @ariel11 - take a look in the wayback machine! https://web.archive.org/web/*/https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze

Hmm...it shows the first time the page was saved was in 2013.  Does that mean it did not exist prior to then?

**Comment by capfei** [comment]
@ariel11 At the bottom of the page, there is 
> Last modified: Sep 9, 2020, by MDN contributors

If you click on "by MDN contributors", it'll take you to the edit history of that page.

**Comment by capfei** [comment]
The license also states Public Domain.
https://clearlydefined.io/file/1c19eb8496c30f037a2f4eccf69e9a2b1512e30444446b6a64a1aacb47f91e3b

**Comment by ariel11** [comment]
> The license also states Public Domain.
> https://clearlydefined.io/file/1c19eb8496c30f037a2f4eccf69e9a2b1512e30444446b6a64a1aacb47f91e3b

Thanks @capfei.  Yes, but it also says "it is based on" that page, so I was looking into the licensing of that page.  Going to "by MDN contributors," it looks like the page was born on [Oct 4, 2010](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze$revision/16018) .  Since that is after August 20, 2010, looks like the code on that page is public domain and this package is public domain, so I'll do "OTHER."

**Comment by ariel11** [comment]
Note - waiting for curator consensus on whether to include the "based on" license info in the "declared" field.

**Comment by ariel11** [comment]
Curation community decide "based on" would *not* be included in the "declared" field.  So, declared here is just OTHER for public domain.  Thanks

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
