### PR TITLE
Xam.Plugin.DeviceInfo 4.0.0.13

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
Xam.Plugin.DeviceInfo 4.0.0.13

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/jamesmontemagno/DeviceInfoPlugin/blob/master/LICENSE

Description:
Found on their github

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [Xam.Plugin.DeviceInfo 4.0.0.13](https://clearlydefined.io/definitions/nuget/nuget/-/Xam.Plugin.DeviceInfo/4.0.0.13)

### CODE REVIEW

**Comment by mihouc** [comment]
License link on Nuget site (https://github.com/jamesmontemagno/DeviceInfoPlugin/blob/master/LICENSE) indicates license is MIT

**Comment by AE49** [comment]
@mihouc @capfei This project was derived from another GitHub project - https://github.com/jamesmontemagno/DeviceInfoPlugin/blob/v4.0.0.13/LICENSE. I would Declare both "MIT and Apache-2.0". Thoughts?

**Comment by AE49** [comment]
@mihouc @capfei After our discussion on code derived from, this should be Declared as MIT. Agree?

**Comment by capfei** [comment]
@AE49 I agree with curating it as MIT based on our recent discussion.

**Comment by mihouc** [comment]
@AE49 Agreed

**Review by AE49 — APPROVED** [review]

**Pull request merged**
