### PR TITLE
client 0.0.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
client 0.0.1

**Details:**
Add NONE License

**Resolution:**
License Url: 

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [client 0.0.1](https://clearlydefined.io/definitions/npm/npmjs/-/client/0.0.1)

### CODE REVIEW

**Comment by LandOfBliss** [comment]
Looked in the "Files" section on the ClearlyDefined definition.  License is MIT
NPM license field indicates BSD
Source code project license is MIT
Conclusion:  Declared license is MIT

**Comment by capfei** [comment]
Since this one has conflicting license information, I opened an issue to see if the author can provide clarification. https://github.com/ContinuumBridge/client-js/issues/2

We'll put this one on hold for a little bit and see if we get a response.

**Comment by ariel11** [comment]
@capfei and @LandOfBliss  - if we haven't heard back, I think per the curation guidelines, we'd prioritize the LICENSE file in the package in the event of a conflict, so we'd curate MIT here.  https://github.com/clearlydefined/clearlydefined/blob/master/docs/curation-guidelines.md#canonical-locations-for-the-declared-license-for-package-definitions

**Comment by capfei** [comment]
No response on my issue, yet, so I will update this to MIT. We can change it later, if needed.

**Review by capfei — APPROVED** [review]

**Pull request merged**
