### PR TITLE
testing

### PR DESCRIPTION
**Pull request by nellshamrell**
**Type:** Other

**Summary:**
testing

**Details:**
test

**Resolution:**
test

**Affected definitions**:
- [pyzmq 22.0.2](https://clearlydefined.io/definitions/pypi/pypi/-/pyzmq/22.0.2/22.0.2)

### CODE REVIEW

**Comment by capfei** [comment]
@nellshamrell Since this is a test, can this be closed?

**Comment by ariel11** [comment]
@capfei - maybe we should clean up the declared field on this one..  Would you agree with "BSD-3-Clause" as the "declared" license here?

**Comment by capfei** [comment]
@ariel11 I'm leaning to BSD-3-Clause AND LGPL-3.0-or-later since it seems they updated most files to BSD-3-Clause and kept some legacy files as LGPL. Stated here:

https://github.com/zeromq/pyzmq/tree/master/RELICENSE
https://github.com/zeromq/pyzmq/blob/master/docs/source/changelog.rst#220

zmq/core is now under zmq/backend/cython

Even the setup.py states BSD and LGPL. 🤷‍♀️ Those are my two cents, wishy-washy as they may be.

**Comment by ariel11** [comment]
Closing this PR (another PR was opened for this package) - https://github.com/clearlydefined/curated-data/pull/10074

**Comment by nellshamrell** [comment]
Sorry, forgot to close this after testing. Thanks @ariel11!

**Pull request closed without merging**
