### PR TITLE
There is no declared license

### PR DESCRIPTION
**Pull request by cruzerika**
**Type:** Incomplete

**Summary:**
There is no declared license

**Details:**
License is BSD-3 clause per COPYING file on github: https://github.com/live-clones/hdf5/blob/f3f29dc7df5f3cc41a5e9462d8c415e540cda3d6/COPYING_LBNL_HDF5 and on the original repository: https://bitbucket.hdfgroup.org/projects/HDFFV/repos/hdf5/browse/COPYING_LBNL_HDF5

**Resolution:**
Populated declared license with "BSD-3-Clause"

**Affected definitions**:
- [hdf5 f3f29dc7df5f3cc41a5e9462d8c415e540cda3d6](https://clearlydefined.io/definitions/git/github/live-clones/hdf5/f3f29dc7df5f3cc41a5e9462d8c415e540cda3d6/f3f29dc7df5f3cc41a5e9462d8c415e540cda3d6)

### CODE REVIEW

**Comment by cruzerika** [comment]
Hi @pombredanne, I've updated the declared license to BSD-3-Clause-LBNL and as well as both of the license of the COPYING files.

**Comment by pombredanne** [comment]
@cruzerika re:

>I've updated the declared license to BSD-3-Clause-LBNL and as well as both of the license of the COPYING files.

thank you ++... is there a new PR then?

**Comment by cruzerika** [comment]
Hi @pombredanne,

Yes, there is. the link to the new PR #2188 is: https://github.com/clearlydefined/curated-data/pull/2188#issuecomment-509355446

Thanks,
Erika

**Comment by pombredanne** [comment]
Closed in favor of https://github.com/clearlydefined/curated-data/pull/2070

**Pull request closed without merging**
