### PR TITLE
Missing Declared license

### PR DESCRIPTION
**Pull request by ariel11**
**Type:** Missing

**Summary:**
Missing Declared license

**Details:**
Repo readme only says "BSD License."  Some files are BSD-2 clause and some are BSD 3-clause.  There is at least one MIT file.  

**Resolution:**
Since the readme says "BSD license," curating the declared license as BSD 2 and 3 clause.

**Affected definitions**:
- [zip.js 563fe1da2579e55ae0ab1fed38a3b37a234e239e](https://clearlydefined.io/definitions/git/github/gildas-lormeau/zip.js/563fe1da2579e55ae0ab1fed38a3b37a234e239e/563fe1da2579e55ae0ab1fed38a3b37a234e239e)

### CODE REVIEW

**Comment by AE49** [comment]
@pombredanne I think @ariel11 is right to curate both BSD-2-Clause and BSD-3-Clause. Thoughts?

**Comment by ariel11** [comment]
@AE49 - Per the call today, I think the outcome is just BSD-3-clause for the declared.  Agree?

**Comment by AE49** [comment]
@ariel11 Yes, thanks for raising it. Made edit to Declared License: BSD-3-Clause

**Comment by pombredanne** [comment]
I agree with a `BSD-3-Clause` here as a declared license ...   The `MIT` and `BSD-2-Clause` code is under tests and is not core code.   
The README statement that `zip.js is an open-source library (BSD license) for zipping and unzipping files.` should therefore be interpreted to mean `BSD-3-Clause` as a main declared license.

Note that there is a request for clarification that made by https://github.com/gildas-lormeau/zip.js/issues/162 and that @gildas-lormeau clarified the licensing in https://github.com/gildas-lormeau/zip.js/issues/10#issuecomment-6495828

So I think we are good with the `BSD-3-Clause` license as a curated data for the declaration.

**Pull request merged**
