### PR TITLE
Alachisoft.NCache.OpenSource.SDK 5.0.2

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
Alachisoft.NCache.OpenSource.SDK 5.0.2

**Details:**
Add Apache-2.0 License

**Resolution:**
License Url: 
https://github.com/Alachisoft/NCache/blob/master/LICENSE

Description:
Per https://www.alachisoft.com/ncache/ncache-open-source.html 

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [Alachisoft.NCache.OpenSource.SDK 5.0.2](https://clearlydefined.io/definitions/nuget/nuget/-/Alachisoft.NCache.OpenSource.SDK/5.0.2)

### CODE REVIEW

**Comment by mihouc** [comment]
Downloaded license file on Clearly Defined indicates license is OTHER
License link on Nuget site also indicates license is OTHER
Project site indicates license is Apache-2.0 for Open Source
Repository listed on project site indicates license is Apache-2.0

License for package should be curated as Apache-2.0

**Comment by AE49** [comment]
@mihouc I would Declare both licenses you found - the proprietary license and the OSS license for source as "OTHER OR Apache-2.0". @ariel11 Thoughts?

**Comment by ariel11** [comment]
@AE49 and @mihouc - I think it is just OTHER.  This particular package/binary license link is the Software Evaluation Agreement.  If they separately offer the source code under Apache, that doesn't change that this NuGet package is under the Software Evaluation Agreement.

**Comment by mihouc** [comment]
@AE49 @ariel11 The company differentiates the Open Source product from the other versions. On this page, https://www.alachisoft.com/download-ncache.html , they state "Note: NCache Open Source is released under the Apache License, Version 2.0"

**Comment by ariel11** [comment]
@AE49 and @mihouc - In this case, I would prioritize the license link for the NuGet page, which is this: https://www.alachisoft.com/pricing/license-agreements.html.   They may license something else from their site under Apache. 

We can ask @royaljust or @capfei  for another opinion.

**Comment by AE49** [comment]
@mihouc I agree with Ariel's point and I updated the yaml, if you agree to approve and merge.

**Review by mihouc — APPROVED** [review]

**Pull request merged**
