### PR TITLE
org.glassfish.hk2:osgi-resource-locator 1.0.3

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
org.glassfish.hk2:osgi-resource-locator 1.0.3

**Details:**
Add EPL-2.0 License

**Resolution:**
License Url: 
http://www.eclipse.org/legal/epl-2.0

Description:
Their public maven repository links to this license:
https://mvnrepository.com/artifact/org.glassfish.hk2/osgi-resource-locator/1.0.3

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [osgi-resource-locator 1.0.3](https://clearlydefined.io/definitions/maven/mavencentral/org.glassfish.hk2/osgi-resource-locator/1.0.3)

### CODE REVIEW

**Comment by TRQ3** [comment]
1. Package files seem to point to EPL v 2, however it also includes language around the secondary license contained within the EPL v2.0 license. The language even includes SPDX identifier: "SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0". But, I am not sure we use the internal, secondary license contained within the EPL in the SPDX curation.  https://clearlydefined.io/file/8b6622eb81e557299fbd9aa854bc5ac76d307f7ae5e770586489a58bb5338b2a
2. Pom file shows same from above. https://repo1.maven.org/maven2/org/glassfish/hk2/osgi-resource-locator/1.0.3/osgi-resource-locator-1.0.3.pom
3. Sources jar seems to point to the same from above. https://repo1.maven.org/maven2/org/glassfish/hk2/osgi-resource-locator/1.0.3/

@ariel11 and @AE49, thoughts on this one? I'm leaning toward curating as EPL 2.0, because the secondary license language is already contained in the EPL itself.

**Comment by capfei** [comment]
@TRQ3 Per the "Notes" on the SPDX license page, it should be OR.
https://spdx.org/licenses/EPL-2.0.html
> Secondary Licenses declared via Exhibit A should be represented using the disjunctive OR operator (See: SPDX spec, section on SPDX License Expressions and https://www.eclipse.org/legal/epl-2.0/faq.php for more info).

This should be curated as EPL-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0. Let me know if you agree.

**Comment by TRQ3** [comment]
@capfei That makes sense to me. Thank you! I agree.

**Comment by capfei** [comment]
@TRQ3 Updated!

**Review by TRQ3 — APPROVED** [review]

**Pull request merged**
