### PR TITLE
WiX.Toolset.UnofficialFork 3.11.2

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
WiX.Toolset.UnofficialFork 3.11.2

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://raw.githubusercontent.com/jozefizso/WiX.Toolset.NuGet/v3.11.2/LICENSE

Description:
Its the license linked in the package official nuget page:
https://www.nuget.org/packages/WiX.Toolset.UnofficialFork/3.11.2

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [WiX.Toolset.UnofficialFork 3.11.2](https://clearlydefined.io/definitions/nuget/nuget/-/WiX.Toolset.UnofficialFork/3.11.2)

### CODE REVIEW

**Comment by ariel11** [comment]
@TRQ3 and @capfei - I think I would do "MS-RL AND MIT" or just "MS-RL" and "MIT would be "discovered."

See https://github.com/jozefizso/WiX.Toolset.NuGet/tree/v3.11.2#license

Thoughts?

**Comment by TRQ3** [comment]
I am leaning toward MS-RL as the declared and MIT as the discovered, given the language "Code for creating the NuGet package is licensed under MIT License."

Thoughts, @capfei?

**Comment by capfei** [comment]
@ariel11 @TRQ3 Wouldn't this be like the Boost NuGet package, where it is a repackage of other code but the NuGet package itself is a different license. If I treat this similarly, MIT is the declared license and MS-RL is discovered.

**Comment by ariel11** [comment]
@capfei and @TRQ3 - I might have been confusing myself thinking of the _declared_ license as the "main" license and _discovered_ being for smaller parts of the project.  Maybe it is more accurate that the MIT is the overall _package_ license, even though the package consists mostly of the MS-RL project? 

@royaljust? :)

**Comment by royaljust** [comment]
I read this license file to say that the tool chain to build WiX into a nuget package is MIT, but that the package itself (the result of running the MS-RL code through the MIT tooling) is under MS-RL. Thoughts on this read? Can we ask the author?

**Comment by ariel11** [comment]
@royaljust - OK, I opened an issue at the author's repo for clarification.

**Comment by ariel11** [comment]
Author confirmed the package and its contents are MS-RL

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
