### PR TITLE
Declared MIT License

### PR DESCRIPTION
**Pull request by peggymoloney**
**Type:** Missing

**Summary:**
Declared MIT License

**Details:**
Found a commit on this day of this version 3/1/2016 at (https://github.com/Azure/autorest/blob/9a379025c6b07728a6b30ab72d903c01e916533f/LICENSE)

**Resolution:**
Declared MIT License

**Affected definitions**:
- [Microsoft.Rest.ClientRuntime 2.1.0](https://clearlydefined.io/definitions/nuget/nuget/-/Microsoft.Rest.ClientRuntime/2.1.0/2.1.0)

### CODE REVIEW

**Comment by AE49** [comment]
@geneh Hi, can you resolve this conflict? Thanks.

**Comment by AE49** [comment]
@iamwillbar Hi, this is still not letting me merge. Is there another step I need to do?

**Comment by pombredanne** [comment]
For reference, the license is MIT because at the time it pointed to licenseUrl>https://raw.githubusercontent.com/Microsoft/dotnet/master/LICENSE which was MIT at the time of that release per https://github.com/microsoft/dotnet/blob/8898eccec47df7ccfd818af8be9f4b85295358fa/LICENSE

**Comment by pombredanne** [comment]
@AE49 I resolved the conflict and merged.

**Pull request merged**
