### PR TITLE
Missing Declared License

### PR DESCRIPTION
**Pull request by ariel11**
**Type:** Incomplete

**Summary:**
Missing Declared License

**Details:**
Followed to repo via Project site link - https://github.com/xunit/xunit/blob/2.4/license.txt

**Resolution:**
Apache v2

**Affected definitions**:
- [xunit 2.4.0](https://clearlydefined.io/definitions/nuget/nuget/-/xunit/2.4.0/2.4.0)

### CODE REVIEW

**Comment by AE49** [comment]
@jeffwilcox @ignacionr I'm still not able to merge this.

**Comment by ignacionr** [comment]
The problem here are the two 'sourceLocation' objects that lack a 'name'.

**Comment by ignacionr** [comment]
@AE49 I resolved it manually, you can now merge.

**Comment by AE49** [comment]
@ignacionr Thank you.

**Pull request merged**
