### PR TITLE
mod_spatialite 4.3.0.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
mod_spatialite 4.3.0.1

**Details:**
Add MPL-2.0 License

**Resolution:**
License Url: 
https://www.gaia-gis.it/fossil/libspatialite/file?name=COPYING

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [mod_spatialite 4.3.0.1](https://clearlydefined.io/definitions/nuget/nuget/-/mod_spatialite/4.3.0.1)

### CODE REVIEW

**Review by capfei — APPROVED** [review]

**Comment by capfei** [comment]
Package metadata points to https://www.gaia-gis.it/fossil/libspatialite/index, which states tri-license of MPL 1.1, GPL 2.0 or later, or LGPL 2.1 or later. Updated.

**Comment by capfei** [comment]
@fossygirl @jeffwilcox Can one of you merge this one? Validation bot doesn't like multiple ORs and I don't have permissions to force merge it.

**Comment by fossygirl** [comment]
This is currently failing a curation check. Is this one that normally Nell would have force merged?

Thanks,
Carol
________________________________

**Comment by capfei** [comment]
@fossygirl Yes, Nell had to force merge these. Multiple ORs has been one of the ongoing issues with the validation bot.
https://github.com/clearlydefined/curated-data/issues/11048

**Comment by MichaelTsengLZ** [comment]
@capfei  Merged.

**Pull request merged**
