### PR TITLE
sparqlwrapper 2.0.0

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
sparqlwrapper 2.0.0

**Details:**
Add W3C-20150513 License

**Resolution:**
License Url: 
https://github.com/RDFLib/sparqlwrapper/blob/master/LICENSE.txt

Description:
License mentioned in Python package release. https://pypi.org/project/SPARQLWrapper/2.0.0/

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [sparqlwrapper 2.0.0](https://clearlydefined.io/definitions/pypi/pypi/-/sparqlwrapper/2.0.0)

### CODE REVIEW

**Comment by capfei** [comment]
@ariel11 The license is an almost match to W3C but it is missing the section titles: "License" and "Disclaimers". The "Notes" section is optional.
https://spdx.org/licenses/W3C.html

https://github.com/RDFLib/sparqlwrapper/blob/2.0.0/LICENSE.txt

Are these significant enough to change this to OTHER?

**Comment by tellarin** [comment]
Not sure of the rules here, but the license has not changed from previous versions and it is the same as v1.8.2, which is listed in ClearlyDefined as W3C: https://clearlydefined.io/definitions/pypi/pypi/-/sparqlwrapper/1.8.2

**Comment by tellarin** [comment]
@ariel11 @capfei Any updates on this? This is blocking us in a release. Thanks.

**Comment by ariel11** [comment]
@capfei - Well, the SPDX matching guidelines do not specifically address section headers, but it does license titles and bullets/numbering, so I think it is reasonable to use the SPDX identifier here.  Thanks!

**Review by capfei — APPROVED** [review]

**Comment by tellarin** [comment]
Thanks!

**Pull request merged**
