### PR TITLE
Update unicorn.yaml

### PR DESCRIPTION
**Pull request by capfei**

### CODE REVIEW

**Comment by capfei** [comment]
@nellshamrell ClearlyDefined bot is failing validation with `OR OTHER` being added. I tried originally in #7880 and thought it was just an issue with that PR. Can you take a look?

**Comment by ariel11** [comment]
@nellshamrell and @capfei  - also having this issue on https://github.com/clearlydefined/curated-data/pull/10046 and https://github.com/clearlydefined/curated-data/pull/10047 - where "OTHER" appears to be causing an error.

**Comment by nellshamrell** [comment]
Interesting. Will take a look!

**Comment by nellshamrell** [comment]
This was a systematic bug that we have now fixed. I'm trying closing and then re-opening the pull request to see whether it works now.

**Comment by nellshamrell** [comment]
Well, that didn't work. Trying to get the automated check to run again.

**Comment by nellshamrell** [comment]
I wasn't able to get the automated check to run again, but I opened a new PR with the changes #10194. Closing this one.

**Pull request closed without merging**
