### PR TITLE
Add license declaration to ms-tpm-20-ref

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
Add license declaration to ms-tpm-20-ref

**Details:**
ms-tpm-20-ref does not explicitly declare a license, however the reference implementation is licensed with BSD-2-Clause.

**Resolution:**
Declared the license as BSD-2-Clause.

**Affected definitions**:
- [ms-tpm-20-ref 6cb570e90317c7927a0c6da86a27777376a9a433](https://clearlydefined.io/definitions/git/github/microsoft/ms-tpm-20-ref/6cb570e90317c7927a0c6da86a27777376a9a433)

### CODE REVIEW

**Comment by pombredanne** [comment]
Basically to me the BSD starts with a permission of `Redistribution and use... ` and the extra terms on top (if there are some patent involved... I have no idea) could be read as `no use allowed if there is a patent`...
In anycase this is NOT a clear cut BSD and would need to be flagged somehow

**Comment by ariel11** [comment]
@pombredanne - I would be inclined to curate the "declared" license field for this as "OTHER." Another question is I see the "LICENSE" file in ClearlyDefined says "BSD-2 clause." Wondering if we would update that to "OTHER," as well.  There are a number of 'discovered' licenses listed, which captures BSD-2 clause and others..  Let's see if @royaljust has some thoughts here.

**Comment by dmcilvaney** [comment]
Sorry for the confusion, I'll see if I can find someone more familiar with the licencing for the repo. If I recall correctly there was some back and forth with various entities when picking a license for the codebase. I'd like to make sure we end up with the correct information.

**Comment by amarochk** [comment]
TPM 2.0 reference implementation is published under a plain BSD license. The form of the license disclaimer was approved (and probably suggested) by Microsoft LCA. It is certainly not BSD-2 or "other".

**Comment by ariel11** [comment]
@dmcilvaney - it seems clear to me that the "License" for this commit is https://github.com/microsoft/ms-tpm-20-ref/blob/6cb570e90317c7927a0c6da86a27777376a9a433/LICENSE (where the license is the BSD-2 clause).  We are just discussing what to tag the license as in ClearlyDefined given the extra text added to the BSD license, which then makes it 'non-standard' (the whole thing no longer matches the SPDX license text for "BSD-2 clause").  So, we are discussing whether we would tag the license as "OTHER" in ClearlyDefined.

**Comment by amarochk** [comment]
Oh, well. If you have any doubts, mark it as "OTHER", IANAL after all...

**Pull request merged**
