### PR TITLE
fmtlib/fmt 6cccdc24bcb8605965c1e2497c61504cd388bde9

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
fmtlib/fmt 6cccdc24bcb8605965c1e2497c61504cd388bde9

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/fmtlib/fmt/blob/16aec06179a2c2661be77fd9ba3b202955de0c0b/LICENSE.rst

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [fmt 6cccdc24bcb8605965c1e2497c61504cd388bde9](https://clearlydefined.io/definitions/git/github/fmtlib/fmt/6cccdc24bcb8605965c1e2497c61504cd388bde9)

### CODE REVIEW

**Comment by mihouc** [comment]
Readme file (https://github.com/fmtlib/fmt/blob/6cccdc24bcb8605965c1e2497c61504cd388bde9/README.rst) indicates license is MIT.
License file is labeled as draft (https://github.com/fmtlib/fmt/blob/6cccdc24bcb8605965c1e2497c61504cd388bde9/LICENSE.rst). but also indicates license is MIT.

License should be curated as MIT

**Comment by ariel11** [comment]
@mihouc - The LICENSE file has some extra text - see “Optional exception to the license.”  Thoughts on curating this as “MIT WITH OTHER"?  We can also get a second opinion from @capfei .

**Comment by capfei** [comment]
@ariel11 @mihouc Yes, I would go with MIT WITH OTHER.

**Comment by mihouc** [comment]
@capfei @ariel11 Does the fact that the license file is labeled as draft make it less definitive than the readme file?

**Comment by ariel11** [comment]
> @capfei @ariel11 Does the fact that the license file is labeled as draft make it less definitive than the readme file?

@mihouc - I think they might mean "draft" as in "write."  Either way, it is still the license file. Thanks for asking.  I updated the "Files changed" to "MIT WITH OTHER," so it is ready to merge now.  Thank you

**Review by mihouc — APPROVED** [review]

**Pull request merged**
