### PR TITLE
Source code Location was missing

### PR DESCRIPTION
**Pull request by yashkohli88**
**Type:** Missing

**Summary:**
Source code Location was missing

**Details:**
Source code Location from this component was missing due to a missing tag in the corresponding GitHub repository.

**Resolution:**
Correct commit was identified and updated. You can refer to package.json file to verify the version for this commit. Here is the link to that - https://github.com/peterolson/BigInteger.js/blob/ae15d64d76a94a3fcc506df920e573d23066fd9e/package.json

**Affected definitions**:
- [big-integer 1.6.25](https://clearlydefined.io/definitions/npm/npmjs/-/big-integer/1.6.25/1.6.25)

### CODE REVIEW

**Comment by capfei** [comment]
Looking at the time the package was published, 9/7/2017 1:45:28 AM UTC, the commit ID should be https://github.com/peterolson/BigInteger.js/commit/a0c10d68aae8f5df56a67b3e3eb353b428abf170. The commit provided above occurred almost 3 hours later.

@yashkohli88 Do you agree with changing the commit ID?

**Comment by yashkohli88** [comment]
@capfei I chose the last commit of that day since it had all the checks passed and earlier commits have some failed checks each. I have attached the screenshot for the same. 
image

**Comment by capfei** [comment]
@AE49 or @ariel11 Do either of you have an opinion on what the source commit should be?

**Comment by ariel11** [comment]
@capfei - I think it makes more sense to me that we would go by date/time stamps.  We are trying to match the actual commit used to make a package, not whether checks passed or not.

**Review by capfei — APPROVED** [review]

**Comment by capfei** [comment]
Updated.

**Pull request merged**
