### PR TITLE
org.glassfish:javax.json 1.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
org.glassfish:javax.json 1.1

**Details:**
Add CDDL-1.0 License

**Resolution:**
License Url: 
https://oss.oracle.com/licenses/CDDL+GPL-1.1

Description:
Their maven repository links to this license
https://mvnrepository.com/artifact/org.glassfish/javax.json/1.1

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [javax.json 1.1](https://clearlydefined.io/definitions/maven/mavencentral/org.glassfish/javax.json/1.1)

### CODE REVIEW

**Comment by TRQ3** [comment]
1. Package files point to CDDL 1.0 OR GPL v2 with classpath exception. https://oss.oracle.com/licenses/CDDL+GPL-1.1
2. Pom file points to CDDL 1.0 OR GPL v2 with classpath exception. https://repo1.maven.org/maven2/org/glassfish/javax.json/1.0.1/javax.json-1.0.1.pom
3. Sources jar links to same CDDL 1.0 OR GPL v2 with classpath exception. https://repo1.maven.org/maven2/org/glassfish/javax.json/1.0.1/

Should curate as CDDL 1.0 OR GPL v2 with classpath exception.

**Comment by capfei** [comment]
@TRQ3 This is CDDL-1.1, not CDDL-1.0. The license info in the pom points to https://oss.oracle.com/licenses/CDDL+GPL-1.1, which states CDDL-1.1.

> The contents of this file are subject to the terms of either the GNU
  General Public License Version 2 only ("GPL") or the Common Development
  and Distribution License("CDDL") (collectively, the "License").  You
  may not use this file except in compliance with the License.  You can
  obtain a copy of the License at **https://oss.oracle.com/licenses/CDDL+GPL-1.1**
  or LICENSE.txt.  See the License for the specific language governing 
  permissions and limitations under the License.

This should be curated as CDDL-1.1 OR GPL-2.0-only WITH Classpath-exception-2.0. Let me know if you agree.

**Comment by TRQ3** [comment]
@capfei Absolutely. Thank you! I agree.

**Comment by capfei** [comment]
@TRQ3 Updated!

**Review by TRQ3 — APPROVED** [review]

**Pull request merged**
