### PR TITLE
org.glassfish.hk2.external:jakarta.inject 2.6.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
org.glassfish.hk2.external:jakarta.inject 2.6.1

**Details:**
Add EPL-2.0 License

**Resolution:**
License Url: 
https://www.eclipse.org/legal/epl-2.0/

Description:
This is an eclipse product

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [jakarta.inject 2.6.1](https://clearlydefined.io/definitions/maven/mavencentral/org.glassfish.hk2.external/jakarta.inject/2.6.1)

### CODE REVIEW

**Comment by TRQ3** [comment]
1. Package files point to EPL 2.0 OR GPL 2.0 only with classpath exception. https://clearlydefined.io/file/8f7ae33adf6bfb459833618ae0aef4b860cc4d03888952f1d72b435334ae1f8d
2. Pom file points to similar language, but references GPL 2.0 as a secondary license from EPL 2.0. The link from the package files explicitly contains both licenses. The Pom file does not. Although, the author does include SPDX identifier language. https://repo1.maven.org/maven2/org/glassfish/hk2/external/jakarta.inject/2.6.1/jakarta.inject-2.6.1.pom
3. The sources jar points to the same package files language that includes both EPL 2.0 OR GPL 2.0 only with classpath exception. 

I think the package files and the sources jar makes the most sense as EPL 2.0 OR GPL 2.0 only with classpath exception. However, it is unclear whether the Pom file's language tips toward just EPL 2.0, given the reference to GPL as a secondary license. Thoughts, @ariel11 @AE49?

**Comment by capfei** [comment]
@TRQ3 Per the "Notes" on the SPDX license page, it should be OR.
https://spdx.org/licenses/EPL-2.0.html
> Secondary Licenses declared via Exhibit A should be represented using the disjunctive OR operator (See: SPDX spec, section on SPDX License Expressions and https://www.eclipse.org/legal/epl-2.0/faq.php for more info).

This should be curated as EPL-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0. Let me know if you agree.

**Comment by TRQ3** [comment]
@capfei That makes sense to me. Thank you! I agree.

**Comment by capfei** [comment]
@TRQ3 Updated!

**Review by TRQ3 — APPROVED** [review]

**Pull request merged**
