### PR TITLE
GoogleAppMeasurement 9.2.0

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
GoogleAppMeasurement 9.2.0

**Details:**
Add Apache-2.0 License

**Resolution:**
License Url: 
https://github.com/google/GoogleAppMeasurement/blob/main/LICENSE

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [GoogleAppMeasurement 9.2.0](https://clearlydefined.io/definitions/pod/cocoapods/-/GoogleAppMeasurement/9.2.0)

### CODE REVIEW

**Comment by AE49** [comment]
It looks like the source is under Apache-2.0 but on this page it says license is OTHER - https://libraries.io/cocoapods/GoogleAppMeasurement but the link goes to GPL-3.0-or-later license.

When I do a search on cocoapods.org for the component name a later version links to this page - https://developers.google.com/ios.

What do you think should be Declared?

**Comment by capfei** [comment]
@AE49 I'm thinking OTHER. I couldn't find anything on the iOS site that pointed to that repo. Also, the podspec states "Copyright 2022 Google" for the license. 
https://github.com/CocoaPods/Specs/blob/master/Specs/e/3/b/GoogleAppMeasurement/9.2.0/GoogleAppMeasurement.podspec.json#L25-L27

**Comment by ariel11** [comment]
@AE49 and @capfei - for the package, I don't see any license information.  There's a copyright notice and a description in row 15 of the podspec that says the package "isn't intended for direct use, but rather as a dependency of some Google libraries."  But I don't see an actual license that clearly applies to this package, so I would recommend curating the package as "NONE."

**Review by capfei — APPROVED** [review]

**Comment by capfei** [comment]
Since all of the other versions have the same information, I updated them all to 'NONE'.

**Pull request merged**
