### PR TITLE
wkhtmltopdf.msvc.exe 1.0.0

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
wkhtmltopdf.msvc.exe 1.0.0

**Details:**
Add GPL-3.0-only License

**Resolution:**
License Url: 
https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/LICENSE

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [wkhtmltopdf.msvc.exe 1.0.0](https://clearlydefined.io/definitions/nuget/nuget/-/wkhtmltopdf.msvc.exe/1.0.0)

### CODE REVIEW

**Comment by LandOfBliss** [comment]
Looked in the "Files" section on the ClearlyDefined definition.  Nuspec does not include license info.
Nuget does not include license field.
Source code project license link is broken.  Link provided by submitter goes to GPL-3.0-only license: https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/LICENSE
The specific version is not in the source code project but last version is GPL-3.0
Project notes:  This package has been deprecated as it is legacy and has critical bugs.
Conclusion:  Declared license is GPL-3.0

**Comment by partychen** [comment]
@LandOfBliss seems I can not change anything in this page, https://dev.azure.com/ceapex/Engineering/_componentGovernance/178968/alert/4676230?typeId=6561903. 
so what's the way for us to fix it? only need to declare license is GPL-3.0?

**Comment by LandOfBliss** [comment]
> @LandOfBliss seems I can not change anything in this page, https://dev.azure.com/ceapex/Engineering/_componentGovernance/178968/alert/4676230?typeId=6561903.
> so what's the way for us to fix it? only need to declare license is GPL-3.0?

@partychen No action for you.  The PR is in the review process and information I provided in the PR will be reviewed/validated and processed shortly by another team member.

**Comment by partychen** [comment]
@LandOfBliss I found we have raise this task almost one month? Is there anyway we can get quick response? Could you help on this, thanks.

**Comment by ariel11** [comment]
@LandOfBliss - "GPL-3.0" is not a SPDX identifier.  Also, the license file is LGPL, not GPL.  Looking in the repo around the time of this package, it appears this is LGPL-3.0-or-later - https://github.com/wkhtmltopdf/wkhtmltopdf/blob/0.12.2.4/src/lib/converter_p.hh.  I will update and merge.  Thanks

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
