### PR TITLE
python 3.8.7

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
python 3.8.7

**Details:**
Add PSF-2.0 License

**Resolution:**
License Url: 
https://docs.python.org/3.7/license.html

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [python 3.8.7](https://clearlydefined.io/definitions/nuget/nuget/-/python/3.8.7)

### CODE REVIEW

**Comment by AE49** [comment]
@capfei Should this be "Python-2.0" - https://www.nuget.org/packages/python/3.8.7/License?

**Comment by ariel11** [comment]
@AE49 - for some more background, see the comments on this PR: https://github.com/clearlydefined/curated-data/pull/9023.  I will do some digging into this...

**Comment by capfei** [comment]
@AE49 @ariel11 I asked the OSI license discussion group and couldn't get a response from anyone who knew where the current OSI version of this license came from. I will try to submit a license approval request this week to get the text updated.

**Comment by capfei** [comment]
Someone submitted a request to SPDX to add Python 2.0.1, which is closer to the version of the license we usually come across. The license section headers are slightly different though. I asked if updating Python-2.0 made more sense than adding [Python 2.0.1 license](https://directory.fsf.org/wiki/License:Python-2.0.1), which I don't come across either.

https://github.com/spdx/license-list-XML/issues/1200

**Comment by AE49** [comment]
@ariel11 @capfei Should I Declare this as OTHER and merge?

**Comment by capfei** [comment]
@AE49 Yes, we have agreed, for now, to do OTHER.

**Review by AE49 — APPROVED** [review]

**Comment by AE49** [comment]
Declaring OTHER for no SPDX identifier.

**Pull request merged**
