### PR TITLE
org.hibernate.javax.persistence:hibernate-jpa-2.1-api 1.0.0.Final

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
org.hibernate.javax.persistence:hibernate-jpa-2.1-api 1.0.0.Final

**Details:**
Add EPL-1.0 License

**Resolution:**
License Url: 
https://mvnrepository.com/artifact/org.hibernate.javax.persistence/hibernate-jpa-2.1-api/1.0.0.Final

Description:
from maven url

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [hibernate-jpa-2.1-api 1.0.0.Final](https://clearlydefined.io/definitions/maven/mavencentral/org.hibernate.javax.persistence/hibernate-jpa-2.1-api/1.0.0.Final)

### CODE REVIEW

**Comment by AE49** [comment]
@capfei EPL 1.0 and EDL 1.0 are both listed as licenses in the POM file. I would add EDL 1.0 as "OTHER" and curate this component as "EPL 1.0 and OTHER". Please let me know if you agree and I'll make the edit to the Files Changed and merge. Thanks

https://repo1.maven.org/maven2/org/hibernate/javax/persistence/hibernate-jpa-2.1-api/1.0.0.Final/hibernate-jpa-2.1-api-1.0.0.Final.pom

**Comment by capfei** [comment]
@AE49 [EDL 1.0](https://www.eclipse.org/org/documents/edl-v10.php) is just the BSD-3-Clause license so I would curate as `EPL-1.0 OR BSD-3-CLAUSE`.

> OSI Approved
> The Eclipse Distribution License is an OSI Approved Open Source License by means of the [New BSD License](http://www.opensource.org/licenses/BSD-3-Clause).

@ariel11 Do you agree?

**Comment by ariel11** [comment]
@capfei and @AE49 - yes, I agree.  EDL 1.0 = BSD-3-Clause.

Do you see the term "dual licensed" anywhere, or any indication this is "OR"?  I suspect they mean "OR," but the file headers are not very clear.

image

**Review by AE49 — APPROVED** [review]

**Comment by capfei** [comment]
@ariel11 No, I assumed OR. I tried looking at their other repos, website, docs... This was the only one that I could find that has these Eclipse licenses.

**Pull request merged**
