### PR TITLE
Add Declared License

### PR DESCRIPTION
**Pull request by AE49**
**Type:** Incomplete

**Summary:**
Add Declared License

**Details:**
Adding BSD-3-Clause 

**Resolution:**
Followed version 1.2.0 which notes BSD-3-Clause on pypi.org page, clicked version Homepage which goes to https://pytorch.org/, has direct link to GitHub repo, searched license for 1.1.0 - https://github.com/pytorch/pytorch/blob/v1.1.0/LICENSE

**Affected definitions**:
- [torch 1.1.0](https://clearlydefined.io/definitions/pypi/pypi/-/torch/1.1.0/1.1.0)

### CODE REVIEW

**Comment by capfei** [comment]
@AE49 I'm seeing BSD-3-Clause in the package contents and the source repo. https://github.com/pytorch/pytorch/blob/v1.1.0/LICENSE. 

Can you point me where it is BSD-1-Clause?

**Comment by AE49** [comment]
@capfei I started at https://pypi.org/project/torch/1.1.0/ from ClearlyDefined, and used the link on the the pypi.org page (left for the libraries.io) - https://libraries.io/pypi/torch/1.1.0. BSD-1-Clause is referenced on the libraries.io page. I didn't see any direct links to the GitHub repo although I see our point on the BSD-3-Clause in that repo.

**Comment by AE49** [comment]
@capfei Thanks. I updated the Declared License and Resolution to BSD-3-Clause.

**Comment by ariel11** [comment]
I agree with BSD-3-clause and will merge, since Candice is on vacation.  Thanks!

**Pull request merged**
