### PR TITLE
org.scalamacros:paradise_2.12.14 2.1.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
org.scalamacros:paradise_2.12.14 2.1.1

**Details:**
Add BSD-3-Clause License

**Resolution:**
License Url: 
https://github.com/scalamacros/paradise/blob/2.12.8/LICENSE.md

Description:
The supplied link was found within the scalamacros/paradise Github repository and for that reason.  Furthermore, the following commit link shows the library Scala version is set to 2.12.14 (https://github.com/scalamacros/paradise/commit/738c0e3d599be29e65371b69ec44a554007102a6). 

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [paradise_2.12.14 2.1.1](https://clearlydefined.io/definitions/maven/mavencentral/org.scalamacros/paradise_2.12.14/2.1.1)

### CODE REVIEW

**Comment by LandOfBliss** [comment]
Looked in the "Files" section on the ClearlyDefined definition. License links to BSD-3-Clause
Nuget license field indicates BSD-3-Clause
Source code project is BSD-3-Clause
Conclusion:  Declared license is BSD-3-Clause

**Comment by abahocodes** [comment]
@LandOfBliss pardon my ignorance but does this PR have additional requirements in order to be merged?

**Comment by ariel11** [comment]
@LandOfBliss - on the POM, the license URL goes here - http://www.scala-lang.org/downloads/license.html - and that says the project changed to Apache-2.0 after Dec 2018.  The LICENE in the repo dates back to 2105 and the README says the project is no longer actively being developed (on GitHub).  I would take this to mean this package (published this year) is Apache-2.0.  

Thoughts @capfei ?

**Comment by capfei** [comment]
@LandOfBliss @ariel11 Since they are using the Maven package and the pom points to the Scala site for the license, I would agree with Apache since this was published after Scala changed licenses.

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
