### PR TITLE
Add MIT License

### PR DESCRIPTION
**Pull request by TRQ3**
**Type:** Missing

**Summary:**
Add Apache 2.0 License

**Details:**
No info in package files. meta data points to Apache 2.0. 

**Resolution:**
https://raw.githubusercontent.com/xunit/xunit/master/license.txt

**Affected definitions**:
- [xunit.assert 2.0.0](https://clearlydefined.io/definitions/nuget/nuget/-/xunit.assert/2.0.0/2.0.0)

### CODE REVIEW

**Comment by capfei** [comment]
@TRQ3 Both https://raw.githubusercontent.com/xunit/xunit/master/license.txt and https://github.com/xunit/xunit/blob/2.0/license.txt state the license is Apache 2.0.

**Comment by TRQ3** [comment]
@capfei You're right. Must have been looking below, where it says MIT. I think I have fixed it. Thanks.

**Comment by TRQ3** [comment]
@capfei You're right. Must have been looking below, where it says MIT. I think I have fixed it. Thanks.

**Comment by capfei** [comment]
@TRQ3 Thanks for confirming!

**Pull request merged**
