### PR TITLE
Adding missing declared licenses

### PR DESCRIPTION
**Pull request by capfei**
**Type:** Missing

**Summary:**
Adding missing declared licenses

**Details:**
Missing licenses

**Resolution:**
https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/v0.1.22/LICENSE.txt
https://github.com/mscdex/busboy/blob/v0.2.14/LICENSE
https://github.com/Raynos/console-stream/blob/343dd07bbefb17023aafd78065fe2ba3739fbc49/LICENCE
https://github.com/mscdex/dicer/blob/v0.2.5/LICENSE

**Affected definitions**:
- [adal-node 0.1.22](https://clearlydefined.io/definitions/npm/npmjs/-/adal-node/0.1.22),- [busboy 0.2.14](https://clearlydefined.io/definitions/npm/npmjs/-/busboy/0.2.14),- [console-stream 0.1.1](https://clearlydefined.io/definitions/npm/npmjs/-/console-stream/0.1.1),- [dicer 0.2.5](https://clearlydefined.io/definitions/npm/npmjs/-/dicer/0.2.5)

### CODE REVIEW

**Comment by ariel11** [comment]
@geneh - Can you help please with the failed check?  Thank you!

**Comment by geneh** [comment]
Done! For some reason the indentation got off in one of the lines during the merge, not sure why. Was it a manual merge?

**Comment by fossygirl** [comment]
@geneh Is this okay to merge?

**Comment by geneh** [comment]
@fossygirl Yes, it looks like @ariel11 has approved this change. I'll merge.

**Pull request merged**
