### PR TITLE
OpenSSL.Windows-1.0.2n 0.0.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
OpenSSL.Windows-1.0.2n 0.0.1

**Details:**
Add Apache-2.0 License

**Resolution:**
License Url: 
https://www.openssl.org/source/license.html

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [OpenSSL.Windows-1.0.2n 0.0.1](https://clearlydefined.io/definitions/nuget/nuget/-/OpenSSL.Windows-1.0.2n/0.0.1)

### CODE REVIEW

**Comment by TRQ3** [comment]
1. Package files show OpenSSL license. https://clearlydefined.io/file/6ec0ec06504b49f669f395a28c922077c6f0ceb8ec381458380450eafe70d29a
2. Meta data not showing a link to source repo or license. https://www.nuget.org/packages/OpenSSL.Windows-1.0.2n
3. Nuspec links to OpenSSL License. 

Should curate as OpenSSL license. Do you agree, @ariel?

**Comment by AE49** [comment]
@TRQ3 The Project link goes to Openssl webpage and there’s a file in the package also pointing to the same place. The license for earlier releases (prior to v3) is double licensed OpenSSL and Original SSLeay – 
/source/license.html (openssl.org)
https://www.openssl.org/source/license-openssl-ssleay.txt

I would curate as “OpenSSL AND OTHER”

@capfei Thoughts?

**Comment by capfei** [comment]
@AE49 This looks like repackaged code. I can only find reference to this package here:  https://github.com/microsoft/react-native-windows/issues/2170.

I'm not certain; maybe it should be curated as "NONE" and the rest should be under "discovered"? @ariel11 @royaljust What do you think?

**Comment by AE49** [comment]
@capfei @TRQ3 You're right on the "OpenSSL" (it includes the SSLeay license text). Justin and I discussed - this is an edge case but we should Declare as "OpenSSL" because this looks like a NuGet wrapper for OpenSSL and the author explicitly put OpenSSL as the project website which indicates the intention to license under OpenSSL. We could reach out to the Microsoft contact who published the package to confirm.
@royaljust

**Comment by ariel11** [comment]
@TRQ3 - Agree with "OpenSSL."  Thanks!

**Review by TRQ3 — APPROVED** [review]

**Pull request merged**
