### PR TITLE
JWT 7.3.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
JWT 7.3.1

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/jwt-dotnet/jwt/blob/main/LICENSE.md

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [JWT 7.3.1](https://clearlydefined.io/definitions/nuget/nuget/-/JWT/7.3.1)

### CODE REVIEW

**Comment by TRQ3** [comment]
1. No info in package files. 
2. Source repo does not have a tagged version. The license file shows CCO-1.0 AND MIT. The license file has not been changed since publication on Dec 2, 2019. This package was released 3 months ago. https://github.com/jwt-dotnet/jwt/blob/main/LICENSE.md
3. Nuspec links to the same as above, confirming CCO-1.0 AND MIT. 

Should curate as CCO-1.0 AND MIT.

**Comment by ariel11** [comment]
@TRQ3  - it looks like JWT is CC0-1.0 while two other subprojects are MIT - https://github.com/jwt-dotnet/jwt#license.  So, I think this package is just CC0-1.0.  Thoughts?

**Comment by TRQ3** [comment]
@ariel11 - I see how you got there. I agree. Can you update the license file?

**Comment by ariel11** [comment]
@TRQ3 - Updated

**Review by TRQ3 — APPROVED** [review]

**Pull request merged**
