### PR TITLE
colorbrewer 1.0.0

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
colorbrewer 1.0.0

**Details:**
Add Apache-2.0 License

**Resolution:**
License Url: 
https://raw.githubusercontent.com/saikocat/colorbrewer/master/LICENSE.txt

Description:
The license file is on the master branch in the source repo linked from the npm package.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [colorbrewer 1.0.0](https://clearlydefined.io/definitions/npm/npmjs/-/colorbrewer/1.0.0)

### CODE REVIEW

**Comment by capfei** [comment]
@ariel11 @AE49 The included license text states Apache 2.0 but also includes most of Apache 1.1. The package.json states "Apache-Style". Should we do OTHER? Apache 2.0 AND OTHER? 🤔 

Source repo: https://github.com/saikocat/colorbrewer/blob/52e96c4c4c0c8b8b9bb8d078352f60f55440abba/LICENSE.txt

**Comment by AE49** [comment]
@capfei @ariel11 I think Apache-2.0 AND OTHER.

**Comment by ariel11** [comment]
@capfei , @AE49 - interesting one.  Yes, I agree with "Apache-2.0 AND OTHER."  The LICENSE.txt states the license is Apache 2.0 and then that is followed by a modified second license that doesn't meet the matching requirements for any SPDX identifier (it is missing the whole disclaimer section of Apache 1.0 or 1.1).   It is not called out as an alternative license or say it is dual licensed, so the impression is that both licenses apply.  Thoughts, @capfei ?

**Comment by capfei** [comment]
@ariel11 @AE49 After looking around some more, I found clarity on the license.

The `package.json` lists http://colorbrewer2.org/ as the `homepage`. This page lists https://github.com/axismaps/colorbrewer as the source repo. I found this issue regarding the license: https://github.com/axismaps/colorbrewer/issues/7

The original author, Cynthia Brewer, states she is using Apache 2.0 but is leaving parts from her original Apache 1.1 license for guidance on attribution and permissions: http://www.personal.psu.edu/cab38/ColorBrewer/ColorBrewer_updates.html

To me this sounds like it should be "AND". If I get a thumbs up, I'll update the PR. 😄

**Review by capfei — APPROVED** [review]

**Pull request merged**
