### PR TITLE
Missing Declared License

### PR DESCRIPTION
**Pull request by ariel11**
**Type:** Missing

**Summary:**
Missing Declared License

**Details:**
Followed source link: https://github.com/microsoft/bond/blob/15d58be7fc1bcb6264492ec88431d228c1e9d9e6/LICENSE

**Resolution:**
Curated MIT

**Affected definitions**:
- [Bond.Runtime.CSharp 5.1.0](https://clearlydefined.io/definitions/nuget/nuget/-/Bond.Runtime.CSharp/5.1.0/5.1.0)

### CODE REVIEW

**Comment by pombredanne** [comment]
@ariel11 would you know why we have these issues of checks?

**Comment by ariel11** [comment]
@pombredanne - No, I don't know what is causing this issue.  I emailed @iamwillbar or help with these.

**Comment by AE49** [comment]
@iamwillbar can you please take a look and resolve the failed checks?

**Comment by AE49** [comment]
@ignacionr Can you help with the failed checks?

**Comment by ignacionr** [comment]
The problem is easy; at https://github.com/clearlydefined/curated-data/pull/2187/files#diff-f8f6e727aaafeba330fb7e04819ecf87R22 the SourceLocation is missing a 'name'.

**Comment by ignacionr** [comment]
@AE49 you are now able to merge

**Pull request merged**
