### PR TITLE
maven/mavencentral/io.jsonwebtoken/jjwt.yaml

### PR DESCRIPTION
**Pull request by waynebeaton**

### CODE REVIEW

**Comment by waynebeaton** [comment]
The ClearlyDefined validator indicates an error. Clicking "Details" takes me to what looks like the default landing page at clearlydefined.io. What have I don wrong?

**Comment by capfei** [comment]
@waynebeaton I don't think the validator is set up to check Maven yet. It can check NPM, NuGet and, possibly, GitHub, although I am not certain.

**Comment by jeffmcaffer** [comment]
Hey @waynebeaton for some reason I did not see this PR. @capfei has it right. we'll have to take a look at that. We have a workitem to integrate the Checks API that should give you richer feedback.

let me dig in and see what's going on here

**Comment by fossygirl** [comment]
@waynebeaton I'm going to close this for now, but please feel free to reopen if you'd like us to review and potentially merge this curation.

**Comment by waynebeaton** [comment]
What does "close this for now" mean? Is this "thanks, but no thanks"?

Do you want to work with me to accept this contribution or not?

**Comment by jeffmcaffer** [comment]
Hmm, don't think this should have been closed. It may be that the schemas were changed but if that's the case we can update the PR with the data in the new form. Reopening.

**Pull request merged**
