### PR TITLE
apple/swift-numerics 6583ac70c326c3ee080c1d42d9ca3361dca816cd

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
apple/swift-numerics 6583ac70c326c3ee080c1d42d9ca3361dca816cd

**Details:**
Add Apache-2.0 License

**Resolution:**
License Url: 
https://github.com/apple/swift-numerics/blob/main/LICENSE.txt

Description:
This is the license from the repo.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [swift-numerics 6583ac70c326c3ee080c1d42d9ca3361dca816cd](https://clearlydefined.io/definitions/git/github/apple/swift-numerics/6583ac70c326c3ee080c1d42d9ca3361dca816cd)

### CODE REVIEW

**Comment by LandOfBliss** [comment]
Looked in the "Files" section on the ClearlyDefined definition.  License file is Apache-2.0
Source code project license is Apache-2.0
Conclusion:  Declared license is Apache-2.0

**Comment by capfei** [comment]
@LandOfBliss I think this should be Apache-2.0 WITH Swift-exception. The license file states the exception at the bottom:
https://github.com/apple/swift-numerics/blob/6583ac70c326c3ee080c1d42d9ca3361dca816cd/LICENSE.txt#L205.

Do you agree?

**Comment by dianambb** [comment]
Hi @LandOfBliss  & @capfei! Is there an update on this? Our team is waiting on this.

**Comment by capfei** [comment]
@AE49 Do you agree that this should be Apache-2.0 WITH Swift-exception?

**Comment by ariel11** [comment]
@capfei - Yes, I agree with Apache-2.0 WITH Swift-exception.  I will update and merge.  Thanks

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
