### PR TITLE
gensim 3.8.3

### PR DESCRIPTION
**Pull request by AE49**
**Type:** Incorrect

**Summary:**
gensim 3.8.3

**Details:**
Fixing the Declared license to LGPL 2.0 or later

**Resolution:**
PyPi meta: GNU Lesser General Public License v2 or later (LGPLv2+) (LGPLv2.1)

https://pypi.org/project/gensim/3.8.3/

**Affected definitions**:
- [gensim 3.8.3](https://clearlydefined.io/definitions/pypi/pypi/-/gensim/3.8.3/3.8.3)

### CODE REVIEW

**Comment by capfei** [comment]
@AE49 Looking at the file headers and the `COPYING`file, they state LGPL 2.1.

Header
```
# Copyright (C) 2010 Radim Rehurek <radimrehurek@seznam.cz>
# Licensed under the GNU LGPL v2.1 - http://www.gnu.org/licenses/lgpl.html
```

The `PKG-INFO` states: Gensim is open source software released under the GNU LGPLv2.1 license. Copyright (c) 2009-now Radim Rehurek

I think it should curated as `LGPL-2.1-only`. Let me know if you agree.

**Comment by AE49** [comment]
@capfei The How to Apply These Terms at the end of the license file says 2.1 or later - on this page https://pypi.org/project/gensim/3.8.3/ and at bottom is the license link: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html. We can get also get input from other curators.

**Comment by capfei** [comment]
@AE49 The SPDX listing for LPGL-2.1-only also has that so I'm not sure. 😕 
https://spdx.org/licenses/LGPL-2.1-only.html

I'll post this one to the community for their thoughts.

**Comment by ariel11** [comment]
@capfei and @AE49 - the METADATA file in the package says: 

Classifier: License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)

**Comment by capfei** [comment]
@ariel11 If you look higher, it also says `License: LGPLv2.1`.

**Comment by ariel11** [comment]
> @ariel11 If you look higher, it also says `License: LGPLv2.1`.

Yes.  Did you put this one to the community?

**Comment by capfei** [comment]
@ariel11 Not yet. I was going to post it to the community after I got through these PRs.

**Comment by pombredanne** [comment]
PyPI classifiers do not support the LGPL 2.1 license ... so the metadata is inaccurate. See https://pypi.org/classifiers/

The license is LGPL-2.1-only alright IMHO. See this PR to correct the metadata https://github.com/RaRe-Technologies/gensim/pull/2871

Eventually this will become a non issue, as soon as I finish submitting this as a Python Enhancement Proposal https://discuss.python.org/t/improving-license-clarity-with-better-package-metadata/2154

And when this is accepted, the new norm will be to use an SPDX license expression in the License attribute of a PyPI package metadata.

@piskvorky FYI

**Comment by AE49** [comment]
@capfei OK given @pombredanne comments. I made the edit to LGPL-2.1-only.

**Pull request merged**
