### PR TITLE
matplotlib 3.3.3

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
matplotlib 3.3.3

**Details:**
Add Python-2.0 License

**Resolution:**
License Url: 
https://spdx.org/licenses/PSF-2.0.html

Description:
The matplotlib pypi.org site lists this as the license for this specific version (3.3.3)

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [matplotlib 3.3.3](https://clearlydefined.io/definitions/pypi/pypi/-/matplotlib/3.3.3)

### CODE REVIEW

**Comment by capfei** [comment]
The license link for matplotlib states that it is based on PSF. Looking at it, it looks to be a modified PSF license so I think this should be curated as OTHER. The license file included in the pypi has the same verbiage.
https://matplotlib.org/users/license.html

@ariel11 what do you think?

**Comment by mirceamt** [comment]
It looks like there is a merge conflict but I couldn't find any.
Are there any blockers or is there anything we can do from our side?

**Comment by ariel11** [comment]
@capfei - sorry I missed your comment to me.  Yes, I agree with "OTHER" here, due to the customizations of the license.  Thanks!

**Comment by mirceamt** [comment]
thank you! 😄

**Pull request merged**
