### PR TITLE
github.com/fmtlib/fmt

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
github.com/fmtlib/fmt

**Details:**
fmtlib is distributed under the MIT license.

**Resolution:**
https://github.com/fmtlib/fmt#license

**Affected definitions**:
- [fmt a30b279bad752ff4c4967c6d1bfcfc8d79c6b170](https://clearlydefined.io/definitions/git/github/fmtlib/fmt/a30b279bad752ff4c4967c6d1bfcfc8d79c6b170/a30b279bad752ff4c4967c6d1bfcfc8d79c6b170)

### CODE REVIEW

**Comment by tusharb86** [comment]
@capfei @AE49 - Friendly ping on this PR. Let me know if there is anything else needed or if I missed something here. Thanks so much! (Sorry for the nudge - my team is trying to drive down to 0 alerts in Component Governance)

**Comment by capfei** [comment]
@AE49 I think this should be OTHER due to the exception included at the end of the license:
```
--- Optional exception to the license ---

As an exception, if, as a result of your compiling your source code, portions of this Software are embedded into a machine-executable object form of such source code, you may redistribute such embedded portions in such object form without including the above copyright and permission notices.
```

What do you think?

**Comment by capfei** [comment]
@AE49 I think this should be OTHER due to the exception included at the end of the license:
```
--- Optional exception to the license ---

As an exception, if, as a result of your compiling your source code, portions of this Software are embedded into a machine-executable object form of such source code, you may redistribute such embedded portions in such object form without including the above copyright and permission notices.
```

What do you think?

**Comment by ariel11** [comment]
I agree with OTHER.

**Review by capfei — APPROVED** [review]

**Pull request merged**
