### PR TITLE
Update license data

### PR DESCRIPTION
**Pull request by bduranc**
**Type:** Incomplete

**Summary:**
Update license data

**Details:**
1. No top-level license was declared for this project.
2. Some individual files were missing license information, despite most being clearly indicated in the header of said files.

**Resolution:**
1. Project is a mix of GPL-2.0 and BSD-2-Clause licenses.

<project root>/LICENSE explains this project uses 2 different licenses: 
- all files in the `lib`: BSD 2-Clause license
- all other files: GPLv2 license unless otherwise stated

2. For individual files, I simply declared same as file header.

**Affected definitions**:
- lz4 dfed9fa1d77f0434306d377c4da1f7191d3ba08a

### CODE REVIEW

**Comment by bduranc** [comment]
@capfei : I notice this PR has been tagged with 'info needed', yet I see no additional details. Can you please elaborate?

Thanks.

**Comment by capfei** [comment]
@bduranc Yes, sorry. I commented in the review, but I guess that doesn't show up for everyone.

My question is regarding the license for "contrib/cmake_unofficial/CMakeLists.txt". The header says, "For details, see http://creativecommons.org/publicdomain/zero/1.0". Should this be listed as "CC0-1.0" instead of "NOASSERTION"?

**Comment by bduranc** [comment]
@capfei : You are totally right, it should be CC0 instead of NOASSERTION.

> @bduranc Yes, sorry. I commented in the review, but I guess that doesn't show up for everyone.
> 
> My question is regarding the license for "contrib/cmake_unofficial/CMakeLists.txt". The header says, "For details, see http://creativecommons.org/publicdomain/zero/1.0". Should this be listed as "CC0-1.0" instead of "NOASSERTION"?

**Comment by capfei** [comment]
Thanks for confirming! I updated the PR and merged.

**Pull request merged**
