### PR TITLE
Added Declared license

### PR DESCRIPTION
**Pull request by ariel11**
**Type:** Missing

**Summary:**
Added Declared license

**Details:**
Followed Source link 

**Resolution:**
https://github.com/aspnet/Hosting/blob/0724e6cde1149ee1a19bfec9c13a2c9327b71213/LICENSE.txt

**Affected definitions**:
- [microsoft.extensions.hosting 2.2.0](https://clearlydefined.io/definitions/nuget/nuget/-/microsoft.extensions.hosting/2.2.0/2.2.0)

### CODE REVIEW

**Comment by pombredanne** [comment]
@ariel11 that's weird. Would you know why there changes are empty?

**Comment by ariel11** [comment]
> @ariel11 that's weird. Would you know why there changes are empty?

@pombredanne  - I have seen this before, and I don't know why it happens. I can open a bug/issue if @capfei hasn't already.  I will take a look...

**Comment by capfei** [comment]
@ariel11 @pombredanne It looks like we have two files for this package: [microsoft.extensions.hosting.yaml](https://github.com/clearlydefined/curated-data/blob/master/curations/nuget/nuget/-/microsoft.extensions.hosting.yaml) and [Microsoft.Extensions.Hosting.yaml](https://github.com/clearlydefined/curated-data/blob/master/curations/nuget/nuget/-/Microsoft.Extensions.Hosting.yaml). The site seems to pull info from the uppercase file (doesn't have 2.2.0) and the PR submitted with the lowercase (which does).

**Comment by capfei** [comment]
I submitted an issue to the service repo and listed another PR with the same problem:
https://github.com/clearlydefined/service/issues/622

**Comment by capfei** [comment]
Adding bug label so I can easily see which PRs are affected by this issue.

**Comment by capfei** [comment]
Any PRs I processed yesterday that are NuGets with upppercase names will have this issue like https://github.com/clearlydefined/curated-data/pull/2496.

**Comment by ignacionr** [comment]
This PR contains no changes as compared to ```master```; closing; let's track [here](https://github.com/clearlydefined/service/issues/626#issuecomment-540533384)

**Pull request closed without merging**
