### PR TITLE
mono/mono abad3612068e7333956106e7be02d9ce9e346f92

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
mono/mono abad3612068e7333956106e7be02d9ce9e346f92

**Details:**
Add MIT AND BSD-3-Clause AND BSD-4-Clause AND GPL-2.0-only AND CC-BY-4.0 AND CC-BY-2.5 AND Info-ZIP AND MS-PL AND MPL-1.1 AND Apache-2.0 License

**Resolution:**
License Url: 
https://github.com/mono/mono/blob/main/LICENSE

Description:
License as listed on github project

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [mono abad3612068e7333956106e7be02d9ce9e346f92](https://clearlydefined.io/definitions/git/github/mono/mono/abad3612068e7333956106e7be02d9ce9e346f92)

### CODE REVIEW

**Comment by ariel11** [comment]
@capfei - well, this one is tricky as ClearlyDefined defines the declared license as the "overall license," while "discovered" licenses only apply to portions of the project.  See: https://github.com/clearlydefined/clearlydefined/blob/master/docs/curation-guidelines.md#the-difference-between-declared-and-discovered-licenses.

Looking at the LICENSE for this commit, I'd say the closest thing to a stated "overall license," would be MIT - see highlighted portions in screenshot.  There's also mention of a commercial license option. So, I think for declared, I would do "MIT OR OTHER" and all the other licenses would be "discovered."  Thoughts?

image

**Comment by bduranc** [comment]
Sorry for being late to the party.

I would be hesitant to declare the overall license as "MIT OR OTHER" because it clearly says dual-licensed under GPL OR LGPL or the commercial terms. Also, while many of the licenses here are GPL-compatible, there are some that are not.

Looking at the license files under the `./mcs` folder; no specific version of the GPL or LGPL are mentioned. The LGPL looks to be the earlier "Library General Public License" version (2.0) judging from the header text included in LICENSE.LGPL file.

In the spirit of transparency and conveying facts, my first thought would have probably been to do exactly what @capfei already proposed in this PR and declare all applicable licenses. I feel this does better convey the scope of applicable licenses to data consumers as well and therefore also makes the risks more apparent without crossing the fine line of "conveying risk".

For cases like this: it might be beneficial if we could use the "tags" feature to declare licenses specific to individual paths :)

Just my two cents.

**Comment by ariel11** [comment]
@bduranc - My thinking here is primarily how to distinguish what we put in the "declared" field vs. what is left in the "discovered" field.  Later versions of the mono license file more clearly state the following: "In general, the runtime and its class libraries are licensed under the terms of the MIT license..."  

Take how we define "declared" vs. "discovered" and how we use "OR OTHER" when there's a commercial license options, is where I got "MIT OR OTHER" for the declared field and all the other licenses would be in the discovered field. 
image

It can be unclear how to split the declared/discovered fields when there's not a clear "overall" license.

**Comment by royaljust** [comment]
Suggest "other" here -- there are multiple licenses with unclear lines indicating no indentation for an "all up" license for the project.

**Review by capfei — APPROVED** [review]

**Pull request merged**
