### PR TITLE
ecdsa 0.14

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
ecdsa 0.14

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/warner/python-ecdsa

Description:
From https://pypi.org/project/ecdsa/:

"This is an easy-to-use implementation of ECDSA cryptography (Elliptic Curve Digital Signature Algorithm), implemented purely in Python, released under the MIT license"

Pull request generated by Microsoft automation.

**Affected definitions**:
- [ecdsa 0.14](https://clearlydefined.io/definitions/pypi/pypi/-/ecdsa/0.14)

### CODE REVIEW

**Comment by capfei** [comment]
It looks like this was derived and built-on from another project that released under public domain. I think this should be curated as `MIT AND OTHER`.

What do others think?

Import of code: https://github.com/warner/python-ecdsa/tree/7be94f3edbe699aa97ef38d810ae59526db15512
License: https://github.com/warner/python-ecdsa/blob/python-ecdsa-0.14/LICENSE

**Comment by ariel11** [comment]
@capfei - I think the "portions of" would be considered a "discovered" license and the "declared" is MIT.

**Comment by ariel11** [comment]
@royaljust - can you comment?

**Comment by royaljust** [comment]
Agree with Ariel.

**Comment by capfei** [comment]
Thanks, @ariel11 and @royaljust!

**Pull request merged**
