### PR TITLE
googleapis/google-cloud-go 5f1389763ab4f59736c2a60413b7cb0c59f044a2

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
googleapis/google-cloud-go 5f1389763ab4f59736c2a60413b7cb0c59f044a2

**Details:**
Add Apache-2.0 License

**Resolution:**
License Url: 
https://github.com/googleapis/google-cloud-go/blob/5f1389763ab4f59736c2a60413b7cb0c59f044a2/LICENSE

Description:
googleapis/google-cloud-go is a commonly used go library which is developed and maintained by Google. The License can be found in the official Github Repo with detailed usage, premission and other information.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [google-cloud-go 5f1389763ab4f59736c2a60413b7cb0c59f044a2](https://clearlydefined.io/definitions/git/github/googleapis/google-cloud-go/5f1389763ab4f59736c2a60413b7cb0c59f044a2)

### CODE REVIEW

**Comment by LandOfBliss** [comment]
Looked in the "Files" section on the ClearlyDefined definition.  License file is Apache-2.0
Links to commit
Source code project license is Apache-2.0
Conclusion:  Declared license is Apache-2.0

**Review by AE49 — APPROVED** [review]

**Comment by hhz1992** [comment]
@AE49 Kindly ping this PR, is there any conflicts causing the Invalid curations issue? We are waiting for the PR merged to resolved the open source alert. Cloud you please help to take a look at this PR?

**Comment by hhz1992** [comment]
@AE49 @LandOfBliss I see after the merge conflicts been resolved (by merging from Master branch), the "licensed:" section missed the initial data: "declared: Apache-2.0" which you can compare with the initial PR which sent by the bot.  Cloud you please help to fix the issue caused by code merge?

**Comment by nellshamrell** [comment]
Hi @hhz1992 - I'm taking a look at this now

**Comment by nellshamrell** [comment]
@hhz1992 I'm investigating why the error is not displaying correctly, but I suspect it is being generated because there is no declared license listed for the revision you added.

Taking a look at this section:

image

I think you need a "declared" line under "licensed" (it also looks like the whitespace is off on "licensed" - it should be back two more spaces)

Looking at @LandOfBliss's comment from 10 days ago:

"Conclusion: Declared license is Apache-2.0"

I suspect that you should alter the changed file to say:

```
revisions:
  5f1389763ab4f59736c2a60413b7cb0c59f044a2:
    licensed:
      declared: Apache-2.0
```

**Comment by hhz1992** [comment]
@nellshamrell I agree with your point but I believe the issue was caused by the merge issue. You can take a look at the first commit of this PR which sent by bot:
image

We can see clearly the "declared: Apache-2.0" was added in that commit however it got removed by the following two commits, which are trying to resolve merge conflicts.
Could you please help to add the missing "declared: Apache-2.0" in the file? This PR was sent by the bot thus I don't have the premission to alert the files.

**Comment by nellshamrell** [comment]
@hhz1992 done!

@capfei @ariel11 @AE49 @LandOfBliss is this good to merge?

**Review by capfei — APPROVED** [review]

**Comment by capfei** [comment]
Merged! Thanks @nellshamrell!

**Pull request merged**
