### PR TITLE
Boost Libraries - 1.78.0 - algorithm, align

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
Boost Libraries - 1.78.0 - algorithm, align

**Details:**
All Boost libraries are covered under the BSL. See https://www.boost.org/users/license.html.

**Resolution:**
BSL-1.0

**Affected definitions**:
- [algorithm 3b3bd8d3db43915c74d574ff36b4d945b6fc7917](https://clearlydefined.io/definitions/git/github/boostorg/algorithm/3b3bd8d3db43915c74d574ff36b4d945b6fc7917),- [align 0790cd45c8e05b1b59fffbc948b6bcb26eb6a2aa](https://clearlydefined.io/definitions/git/github/boostorg/align/0790cd45c8e05b1b59fffbc948b6bcb26eb6a2aa)

### CODE REVIEW

**Comment by tusharb86** [comment]
@capfei - Just a heads up that this one is ready to go. In this change, I only included 2 Boost libraries, but I plan on including 50+ in the next PR (now that I understand how to use the Curations Patch API). Is it OK to do them in bulk that way or would you prefer something else? Thanks!

**Comment by capfei** [comment]
@tusharb86 I don't mind multiple, but, maybe limit them to 10 per PR, if possible, so it can be spread across other reviewers or at least allow us to process them in chunks in case we cannot review all 50 in one go.

@ariel11 @AE49 Do you have a preference on bulk curations?

**Comment by ariel11** [comment]
Yes, agree 10 (or less) per PR is ideal for those reviewing the PRs.  Thank you for asking, @tusharb86 - really appreciate it!

**Comment by tusharb86** [comment]
Thanks for feedback @capfei and @ariel11! This PR is ready to go and I'll ensure that the upcoming PRs for version 1.78.0 of other Boost libraries only contain 10 curations at maximum for each one.

**Review by capfei — APPROVED** [review]

**Comment by tusharb86** [comment]
@capfei, @ariel11 - FYI I've created 8 more PRs for different Boost libraries in version 1.78.0. Listing them here:

https://github.com/clearlydefined/curated-data/pull/17085
https://github.com/clearlydefined/curated-data/pull/17086
https://github.com/clearlydefined/curated-data/pull/17087
https://github.com/clearlydefined/curated-data/pull/17088
https://github.com/clearlydefined/curated-data/pull/17089
https://github.com/clearlydefined/curated-data/pull/17090
https://github.com/clearlydefined/curated-data/pull/17091
https://github.com/clearlydefined/curated-data/pull/17092

**Pull request merged**
