### PR TITLE
Declared MIT and updated "nuspec"

### PR DESCRIPTION
**Pull request by peggymoloney**
**Type:** Missing

**Summary:**
Declared MIT and updated "nuspec"

**Details:**
Component (https://github.com/StackExchange/StackExchange.Redis/tree/0b47916a53e269835717c72a474785e10713e723)  License (https://github.com/StackExchange/StackExchange.Redis/blob/0b47916a53e269835717c72a474785e10713e723/LICENSE)

**Resolution:**
Declared MIT and also included SHAREALIKE in license and updated "nuspec"

**Affected definitions**:
- [StackExchange.Redis.StrongName 1.1.603](https://clearlydefined.io/definitions/nuget/nuget/-/StackExchange.Redis.StrongName/1.1.603/1.1.603)

### CODE REVIEW

**Comment by AE49** [comment]
@geneh Can you look at why I cannot merge this curation? Thanks.

**Comment by geneh** [comment]
Related to https://github.com/clearlydefined/service/issues/564

**Comment by AE49** [comment]
@geneh Do I close this PR? It looks like you were able to resolve 564?

**Comment by geneh** [comment]
I've resolved the merge conflict.

**Pull request merged**
