### PR TITLE
Missing declared license

### PR DESCRIPTION
**Pull request by capfei**
**Type:** Missing

**Summary:**
Missing declared license

**Details:**
Missing license

**Resolution:**
I wasn't sure if it should be MIT or NONE since the license isn't declared in the package or in a license URL. I went with MIT since it repackaged code from another project that is MIT.

**Affected definitions**:
- [jQuery.Validation 1.11.1](https://clearlydefined.io/definitions/nuget/nuget/-/jQuery.Validation/1.11.1/1.11.1)

### CODE REVIEW

**Comment by ariel11** [comment]
Project Site link on NuGet download page goes to https://jqueryvalidation.org/, which says MIT.  Agree with MIT.

**Comment by ariel11** [comment]
@geneh - Would you please resolve the conflicts?  I clicked on "Resolve conflicts" to see if I could figure it out, but I am not sure what to do.  Also, I do not see BSD-3-Clause on the jQuery.Validation.nuspec files, as listed here: https://github.com/clearlydefined/curated-data/pull/3021/conflicts.  I checked the nuspec file here -  https://clearlydefined.io/definitions/nuget/nuget/-/jQuery.Validation/1.13.1 - no mention of BSD-3-Clause.

**Comment by capfei** [comment]
@ariel11 I can help resolve merge conflicts, if needed.

BSD-3-Clause for the nuspec comes from the CodePlex archive that states custom files like the nuspec and automation scripts are under that license. https://archive.codeplex.com/?p=nugetpackages

**Comment by geneh** [comment]
Thanks, @capfei! Please let me know if my assistance is needed.

**Comment by capfei** [comment]
Conflict resolved.

**Comment by ariel11** [comment]
@capfei - thanks for the pointer.  This page - https://archive.codeplex.com/?p=nugetpackages - says the nuspec file "is distributed under the license shown in the License tab."  This NuGet doesn't have a License listed on the page - https://www.nuget.org/packages/jQuery.Validation/1.11.1 - but the Project Site link goes here - https://jqueryvalidation.org/ - and says License: MIT.  So isn't the nuspec under MIT like the rest of the package?

**Comment by ariel11** [comment]
@capfei - I'll go ahead and merge this PR, which is for setting the declared license as MIT.  But I dont understand why the commit shows the _nuspec_ files as being BSD-3-Clause.

**Pull request merged**
