### PR TITLE
eclipse/kapua 1.2.3

### PR DESCRIPTION
**Pull request by lorthirk**
**Type:** Other

**Summary:**
Update to latest version

**Details:**
Update to latest version

**Resolution:**
Updated commit and release date to the latest release

**Affected definitions**:
- [kapua 510b549c7e64c8cbbd90b8aabda47bf1e4a827cd](https://clearlydefined.io/definitions/git/github/eclipse/kapua/510b549c7e64c8cbbd90b8aabda47bf1e4a827cd)

### CODE REVIEW

**Comment by capfei** [comment]
@lorthirk Just to confirm, you are trying to curate commit b851dab92141fd95f42e64a3d71dfa1510481eea, not 510b549c7e64c8cbbd90b8aabda47bf1e4a827cd, correct? You submitted changes that apply to b851d, but submitted for 510b5.

Let me know so I can update the PR accordingly.

**Comment by lorthirk** [comment]
Well... Probably I did something wrong: all I wanted was to update the git/github/eclipse/kapua definition to the latest version, since the revision currently indexed is two years old. Is this the right thing to do?

**Comment by capfei** [comment]
@lorthirk The files here only contain edits for versions or commits that have already been scanned and harvested. As far as I am aware, there isn't any mechanism in place to define a commit or version as the latest.

If you wanted to updated information for b851dab92141fd95f42e64a3d71dfa1510481eea, then you can go to https://clearlydefined.io/definitions/git/github/eclipse/kapua/b851dab92141fd95f42e64a3d71dfa1510481eea, make the edits and then submit.

Does that help?

**Comment by lorthirk** [comment]
Yes, definitely. I'll close this PR and submit a new one, probably after a license change version happens in the project (we're working towards a new release with EPL-2.0).

**Pull request closed without merging**
