### PR TITLE
heap 0.2.5

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
heap 0.2.5

**Details:**
Add NONE License

**Resolution:**
License Url: 
https://www.npmjs.com/package/storm-react-diagrams/v/5.2.1

Description:
We have used "storm-react-diagrams 5.2.1" npm package and package is come under the no license. Please see the following URL 
https://www.npmjs.com/package/storm-react-diagrams/v/5.2.1

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [heap 0.2.5](https://clearlydefined.io/definitions/npm/npmjs/-/heap/0.2.5)

### CODE REVIEW

**Comment by peggymoloney** [comment]
Files License in README.md is OTHER https://clearlydefined.io/file/b5c45c317769a2979f7308cbdb9dcc75165a5f48c260337610a179fb702c8f76

Landing Page License is NONE https://www.npmjs.com/package/heap/v/0.2.5

Repository License in README.md is OTHER https://github.com/qiao/heap.js

Package.json License is PSF https://github.com/qiao/heap.js

Curate as OTHER

**Comment by ariel11** [comment]
@peggymoloney - On this one, its a near match to "PSF.20" and the package.json says "PSF."  I am wondering if we can rely on matching guideline 2.1.3 here in that the only difference is the "name" - Python vs. Python 2.7.2.  Thoughts on using "PSF-2.0" for this - https://github.com/qiao/heap.js/tree/0.2.5#license, @capfei ?

**Review by ariel11 — APPROVED** [review]

**Review by ariel11 — APPROVED** [review]

**Comment by ariel11** [comment]
@nellshamrell  - checks still failing?

**Comment by nellshamrell** [comment]
@ariel11 - apologies, looks like the check is now passing after closing and re-opening :)

**Pull request merged**
