### PR TITLE
github.com/kisielk/gotool v1.0.0

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
github.com/kisielk/gotool v1.0.0

**Details:**
Add BSD-3-Clause AND MIT License

**Resolution:**
License Url:
 https://clearlydefined.io/file/25ad56f47146a8c6e502d5b1eefe145933b460a8b314bbb66bb7fc964b92298b 

Description:
 The legal file said match.go and match_test.go are BSD-3-Clause

**Affected definitions**:
- [gotool v1.0.0](https://clearlydefined.io/definitions/go/golang/github.com%2Fkisielk/gotool/v1.0.0/v1.0.0)

### CODE REVIEW

**Comment by MichaelTsengLZ** [comment]
@capfei Any chance to help me review these 14 Go component curations. I'm a little bit blocked by it.

[github.com/munnerz/goautoneg v0.0.0-20120707110453-a547fc61f48d](https://github.com/clearlydefined/curated-data/pull/20502)
[github.com/coreos/etcd v3.3.10+incompatible](https://github.com/clearlydefined/curated-data/pull/20501) 
[github.com/smartystreets/goconvey v1.6.4](https://github.com/clearlydefined/curated-data/pull/20500) 
[honnef.co/go/tools v0.0.1-2020.1.3](https://github.com/clearlydefined/curated-data/pull/20499) 
[github.com/coreos/go-semver v0.3.0](https://github.com/clearlydefined/curated-data/pull/20498) 
[github.com/smartystreets/assertions v0.0.0-20180927180507-b2de0cb4f26d](https://github.com/clearlydefined/curated-data/pull/20497) 
[github.com/coreos/pkg v0.0.0-20180928190104-399ea9e2e55f](https://github.com/clearlydefined/curated-data/pull/20496) 
[github.com/coreos/go-systemd v0.0.0-20190321100706-95778dfbb74e](https://github.com/clearlydefined/curated-data/pull/20495) 
[github.com/chzyer/logex v1.1.10](https://github.com/clearlydefined/curated-data/pull/20494) 
[github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910](https://github.com/clearlydefined/curated-data/pull/20493) 
[github.com/burntsushi/xgb v0.0.0-20160522181843-27f122750802](https://github.com/clearlydefined/curated-data/pull/20492) 
[github.com/kr/logfmt v0.0.0-20140226030751-b84e30acd515](https://github.com/clearlydefined/curated-data/pull/20491) 
[github.com/envoyproxy/protoc-gen-validate v0.1.0](https://github.com/clearlydefined/curated-data/pull/20490) 
[github.com/kisielk/gotool v1.0.0](https://github.com/clearlydefined/curated-data/pull/20489)

**Review by capfei — APPROVED** [review]

**Comment by capfei** [comment]
Declared license is MIT. It looks like BSD-3-Clause would fall under "Discovered".

**Comment by capfei** [comment]
@MichaelTsengLZ All of the PRs have been merged. 👍

**Comment by MichaelTsengLZ** [comment]
@capfei  Thank you so so much. This helps me a lot.

**Pull request merged**
