### PR TITLE
jQuery.BlockUI 2.70

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
jQuery.BlockUI 2.70

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/malsup/blockui#copyright-and-license

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [jQuery.BlockUI 2.70.0](https://clearlydefined.io/definitions/nuget/nuget/-/jQuery.BlockUI/2.70.0)

### CODE REVIEW

**Comment by TRQ3** [comment]
Looks like it should be curated as MIT OR AGPL 1.0-only. https://github.com/malsup/blockui/tree/2.70

**Comment by ariel11** [comment]
@TRQ3 - I think you meant "GPL" not "AGPL."  If I click on "GPL" here - https://github.com/malsup/blockui/tree/2.70#copyright-and-license - it takes me to GPL-2.0.  So, I think it is "MIT OR GPL-2.0-only."  Thoughts?

**Comment by ariel11** [comment]
@royaljust 
1) Tooling identified jquery.blockUI.js as "MIT OR GPL-1.0-or-later," though I do not see any reference to "1.0.
2) NuGet page has no license info, but links to Project Site - http://malsup.com/jquery/block/.  On that page, if you click on http://malsup.com/jquery/block/#download, you get the repo: https://github.com/malsup/blockui/.
3) In repo, tagged version: https://github.com/malsup/blockui/tree/2.70, has this statement: https://github.com/malsup/blockui/tree/2.70#copyright-and-license. The "GPL" link goes specifically to http://malsup.github.io/gpl-license-v2.txt.   So, version 2 of the license is specified. 
4) In addition, this file again links to the version 2 specific license - https://github.com/malsup/blockui/blob/2.70/blockUI.jquery.json.

So, conclusion is "MIT AND "GPL-2.0-only," as v2 specified.  Thoughts?

**Comment by royaljust** [comment]
@ariel11 - agree with your analysis. I was looking at the .js file itself, not the more canonical location of the readme link.

https://github.com/malsup/blockui/blob/2.70/jquery.blockUI.js

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
