### PR TITLE
webrtc-uwp/icu d888fd2a1be890f4d35e43f68d6d79f42519a357

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
webrtc-uwp/icu d888fd2a1be890f4d35e43f68d6d79f42519a357

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/webrtc-uwp/icu/blob/master/LICENSE

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [icu d888fd2a1be890f4d35e43f68d6d79f42519a357](https://clearlydefined.io/definitions/git/github/webrtc-uwp/icu/d888fd2a1be890f4d35e43f68d6d79f42519a357)

### CODE REVIEW

**Comment by mihouc** [comment]
License file link on Clearly Defined indicates license is OTHER
License file at source listed on Clearly Defined also indicates license is OTHER

License for package should be curated as OTHER

**Comment by AE49** [comment]
@mihouc The license files looks to be Unicode-DFS-2016 - https://spdx.org/licenses/Unicode-DFS-2016.html. Do you agree?

**Comment by mihouc** [comment]
@AE49 Is the inclusion of the top portion of the Unicode license required?

**Comment by AE49** [comment]
@mihouc The top portion of the Unicode-DFS-2016 seems applicable to Data Files. @ariel11 How would you curate this one?

**Comment by ariel11** [comment]
@AE49 and @mihouc - well, a strict application of the SPDX matching guidelines would make the curation "OTHER" because the text that is missing from this project's license file is not optional text, per https://spdx.org/licenses/Unicode-DFS-2016.html.  As noted above, this project's license file is missing the top half of the text:

image

Since we curate based on the SPDX matching guidelines, I think this would be "OTHER."

**Comment by AE49** [comment]
@mihouc I updated the yaml to "OTHER". You can approve and merge. @ariel11

**Review by mihouc — APPROVED** [review]

**Pull request merged**
