### PR TITLE
BotAuth 3.11.0-alpha

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
BotAuth 3.11.0-alpha

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/richdizz/botauth/blob/master/LICENSE

Description:
https://github.com/richdizz/botauth

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [BotAuth 3.11.0-alpha](https://clearlydefined.io/definitions/nuget/nuget/-/BotAuth/3.11.0-alpha)

### CODE REVIEW

**Comment by TRQ3** [comment]
1. No info in package files. 
2. I think I found the source repo, which is archived and without any versions. Though, it does show MIT. https://github.com/microsoftarchive/botauth/blob/master/LICENSE
3. Nuspec and downloaded files are not helpful with license info either. 

I'm a bit stumped here, leaning MIT.

**Comment by ariel11** [comment]
@TRQ3 - I agree with MIT based on what you found.  Thanks!

**Comment by ariel11** [comment]
@capfei - what do you think here? The NuGet package doesn't have any license info, however, @TRQ3 found the repo that appears to be correct for this project with a MIT license and the copyright matches the copyright on the package. See: https://github.com/microsoftarchive/botauth/blob/master/LICENSE.  Would you curate MIT for this package? I am hesitating because the package itself doesn't provide any license info or pointers to the repo @TRQ3 found. We could also raise on the March 1 community call?

Similar PR: https://github.com/clearlydefined/curated-data/pull/9636

**Comment by ariel11** [comment]
@TRQ3 - Per the notes on #9636, let's go with NONE.

**Review by TRQ3 — APPROVED** [review]

**Pull request merged**
