### PR TITLE
added Source location

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Incomplete

**Summary:**
added Source location

**Details:**
added source location

**Resolution:**
source location were missing, added them, incl. the commit hash for version 5.0.43

**Affected definitions**:
- [DotNetProjects.Wpf.Toolkit 5.0.43](https://clearlydefined.io/definitions/nuget/nuget/-/DotNetProjects.Wpf.Toolkit/5.0.43)

### CODE REVIEW

**Comment by ariel11** [comment]
There are not any tagged versions in the repo (https://github.com/dotnetprojects/WpfToolkit) and I do not see any reference to v5.0.43.  Unclear how the source link above was determined for this package?

**Comment by ariel11** [comment]
I can see the person curated the source URL using a commit with the same date (https://github.com/dotnetprojects/wpftoolkit/commit/6e05d7e451bd61ac8d1266f26317d26e692636a3) as the NuGet 'last updated' date (https://www.nuget.org/packages/DotNetProjects.Wpf.Toolkit/5.0.43) of July 28, 2017, but is that enough to confirm this is the right source URL for that NuGet package?

**Comment by pombredanne** [comment]
@jogibear9988 this is your code ... we are trying to match a NuGet release to a commit in your repo for clarity... is this something you could help us with? There are no tags in Git to help there.

**Comment by jogibear9988** [comment]
don‘t know how! the release numbers are generated from appveyor on each commit.
atm i do not generate github releases. why isnt the source hash enough?

**Comment by pombredanne** [comment]
@jogibear9988 thank you for chiming in!
What we are trying to do here is simply confirm that this commit dotnetprojects/WpfToolkit@6e05d7e corresponds to the source code used to build this released  NuGet https://www.nuget.org/packages/DotNetProjects.Wpf.Toolkit/5.0.43

Since there is no tag in your repo there is no obvious way to match a Nuget release to its exact corresponding sources. And we could not find either some hints  in the commit stream beyond the commit date. 

Is there a link to your appveyor page that could help may be? Or some other clue?

**Comment by jogibear9988** [comment]
for the newest nugets we have sourcelink support.

the one you name is replaced by 4 new ones

**Comment by jogibear9988** [comment]
but nuget dors not support deprecation of packages (as I know)

**Comment by ariel11** [comment]
My understanding from the above is we cannot assume this commit (https://github.com/dotnetprojects/wpftoolkit/commit/6e05d7e451bd61ac8d1266f26317d26e692636a3) is the right one for the DotNetProjects.Wpf.Toolkit 5.0.43 NuGet package.  I will close this PR.

**Pull request closed without merging**
