### PR TITLE
Update file licenses

### PR DESCRIPTION
**Pull request by waynebeaton**
**Type:** Incorrect

**Summary:**
Update file licenses

**Details:**
The discovered licenses on the text-based files are not correct.

**Resolution:**
Update the licenses.

**Affected definitions**:
- [javax.servlet-api 3.1.0](https://clearlydefined.io/definitions/maven/mavencentral/javax.servlet/javax.servlet-api/3.1.0/3.1.0)

### CODE REVIEW

**Comment by waynebeaton** [comment]
I just noticed that I missed the pom.xml file (CDDL-1.0 OR GPL-2.0-only WITH Classpath-exception-2.0)

What's the preferred means of addressing that? Update this PR, or submit a follow up?

**Comment by bduranc** [comment]
> I just noticed that I missed the pom.xml file (CDDL-1.0 OR GPL-2.0-only WITH Classpath-exception-2.0)
> 
> What's the preferred means of addressing that? Update this PR, or submit a follow up?

In some cases, I've noticed the individual who is approving the request will make a change.

@ariel11 might be able to advise better.

**Comment by ariel11** [comment]
Thanks, @waynebeaton for this curation.  Thanks, @bduranc for looping me in.  Yes, I will make minor updates to curations.  For example here,  I added "All rights reserved." to the end of the copyright statements that had that.  I also deleted the copyrights on the License.txt file because those are part of the license, not author copyrights.  But I do not add a whole new curation.  If you would like to submit a curation for a new file, please do a new contribution, so we can follow the process of having one person submit the curation and a second person review it.  Thank you very much!

**Comment by ariel11** [comment]
@geneh - Can you please look into the failed checks?  Thank you!

**Comment by ariel11** [comment]
@geneh - Can you please look into the failed checks? Thank you!

**Comment by geneh** [comment]
Done

**Pull request merged**
