### PR TITLE
supermassive-todomvc 1.0.1-0

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
supermassive-todomvc 1.0.1-0

**Details:**
Add MIT License

**Resolution:**
License Url:
https://github.com/microsoft/graphitation/blob/main/LICENSE

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [supermassive-todomvc 1.0.1-0](https://clearlydefined.io/definitions/npm/npmjs/-/supermassive-todomvc/1.0.1-0)

### CODE REVIEW

**Comment by capfei** [comment]
If I'm reading this correctly, then it looks like this package shouldn't have been published publicly: https://github.com/microsoft/graphitation/pull/154

I found this repo through the other packages, not this one. All of the other packages in the `example` folder have not been published and the package.json still lists it as a private package. Was MIT added last week because this was published accidentally a couple of years ago?

@ariel11 @AE49 What do you think? MIT or NONE?

**Comment by ariel11** [comment]
@capfei - well, if we go with what license information was provided in/for the package at the time it was (mistakenly) published, it would be "NONE," so I would recommend going with that.

**Comment by LSDima** [comment]
@capfei, @ariel11 I've added MIT as a license here because we got a [Security Alert in our Pipeline Component Governance](https://dev.azure.com/DomoreexpGithub/Github_Pipelines/_componentGovernance/214173/alert/8486068?typeId=16752842). I'll post below de description in case you don't have access to that: 

>Description
To validate the use of open source, Component Governance needs additional license information. Our tooling depends on the publicly accessible open source database [ClearlyDefined](https://clearlydefined.io/) for this information, and ClearlyDefined does not have information for this component. This is a rare occurrence, and requires input from you.
>
>Please provide:
>
>The license for this component;
>A url to the license for this component;
>Optionally, describe why you think this is the license for this component.
>When you click "submit" Component Governance will automatically create a pull request in [ClearlyDefined](https://clearlydefined.io/) for the ClearlyDefined open source community to review according to these guidelines - [ClearlyDefined Review Guidelines](https://docs.clearlydefined.io/data-curation).
>
>With your submission please keep in mind ClearlyDefined community members are not Microsoft employees, and donate their time when reviewing submissions.

If MIT is not the proper license, please help us figure out which one is as MIT is the only one I could find inside the package.

**Comment by ariel11** [comment]
> @capfei, @ariel11 I've added MIT as a license here because we got a [Security Alert in our Pipeline Component Governance](https://dev.azure.com/DomoreexpGithub/Github_Pipelines/_componentGovernance/214173/alert/8486068?typeId=16752842). I'll post below de description in case you don't have access to that:
> 
> > Description
> > To validate the use of open source, Component Governance needs additional license information. Our tooling depends on the publicly accessible open source database [ClearlyDefined](https://clearlydefined.io/) for this information, and ClearlyDefined does not have information for this component. This is a rare occurrence, and requires input from you.
> > Please provide:
> > The license for this component;
> > A url to the license for this component;
> > Optionally, describe why you think this is the license for this component.
> > When you click "submit" Component Governance will automatically create a pull request in [ClearlyDefined](https://clearlydefined.io/) for the ClearlyDefined open source community to review according to these guidelines - [ClearlyDefined Review Guidelines](https://docs.clearlydefined.io/data-curation).
> > With your submission please keep in mind ClearlyDefined community members are not Microsoft employees, and donate their time when reviewing submissions.
> 
> If MIT is not the proper license, please help us figure out which one is as MIT is the only one I could find inside the package.

@LSDima - this is a public open source project. Please contact your internal support if you have license or security questions. As for the curation of this component, ClearlyDefined simply reports the license info provided with/in the package. Where did you find MIT inside this package?

**Comment by LSDima** [comment]
> > If MIT is not the proper license, please help us figure out which one is as MIT is the only one I could find inside the package.
> 
> @LSDima - this is a public open source project. Please contact your internal support if you have license or security questions. As for the curation of this component, ClearlyDefined simply reports the license info provided with/in the package. Where did you find MIT inside this package?

Very sorry, I've meant the repo, not the package: https://github.com/microsoft/graphitation/blob/main/LICENSE.

**Comment by freiksenet** [comment]
Hi! I'm the maintainer of the repository. The whole repository is licensed as MIT, therefore examples are MIT too, even if it's not published.

**Comment by ariel11** [comment]
@freiksenet - OK, great - with your confirmation that you meant for the **[published NPM package]** (https://www.npmjs.com/package/supermassive-todomvc/v/1.0.1-0) to also be MIT licensed (as the published _package_ has no license  information at all or a link back to the project repo), we can add "MIT" for the package to this public license repository (ClearlyDefined). @capfei - FYI on the license confirmation from the project maintainer. Thanks!

**Review by capfei — APPROVED** [review]

**Pull request merged**
