### PR TITLE
BotAuth.AADv1 3.11.0-alpha

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
BotAuth.AADv1 3.11.0-alpha

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/richdizz/botauth/blob/master/LICENSE

Description:
That's the github repo: https://github.com/richdizz/botauth and the MIT license is there.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [BotAuth.AADv1 3.11.0-alpha](https://clearlydefined.io/definitions/nuget/nuget/-/BotAuth.AADv1/3.11.0-alpha)

### CODE REVIEW

**Comment by TRQ3** [comment]
1. No info in package files.
2. I think I found the source repo, which is archived and without any versions. Though, it does show MIT. https://github.com/microsoftarchive/botauth/blob/master/LICENSE
3. Nuspec and downloaded files are not helpful with license info either.

I'm a bit stumped here, leaning MIT.

**Comment by ariel11** [comment]
@capfei - what do you think here?  The NuGet package doesn't have any license info, however, @TRQ3 found the repo that appears to be correct for this project with a MIT license and the copyright matches the copyright on the package.  See: https://github.com/microsoftarchive/botauth/blob/master/Node/examples/aadv1/package.json (the package _versions_ do not match though) and https://github.com/microsoftarchive/botauth/blob/master/LICENSE.  Would you curate MIT for this package?  I am hesitating because the package itself doesn't provide any license info or pointers to the repo @TRQ3 found.  We could also raise on the March 1 community call?

Similar PR: https://github.com/clearlydefined/curated-data/pull/9637

**Comment by capfei** [comment]
@ariel11 It looks like the NuGets are under the CSharp folder, not Node. Looking at the history, the code for this wasn't added until September 2017.

I'm leaning to NONE since there is nothing in the package itself that points to this repo or license. The NPM package declares a license and includes a license file. None of the NuGets do so I would argue that it could be a case of source is MIT but the NuGet isn't. Maybe because all of the versions are alpha that they aren't licensed.

**Comment by capfei** [comment]
I would say the same for #9637.

**Comment by ariel11** [comment]
@TRQ3 - Per the above, let's go with NONE.

**Review by TRQ3 — APPROVED** [review]

**Pull request merged**
