### PR TITLE
foo 1.0.0

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
foo 1.0.0

**Details:**
Add Apache-2.0 License

**Resolution:**
License Url: 
https://github.com/elastic/kibana/blob/master/LICENSE.txt

Description:
All sources except "x-pack" folder is  under Apache 2.0 license. "x-pack" folder source code in a given file is licensed under the
Elastic License

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [foo 1.0.0](https://clearlydefined.io/definitions/npm/npmjs/-/foo/1.0.0)

### CODE REVIEW

**Comment by TRQ3** [comment]
1. No info in package files. 
2. Source repo points  to ISC license in package.json, but does not have any license language. Source repo also doesn't have any more license clarity in any other files.  https://github.com/jasonLaster/foo/blob/master/package.json
3. NPM registry also unhelpful with silence on license issue. http://registry.npmjs.com/foo/1.0.0

Would you go with NONE on this one, @ariel11?

**Comment by ariel11** [comment]
@TRQ3 - I am not sure if this is a real package.  The package.json for this version of the package points to a different repo than more recent packages. This version 1.0.0 points to github.com/coolaj86/node-pakman, while the more recent packages point to github.com/jasonLaster/foo.  There doesnt seem to be much of anything in this package.

@capfei  - do you have any insights or thoughts about this package?  Is it a "real" package or something just used for test purposes, maybe?

**Comment by capfei** [comment]
@ariel11 It does look like a test or demo package. I would curate as NONE.

**Comment by ariel11** [comment]
@TRQ3 - I updated the "Files changed" to NONE.  Thanks!

**Review by TRQ3 — APPROVED** [review]

**Pull request merged**
