### PR TITLE
com.github.jsonld-java:jsonld-java 0.12.5

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
com.github.jsonld-java:jsonld-java 0.12.5

**Details:**
Add BSD-3-Clause License

**Resolution:**
License Url: 
https://github.com/jsonld-java/jsonld-java/blob/master/LICENCE

Description:
Github website

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [jsonld-java 0.12.5](https://clearlydefined.io/definitions/maven/mavencentral/com.github.jsonld-java/jsonld-java/0.12.5)

### CODE REVIEW

**Comment by TRQ3** [comment]
1. No info in package files. 
2. Pom file is silent on license. 
3. Sources jar is silent on license. 

Would curate as NONE.

**Comment by ariel11** [comment]
This appears to the repo the maven comes from:  https://github.com/jsonld-java/jsonld-java/blob/v0.12.5/LICENCE.   I think we can curate BSD-3-Clause here.  @royaljust - do you agree?

**Comment by ariel11** [comment]
Tagging @capfei to take a look at the above.  Thanks!

**Comment by capfei** [comment]
@ariel11 Yes, I agree with BSD-3-Clause. I was able to find this repo in the source code files.

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
