### PR TITLE
HdrHistogram 2.5.0

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
HdrHistogram 2.5.0

**Details:**
Add BSD-2-Clause License

**Resolution:**
License Url: 
https://github.com/HdrHistogram/HdrHistogram.NET/blob/master/LICENSE.txt

Description:
You can find the repository url in nuget manager which has the license.

This is the dependency of NBomber which has the following license information:

https://github.com/PragmaticFlow/NBomber/blob/master/LICENSE
Apache li 2.0

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [HdrHistogram 2.5.0](https://clearlydefined.io/definitions/nuget/nuget/-/HdrHistogram/2.5.0)

### CODE REVIEW

**Comment by TRQ3** [comment]
1. No info in package files. 
2. Source repo for commit shows BSD 2 Clause. https://github.com/HdrHistogram/HdrHistogram.NET/blob/9d82f46d3abfd07d20df901e3fbcf015a8baf665/LICENSE.txt
3. Nuspec points to BSD 2 Clause. https://raw.githubusercontent.com/HdrHistogram/HdrHistogram.NET/master/LICENSE.txt

Agree with the above. Should be curated as BSD 2 Clause.

**Comment by ariel11** [comment]
@TRQ3 - Because of the language at the [top of the LICENSE file](https://github.com/HdrHistogram/HdrHistogram.NET/blob/9d82f46d3abfd07d20df901e3fbcf015a8baf665/LICENSE.txt) (rows 1-12), I would suggest the curation be "CC0-1.0 OR BSD-2-Clause."  Do you agree?

**Comment by TRQ3** [comment]
@ariel11 I do. Thanks for the clarity.

**Comment by ariel11** [comment]
@TRQ3 - OK, I updated the "Files changed" tab.  Thanks!

**Review by TRQ3 — APPROVED** [review]

**Pull request merged**
