### PR TITLE
@microsoft/sp-property-pane 1.19.0

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
@microsoft/sp-property-pane 1.19.0

**Details:**
Add OTHER License

**Resolution:**
License Url:
https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Funpkg.com%2F%40microsoft%2Fsp-core-library%401.8.2%2FEULA%2FMicrosoft%2520Sharepoint%2520Framework%2520-%2520Standalone%2520(free)%2520Use%2520Terms.docx&wdOrigin=BROWSELINK

Description:
sp-property-pane package supports development of client-side components (e.g. web parts, client-side extensions, and applications) built using the SharePoint Framework.  This package is part of the SharePoint Framework.

We have received license information from below Microsoft website:

https://learn.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-framework-overview?WT.mc_id=m365-15744-cxa

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [sp-property-pane 1.19.0](https://clearlydefined.io/definitions/npm/npmjs/@microsoft/sp-property-pane/1.19.0)

### CODE REVIEW

**Review by capfei — APPROVED** [review]

**Comment by v-ravranjan** [comment]
Hello @capfei,
We have provided all the missing legal information for this legal alert, and it has been approved and completed on your side. Although you completed this alert 48 hours ago, it still has not been removed from my repository's Active Alerts list. Please help me remove this legal alert from my repository.

Alert URL: https://onegdc.visualstudio.com/OneGDC/_componentGovernance/Events%20Menu/alert/11382815?typeId=25397643&pipelinesTrackingFilter=0

image

Thanks,
Ravi

**Comment by v-ravranjan** [comment]
@capfei , @clearlydefinedbot Any update on this.

**Comment by capfei** [comment]
@v-ravranjan 🤷‍♀️ Contact CG support? I help with ClearlyDefined, not CG, so I have no clue if this is an issue or not.

**Comment by v-ravranjan** [comment]
@capfei Please provide CG support email ID.

**Comment by mpcen** [comment]
@capfei I took a look at the definition in clearlydefined found here: https://clearlydefined.io/definitions/npm/npmjs/@microsoft/sp-property-pane/1.19.0

it's showing declared as NOASSERTION. Is this correct?

**Comment by capfei** [comment]
@mpcen No, it isn't. I got it update and is now correctly showing "OTHER".

**Pull request merged**
