### PR TITLE
unicode-org/icu e2d85306162d3a0691b070b4f0a73e4012433444

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
unicode-org/icu e2d85306162d3a0691b070b4f0a73e4012433444

**Details:**
Add ICU License

**Resolution:**
License Url: 
https://github.com/unicode-org/icu/blob/e2d85306162d3a0691b070b4f0a73e4012433444/icu4c/LICENSE

Description:
The README.md shows the license file should be ./icu4c/LICENSE
"Please see ./icu4c/LICENSE (C and J are under an identical license file.)"

Link to the statement:
https://github.com/unicode-org/icu/tree/e2d85306162d3a0691b070b4f0a73e4012433444#license

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [icu e2d85306162d3a0691b070b4f0a73e4012433444](https://clearlydefined.io/definitions/git/github/unicode-org/icu/e2d85306162d3a0691b070b4f0a73e4012433444)

### CODE REVIEW

**Comment by AE49** [comment]
@capfei There is a small change to this license to add "Data Files". Would you still curate as ICU?

https://github.com/unicode-org/icu/blob/e2d85306162d3a0691b070b4f0a73e4012433444/icu4c/LICENSE

**Comment by capfei** [comment]
@AE49 I have asked about this license in Discord and haven't gotten a response yet. I'm not sure how to curate this one since it doesn't quite match ICU, but does match the Data Files license verbiage, but is missing the first 4 sentences. ☹️

**Comment by jefgen** [comment]
Hello!

I just opened a PR for ICU as well over here just now: https://github.com/clearlydefined/curated-data/pull/7529

I wonder if perhaps you might be able to review that as well?

FWIW, I think that perhaps the two PRs could somehow be combined, as the license for ICU has not changed much since ICU version 58.

Thank you!

**Comment by yelu** [comment]
What else we could do to have this approved? @capfei

**Comment by jefgen** [comment]
> What else we could do to have this approved? @capfei 

Hello! I'd also like to know what else can be done to help get this (and also PR #7529) approved as well.
Thank you! :)

**Comment by jefgen** [comment]
> @capfei: I'm not sure how to curate this one since it doesn't quite match ICU, but does match the Data Files license verbiage, but is missing the first 4 sentences.

FWIW, the ICU project changed their license in 2016 when they became part of the Unicode Consortium. I wonder if the "ICU" license you mentioned is perhaps the older IBM ICU license maybe, and that's why it is different? (Just wondering maybe).

On the other PR, when looking at the new license, I was sort of thinking that the new license terms for ICU (as part of the Unicode Consortium) might be this:
"`Unicode-DFS-2016 AND BSD-3-Clause AND BSD-2-Clause License`"
due to the various other parts that are included.

What do you think?

Thanks!

**Comment by capfei** [comment]
@AE49 Based this information, I would curate this as Unicode-DFS-2016.

**Comment by jefgen** [comment]
> @AE49 Based this information, I would curate this as Unicode-DFS-2016.

Thank you very much both @capfei and @ariel11 for all your help with this, and for reviewing both this PR and the other ICU-related PR (#7529) as well. :+1: 

Thank you! :)

**Review by AE49 — APPROVED** [review]

**Comment by ariel11** [comment]
@AE49 - you should be able to merge now.  Thanks

**Pull request merged**
