### PR TITLE
clang 14.0

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
clang 14.0

**Details:**
Add Apache-2.0 License

**Resolution:**
License Url: 
https://www.llvm.org/docs/DeveloperPolicy.html#open-source-licensing-terms

Description:
clang is a subproject of LLMV, which falls under same license terms

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [clang 14.0](https://clearlydefined.io/definitions/pypi/pypi/-/clang/14.0)

### CODE REVIEW

**Comment by AE49** [comment]
@capfei I think this should be Declared as Apache-2.0 WITH LLVM-exception. What do you think?

https://github.com/llvm-mirror/clang/blob/master/bindings/python/clang/__init__.py

**Comment by capfei** [comment]
@AE49 I thought this was an official package but it isn't. I was desperately looking for this package in the LLVM repo and missed in the description that this is redistributed code. 🤦‍♀️ 
> This is a non-official packaging directly from the debian packages for the purpose of pypi package.

I found a source repo by looking at an older version: https://pypi.org/project/clang/3.7/. It has a travis-ci link which has a GitHub repo. I didn't see any actual LLVM files in the repo so I'm guessing it really does pull in the contents, repackage, then publish to pypi.
https://travis-ci.org/trolldbois/python-clang --> https://github.com/trolldbois/python-clang

I saw in LLVM license, https://llvm.org/LICENSE.txt, at the bottom is has a portion for legacy license (NCSA). That has a link to https://llvm.org/docs/DeveloperPolicy.html#legacy that says that NCSA is still an option until they complete their relicensing efforts. I'm assuming since information continuing the relicensing efforts that it is still in progress. 🤷‍♀️ 

> The code base was previously licensed under the Terms described here. We are in the middle of relicensing to a new approach (described above), but until this effort is complete, the code is also still available under these terms. Once we finish the relicensing project, new versions of the code will not be available under these terms. However, nothing takes away your right to use old versions under the licensing terms under which they were originally released.

With all of this, I'm comfortable going with NCSA.

@ariel11 What do you think?

**Comment by capfei** [comment]
Opened an issue with the package author for license clarification.
https://github.com/trolldbois/python-clang/issues/16

**Comment by capfei** [comment]
The author stated that the license is the from clang so Apache with LLVM. @AE49 Can you update the other versions except 5.0?

Also, I submitted a PR to get the setup.py details updated with the current license. Hopefully, it will be accepted and clear up any future confusion.

**Review by AE49 — APPROVED** [review]

**Pull request merged**
