### PR TITLE
opts 1.2.6

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
opts 1.2.6

**Details:**
Add BSD-2-Clause License

**Resolution:**
License Url: 
https://github.com/khtdr/opts/blob/master/LICENSE.txt

Description:
It's on their repo

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [opts 1.2.6](https://clearlydefined.io/definitions/npm/npmjs/-/opts/1.2.6)

### CODE REVIEW

**Comment by mihouc** [comment]
opts.js file on Clearly Defined indicates license is BSD-2
No license information in NPM registry
License information in repository is after this version, but that license is BSD-2

License for package should be curated as BSD-2

**Comment by ariel11** [comment]
@capfei  - this one is interesting.  The [opts.js file](https://clearlydefined.io/file/a1ee7e717cbf07f02766f2e5e3dd527e734351faf8455b04627fa650f552e181) has the "BSD-2-Clause-Views” license, while the repo license is standard “BSD-2-Clause.”  And the repo license is from the same date and this package.  For this package, would you go with the license info on the opts.js file or the repo for the "declared" license?

**Comment by capfei** [comment]
@ariel11 Looking at the repo when the package was published, I don’t see a license file. The license file was added this year and this version was published in 2017. I would go with BSD-2-Clause-views since that is the only license information I can find.

**Comment by ariel11** [comment]
@capfei  - thanks!
@mihouc - I updated the "Files changed" tab to BSD-2-Clause-Views.  Good catch!

**Review by mihouc — APPROVED** [review]

**Pull request merged**
