### PR TITLE
py-ms 2.4.0

### PR DESCRIPTION
**Pull request by LandOfBliss**
**Type:** Missing

**Summary:**
py-ms 2.4.0

**Details:**
PyPi indicates GPLv3
ClearlyDefined PACKAGE-INFO indicates GPLv3
Curation guidelines #10

**Resolution:**
GPL-3.0-or-later

**Affected definitions**:
- [py-ms 2.4.0](https://clearlydefined.io/definitions/pypi/pypi/-/py-ms/2.4.0/2.4.0)

### CODE REVIEW

**Comment by capfei** [comment]
@LandOfBliss Can you point me to where it states "or later"? I checked several files but could not find anything that states it.

**Comment by LandOfBliss** [comment]
@capfei I did not find evidence of "only" or "or later".  So, followed the curation guidelines #10.

**Comment by capfei** [comment]
@LandOfBliss Ok, then without any references to "or later" then this should "GPL-3.0-only" since it is stated to be GPLv3. The only time we would default "or later" is if the only license information we have is just "GPL" and no version, which we would then use GPL-1.0-or-later.

Do you agree?

**Comment by ariel11** [comment]
Agree with "GPL-3.0-only."

**Review by capfei — APPROVED** [review]

**Pull request merged**
