### PR TITLE
vsda 1.4.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
vsda 1.4.1

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://opensource.org/licenses/MIT

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [vsda 1.4.1](https://clearlydefined.io/definitions/npm/npmjs/-/vsda/1.4.1)

### CODE REVIEW

**Comment by capfei** [comment]
I can't find where it states MIT. The package no longer exists on NPMJS and I can't view the README on the CD site. 
The package.json lists the source as https://github.com/microsoft/vscode but I can't find the package there. I did find this issue where someone asked where the package was in the source and the response was the vsda package is only the VSCode product, not the code.
https://github.com/microsoft/vscode/issues/72885#issuecomment-487714320

If that is the case, then shouldn't be either curated as either `NONE` (since there is no license info) or `OTHER` since it is apart of the VSCode product, which is under a EULA.
https://code.visualstudio.com/license?lang=en

I'm leaning towards `OTHER` but would like other people's opinions.

**Comment by ariel11** [comment]
@capfei - Interesting.  I would agree with "OTHER" based on the Issue you found (saying this package is only made available in the EULA-licensed version of VS Code).

**Comment by Chuxel** [comment]
@ariel11 @capfei Yeah, this is MS licensed code for VS Code "distro" - it's not MIT.

**Comment by capfei** [comment]
Thanks, @ariel11 and @Chuxel! I have updated the PR.

**Pull request merged**
