### PR TITLE
boost_locale-vc141 1.70.0.0

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
boost_locale-vc141 1.70.0.0

**Details:**
Add BSL-1.0 License

**Resolution:**
License Url: 
https://www.boost.org/users/license.html

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [boost_locale-vc141 1.70.0](https://clearlydefined.io/definitions/nuget/nuget/-/boost_locale-vc141/1.70.0)

### CODE REVIEW

**Comment by LandOfBliss** [comment]
Looked in the "Files" section on the ClearlyDefined definition.  Downloaded Nuspec file includes link to Apache-2.0 license
Nuget license field links to Apache-2.0 license
Source code project includes Apache-2.0 license
Conclusion:  Declared license is Apache-2.0 license

**Comment by ariel11** [comment]
@LandOfBliss - I agree with Apache-2.0 here, though a different version was curated differently, so just making sure I am not missing something - @capfei?  Or should 1.67.0 be updated to "Apache-2.0," as well?

**Comment by capfei** [comment]
@ariel Yes, this should be updated to Apache 2.0.

**Review by ariel11 — APPROVED** [review]

**Comment by ariel11** [comment]
> @ariel Yes, this should be updated to Apache 2.0.

@capfei - Great!  I updated both versions on the yaml

**Pull request merged**
