### PR TITLE
xamarin/macios-binaries d33e206ce7978d2ec0019989a1add727c87ea1cf

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
xamarin/macios-binaries d33e206ce7978d2ec0019989a1add727c87ea1cf

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/xamarin/xamarin-macios/blob/main/LICENSE

Description:
macios-binaries (https://github.com/xamarin/macios-binaries) is is a secondary build module for xamarin-macios (https://github.com/xamarin/xamarin-macios) and the parent repo is MIT

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [macios-binaries d33e206ce7978d2ec0019989a1add727c87ea1cf](https://clearlydefined.io/definitions/git/github/xamarin/macios-binaries/d33e206ce7978d2ec0019989a1add727c87ea1cf)

### CODE REVIEW

**Comment by mihouc** [comment]
No obvious license information on Clearly Defined
No license information in repository, which indicates it is a secondary build module for Xamarin.Mac
License file in repository for main module is MIT

**Comment by ariel11** [comment]
@mihouc opened an Issue at the repo - https://github.com/xamarin/macios-binaries/issues/37

**Comment by ariel11** [comment]
It's been over 7 days and no response on the above PR.  Think we should merge this PR with "NONE" as the declared license.   Do you agree @capfei?

**Comment by capfei** [comment]
@ariel11 Yeah, I agree with NONE.

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
