### PR TITLE
Antlr2.Runtime 2.7.7.02

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
Antlr2.Runtime 2.7.7.02

**Details:**
Add ANTLR-PD License

**Resolution:**
License Url: 
https://www.antlr2.org/license.html

Description:
This is the link to the license, and they have there own special license

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [Antlr2.Runtime 2.7.7.2](https://clearlydefined.io/definitions/nuget/nuget/-/Antlr2.Runtime/2.7.7.2)

### CODE REVIEW

**Comment by mihouc** [comment]
License link on Nuget site (https://www.antlr2.org/license.html) indicates license is ANTLR-PD. That link is also the license link on the project home page.

License should be curated as ANTLR-PD

**Comment by ariel11** [comment]
@mihouc - It looks like only the two top paragraphs of the license file match the ANTLR-PD SPDX license text.  The authors also grant a copyright license under any OSI-approved license.  So, I think this would be “ANTLR-PD OR OTHER.”  Thoughts?  We can also ask @capfei  for a second opinion.  Thanks!

**Comment by mihouc** [comment]
@ariel11 - I agree with your analysis, but to be precise the condition precedent for "copyright license under any OSI-approved license" requires use in countries where the Public Domain status of the work may not be valid.

**Comment by capfei** [comment]
@ariell11 @mihouc I would curate this as ANTLR-PD OR OTHER since they did add the option to pick any OSI-approved license in countries that do not recognize Public Domain.

**Comment by ariel11** [comment]
@mihouc - I updated the "Files changed" tab so it's ready to merge.  Thanks!

**Review by mihouc — APPROVED** [review]

**Pull request merged**
