### PR TITLE
pythonx86 3.9.0-a4

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
pythonx86 3.9.0-a4

**Details:**
Add PSF-2.0 License

**Resolution:**
License Url: 
https://docs.python.org/license.html

Description:
I am a core Python developer and work on this project.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [pythonx86 3.9.0-a4](https://clearlydefined.io/definitions/nuget/nuget/-/pythonx86/3.9.0-a4)

### CODE REVIEW

**Comment by zooba** [comment]
This is definitely the correct Python license, and I don't see why all the other entries in this file aren't the same.

**Comment by capfei** [comment]
@zooba The reason the other versions are OTHER is because the Python license that includes the multiples licenses in it has differences that make it not a match to what SPDX and OSI have listed for the Python-2.0 license.
https://spdx.org/licenses/Python-2.0.html 

PSF-2.0 is only the Python 2.0 portion: https://spdx.org/licenses/PSF-2.0.html.

There is an open issue with SPDX to get the current license text used by Python an identifier. It is still weird for me to use OTHER for Python, but since we adhere to the [SPDX matching guidelines](https://spdx.dev/license-list/matching-guidelines/), it is OTHER. The same for #17618; that will be updated to OTHER.

Discussion: https://github.com/spdx/license-list-XML/issues/1200

**Comment by ariel11** [comment]
Agree that this license - https://www.nuget.org/packages/pythonx86/3.9.0-a4/License - does not have an SPDX identifier.  There are ones that are close, like the SPDX "Python-2.0," however the differences between that SPDX license template and the above package license does not meet the SPDX matching guidelines.  Therefore, like other licenses that do not have a matching SPDX identifier, the declared license is entered as "OTHER."

**Comment by zooba** [comment]
Eh, OTHER is fine enough by me. I just want the misdetection on my build to stop complaining - I'm not actually _using_ the component.

**Review by ariel11 — APPROVED** [review]

**Pull request merged**
