### PR TITLE
supervisor 4.2.2

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
supervisor 4.2.2

**Details:**
Add ZPL-2.1 License

**Resolution:**
License Url: 
http://www.repoze.org/LICENSE.txt

Description:
Found the license details of supervisor package on https://pypi.org/project/supervisor/

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [supervisor 4.2.2](https://clearlydefined.io/definitions/pypi/pypi/-/supervisor/4.2.2)

### CODE REVIEW

**Review by capfei — APPROVED** [review]

**Review by capfei — APPROVED** [review]

**Comment by capfei** [comment]
License in the included package states BSD-3-Clause-Modification, as well as the source repo. Updated. https://github.com/Supervisor/supervisor/blob/4.2.2/LICENSES.txt

**Comment by capfei** [comment]
@MichaelTsengLZ  Can you merge this please? This is a valid license; bot is out of date.

**Comment by MichaelTsengLZ** [comment]
This got merge conflict when I merged this [PR](https://github.com/clearlydefined/curated-data/pull/20656#event-7083333303). Could you please solve it and then notice me to merge it again?

**Comment by capfei** [comment]
@MichaelTsengLZ Resolved! Thank you 😃

**Pull request merged**
