### PR TITLE
Added the Source and License for ApacheOrcDotNet 1.0.0

### PR DESCRIPTION
**Pull request by alkent**
**Type:** Missing

**Summary:**
Added the Source and License for ApacheOrcDotNet 1.0.0

**Details:**
Source and license data was missing for ApacheOrcDotNet.

**Resolution:**
Source and license data was added.
License was here: https://github.com/ddrinka/ApacheOrcDotNet/blob/master/LICENSE

**Affected definitions**:
- [ApacheOrcDotNet 1.0.0](https://clearlydefined.io/definitions/nuget/nuget/-/ApacheOrcDotNet/1.0.0/1.0.0)

### CODE REVIEW

**Comment by alkent** [comment]
Woops, misclicked the close button.

**Comment by capfei** [comment]
@alkent I'm not able to verify that this is the source for this package. 

I was not able to find this repo referenced in the package. I was unable to find any source information, at least from my looking. The NuGet package publisher account is different. I could not verify that the NuGet package publisher, 'dhinkebein', is the same as the GitHub user 'ddrinka'.

The source commit ID you provided is from 2021; this version was published in 2020. Maybe I missed it, but I couldn't locate the commit ID for version 1.0.0.

This may be repackaged code that was published for their own use and I am unable to verify if changes were made.

With that, I'm not confident in merging this as the source location information for this package and recommend closing this PR.

Do you agree?

**Comment by alkent** [comment]
Looking back through the commit history in github, it does not look like it was started from a fork.
If this is the same package, it is the original.
Initial commit * ***@***.*** (github.com)<https://github.com/ddrinka/ApacheOrcDotNet/commit/0ca1cc8f3fb1033895ad4909d8e76b355665d8ed>
It is described as a port for Apache ORC file format in C#.

I've been given the task to update this information. I cannot close it until I complete it.
The alternative would be to use a different package with full license information. Which doesn't exist.

**Comment by ariel11** [comment]
Per the above recommendation, closing this PR.  Thank you!

**Pull request closed without merging**
