### PR TITLE
fmtlib/fmt 4fe0b11195b7cd71f39253c44db2c9dddf6b82d4

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
fmtlib/fmt 4fe0b11195b7cd71f39253c44db2c9dddf6b82d4

**Details:**
Add NONE License

**Resolution:**
License Url: 
https://github.com/fmtlib/fmt/blob/master/LICENSE.rst

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [fmt 4fe0b11195b7cd71f39253c44db2c9dddf6b82d4](https://clearlydefined.io/definitions/git/github/fmtlib/fmt/4fe0b11195b7cd71f39253c44db2c9dddf6b82d4)

### CODE REVIEW

**Comment by LandOfBliss** [comment]
Looked in ClearlyDefined files.  License file is MIT
The ClearlyDefined version links to GitHub source location
Readme file indicates MIT
Source project license is MIT
Conclusion:  Declared license is MIT

**Comment by ariel11** [comment]
@LandOfBliss - On these ones, we've done "MIT WITH OTHER."  We used the SPDX "WITH" operator to capture the license exception and then did "OTHER" because there's not a SPDX match for that particular license exception.

**Review by ariel11 — APPROVED** [review]

**Review by ariel11 — APPROVED** [review]

**Comment by ariel11** [comment]
@nellshamrell , @capfei , @royaljust - what do we do when we want to use a SPDX "like" expression because that's as close as we can get?

Here, there is no SPDX for the license exception, so we are using with the SPDX "WITH" operator and then doing "WITH OTHER."

**Comment by capfei** [comment]
@ariel11 I think the bot needs some tweaking since I still have open PRs that are failing even though all of the licenses are valid identifiers.

**Review by ariel11 — APPROVED** [review]

**Comment by ariel11** [comment]
We decided to stop using "WITH" with "OTHER."  We will follow the SPDX matching guidelines, which says if there's extra license text, we will not use the SPDX identifier.  So, this just becomes OTHER.

**Pull request merged**
