### PR TITLE
NETStandard.Library.NETFramework 2.0.0-preview2-25405-01

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
NETStandard.Library.NETFramework 2.0.0-preview2-25405-01

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/dotnet/corefx/blob/master/LICENSE.TXT

Description:
This is the licence on the page which advertises the NuGet: https://www.nuget.org/packages/NETStandard.Library.NETFramework as well as the licence in the LICENCE.txt in the package itself

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [NETStandard.Library.NETFramework 2.0.0-preview2-25405-01](https://clearlydefined.io/definitions/nuget/nuget/-/NETStandard.Library.NETFramework/2.0.0-preview2-25405-01)

### CODE REVIEW

**Comment by capfei** [comment]
This has a PATENTS file. Should this be curated as `MIT AND OTHER`?
https://github.com/dotnet/corefx/blob/v2.0.0-preview2/PATENTS.TXT

**Comment by ariel11** [comment]
> This has a PATENTS file. Should this be curated as `MIT AND OTHER`?
> https://github.com/dotnet/corefx/blob/v2.0.0-preview2/PATENTS.TXT

Yes

**Comment by ariel11** [comment]
@capfei - I don't see the PATENTS file in the NuGet.  However, I do see it sitting in the repo that this package points to, and it does say it applies to .NET Libraries, so it looks like it applies.  Therefore, I agree with MIT AND OTHER.

**Comment by capfei** [comment]
Thanks, @ariel11! I have updated the PR.

**Pull request merged**
