### PR TITLE
Xamarin.TestCloud.Agent 0.20.1

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
Xamarin.TestCloud.Agent 0.20.1

**Details:**
Add EPL-1.0 License

**Resolution:**
License Url: 
https://github.com/calabash/calabash-ios-server/blob/master/LICENSE

Description:
A link to Eclipse Public License is provided by the Xamarin library, see https://www.nuget.org/packages/Xamarin.TestCloud.Agent

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [Xamarin.TestCloud.Agent 0.20.1](https://clearlydefined.io/definitions/nuget/nuget/-/Xamarin.TestCloud.Agent/0.20.1)

### CODE REVIEW

**Comment by capfei** [comment]
It looks like this used to be under a EULA per the license link: https://web.archive.org/web/20160919015018/https://developer.xamarin.com/guides/testcloud/uitest/license/

@AE49 Do you agree with this version being OTHER?

**Comment by AE49** [comment]
@capfei Hi, The NuGet license click takes me here - https://learn.microsoft.com/en-us/appcenter/test-cloud/. How did you find the EULA?

**Comment by capfei** [comment]
@AE49 I used wayback machine to look at the license link for September 2016.
https://web.archive.org/web/20160919015018/https://developer.xamarin.com/guides/testcloud/uitest/license/

**Comment by AE49** [comment]
@capfei I agree with OTHER

**Review by capfei — APPROVED** [review]

**Pull request merged**
