### PR TITLE
Sustainsys.Saml2 2.3.0

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
Sustainsys.Saml2 2.3.0

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/Sustainsys/Saml2/blob/master/LICENSE

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [Sustainsys.Saml2 2.3.0](https://clearlydefined.io/definitions/nuget/nuget/-/Sustainsys.Saml2/2.3.0)

**Automatically added versions:**
- 0.23.0
- 0.24.0
- 1.0.0
- 1.0.1
- 1.0.2
- 2.0.0-preview01
- 2.0.0
- 2.1.0
- 2.2.0
- 2.4.0

Matching metadata: manifest.licenseUrl: 'https://github.com/Sustainsys/Saml2/blob/master/LICENSE'

### CODE REVIEW

**Comment by AE49** [comment]
@capfei We discussed this as a community. Versions 2.0 and above are licensed under MIT, and all earlier versions prior to 2.0 are under LGPL-3.0-or-later. I checked the earlier tagged versions to confirm. I'm making the change the yaml files accordingly.  https://github.com/Sustainsys/Saml2/blob/master/LICENSE

**Review by AE49 — APPROVED** [review]

**Comment by capfei** [comment]
@AE49 Only checked a few but I can't find "or later" being used in the files. Can you point me to one?

**Comment by AE49** [comment]
@capfei It was the result I got when I ran the Diff Tool on the LGPL license file - https://github.com/Sustainsys/Saml2/blob/v0.19.0/LICENSE. What are your thoughts?

**Comment by capfei** [comment]
@AE49 For the GNU licenses, the license text is the same for "only" and "or later". The diff tool will match both.
image

You usually have to look for something that calls out which. From experience, you can usually find it in file headers.

LGPL-2.0-or-later file header example:

> This library is free software; you can redistribute it and/or modify it under the terms of the GNU Library General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

LGPL-2.0-only file header example:

> This library is free software; you can redistribute it and/or modify it under the terms of the GNU Library General Public License as published by the Free Software Foundation; version 2.

I usually assume "only" if they have the license but do not have anything in the file headers, readme, etc.. stating "or (at your option) any later version".

This also applies to MPL-2.0. You need to check the file headers to see if they list Exhibit B or not. If they do, then it is MPL-2.0-no-copyleft-exception.

**Comment by AE49** [comment]
@capfei Ok to Declare "LGPL-3.0-only" for this PR.

**Pull request closed without merging**
