### PR TITLE
webrtc-uwp/AppRTC 74fc5eaf4aaf3911c281a92a09395aee61a9b8bc

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
webrtc-uwp/AppRTC 74fc5eaf4aaf3911c281a92a09395aee61a9b8bc

**Details:**
Add NONE License

**Resolution:**
License Url: 
https://github.com/webrtc-uwp/AppRTC/

Description:
No license in the repository.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [apprtc 74fc5eaf4aaf3911c281a92a09395aee61a9b8bc](https://clearlydefined.io/definitions/git/github/webrtc-uwp/apprtc/74fc5eaf4aaf3911c281a92a09395aee61a9b8bc)

### CODE REVIEW

**Comment by TRQ3** [comment]
1. Package files point to Apache 2.0.
2. Source repo for this specific commit shows Apache 2.0, but also has the same "BSD-style license"
https://github.com/webrtc-uwp/apprtc/blob/74fc5eaf4aaf3911c281a92a09395aee61a9b8bc/appRTC_win_JS.Win10/WinJS/js/en-US/ui.strings.js
https://github.com/webrtc-uwp/AppRTC/blob/master/appRTC_win_JS.Win10/default.html

Leaning toward curating as Apache 2.0. I think that BSD-style language would be discovered. Do you agree, @AE49?

**Comment by AE49** [comment]
@TRQ3 I think the Apache 2.0 and BSD-3-Clause are discovered licenses for sub-components. There's no license in this repo. There's mention in this repo it's a port and the link goes to https://github.com/webrtc/apprtc which does has a BSD-3-Clause license.

@ariel11 Thoughts?

**Comment by ariel11** [comment]
@AE49 and @TRQ3 - It does appear the bulk of the main project files say the below.  However, I do not see a LICENSE file anywhere in this repo (for any commit/branch).  For the curation, "NONE" probably makes the most sense given there's not an actual LICENSE file or SPDX identifier indicating what exactly the license text is.

/*
 *  Copyright (c) 2014 The WebRTC project authors. All Rights Reserved.
 *
 *  Use of this source code is governed by a BSD-style license
 *  that can be found in the LICENSE file in the root of the source
 *  tree.
 */

**Comment by ariel11** [comment]
@TRQ3 - I looked again and do not see any license info for this repo.  It says it is a port of https://github.com/webrtc/apprtc, and that repo has a LICENSE file, so I think all the files that have that header saying look at the LICENSE file come from that repo.  However, I dont see anything regarding how the port is licensed.  I would suggest "NONE," but curious what @capfei thinks.

**Review by TRQ3 — APPROVED** [review]

**Pull request merged**
