### PR TITLE
Missing declared license

### PR DESCRIPTION
**Pull request by capfei**
**Type:** Missing

**Summary:**
Missing declared license

**Details:**
Missing license

**Resolution:**
MIT: https://bitbucket.org/cffi/cffi/src/v1.13.0/LICENSE

**Affected definitions**:
- [cffi 1.13.0](https://clearlydefined.io/definitions/pypi/pypi/-/cffi/1.13.0/1.13.0)

### CODE REVIEW

**Comment by AE49** [comment]
@geneh Can you resolve this conflict? Thanks

**Comment by AE49** [comment]
@geneh Can you resolve this conflict? Thanks

**Comment by geneh** [comment]
Done!

**Comment by AE49** [comment]
@geneh This one is still under conflict.

**Pull request merged**
