### PR TITLE
TravisEz13_181205_203732.886

### PR DESCRIPTION
**Pull request by TravisEz13**
**Type:** Missing

**Summary:**
Add license types for a few nuget packages

**Details:**
Add license types for packages based on the license link on the nuget.org page for the package

**Resolution:**
Add license types for packages based on the license link on the nuget.org page for the package

**Affected definitions**:
- System.ServiceModel.Primitives 4.5.3,- System.ServiceModel.Security 4.5.3,- System.ServiceModel.Syndication 4.5.0,- System.ServiceProcess.ServiceController 4.5.0,- System.Threading.AccessControl 4.5.0

### CODE REVIEW

**Comment by TravisEz13** [comment]
Hmmm... The UI shows that these don't have license types defined but this PR shows no changes when I submit it.  I'll close this if it goes away on it's own

**Comment by fossygirl** [comment]
@dabutvin Is this another curation sync issue?

**Comment by TravisEz13** [comment]
For example, https://clearlydefined.io/definitions/nuget/nuget/-/System.ServiceModel.Primitives/4.5.3 shows no license, but it is in the curation data.

**Comment by dabutvin** [comment]
I just kicked it and it's there now, not sure what happened in this case. I'll look into it.

something to do with the combination of these PRs

https://github.com/clearlydefined/curated-data/pull/847
https://github.com/clearlydefined/curated-data/pull/848/files#diff-edc6f036a944374ee23cb2b132e809eb

**Comment by TravisEz13** [comment]
@dabutvin 	that fixed one issue but I still have issues with these packages:
image

**Comment by TravisEz13** [comment]
@dabutvin 	Can you tell me when these should be ready?

**Comment by dabutvin** [comment]
Ready!

- https://clearlydefined.io/definitions/nuget/nuget/-/System.ServiceModel.Security/4.5.3
- https://clearlydefined.io/definitions/nuget/nuget/-/System.ServiceModel.Syndication/4.5.0
- https://clearlydefined.io/definitions/nuget/nuget/-/System.ServiceProcess.ServiceController/4.5.0
- https://clearlydefined.io/definitions/nuget/nuget/-/System.Threading.AccessControl/4.5.0

**Comment by TravisEz13** [comment]
Thanks, it is working now

**Comment by dabutvin** [comment]
sure 👍

**Pull request closed without merging**
