### PR TITLE
Adding license to couple of missing components

### PR DESCRIPTION
**Pull request by anpaz-msft**
**Type:** Missing

**Summary:**
Adding license to couple of missing components

**Details:**
Missing packages used by Q#

**Resolution:**
Checked and both uses MIT.

**Affected definitions**:
- [CommandLineParser 2.5.0](https://clearlydefined.io/definitions/nuget/nuget/-/CommandLineParser/2.5.0),- [YamlDotNet 6.0.0](https://clearlydefined.io/definitions/nuget/nuget/-/YamlDotNet/6.0.0)

### CODE REVIEW

**Comment by joseharriaga** [comment]
I also have a PR open for CommandLineParser 2.5.0: https://github.com/clearlydefined/curated-data/pull/2107. One thing to note is that the file for CommandLineParser is currently corrupted, which is why it's failing the automatic check here. My PR fixes that corruption on top of adding the license for version 2.5.0. I recommend undoing the changes in CommandLineParser, keeping the changes in YamlDotNet, and merging my PR.

**Comment by AE49** [comment]
@geneh or @fossygirl  can you help with why I'm not able to merge this PR? The license details curated are correct.

**Comment by geneh** [comment]
The problem was related to https://github.com/clearlydefined/service/issues/564. There was also a merging conflict I had to resolve.

**Comment by AE49** [comment]
@geneh Thanks.

**Pull request merged**
