### PR TITLE
webrtc-uwp/cryptopp b8f35b6ab15911654835a287c7e6fce86ad45fc7

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
webrtc-uwp/cryptopp b8f35b6ab15911654835a287c7e6fce86ad45fc7

**Details:**
Add BSL-1.0 License

**Resolution:**
License Url: 
https://raw.githubusercontent.com/webrtc-uwp/cryptopp/master-ortclib/License.txt

Description:

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [cryptopp b8f35b6ab15911654835a287c7e6fce86ad45fc7](https://clearlydefined.io/definitions/git/github/webrtc-uwp/cryptopp/b8f35b6ab15911654835a287c7e6fce86ad45fc7)

### CODE REVIEW

**Comment by mihouc** [comment]
License link on Clearly Defined indicates license is NONE
License file at source listed on Clearly Defined also indicates license is NONE

License for package should be curated as NONE

**Comment by AE49** [comment]
@mihouc I agree with the Data Contributor on BSL-1.0 - https://github.com/webrtc-uwp/cryptopp/blob/b8f35b6ab15911654835a287c7e6fce86ad45fc7/License.txt

**Comment by mihouc** [comment]
@AE49 I misread the license. I agree with BSL-1.0

**Review by mihouc — APPROVED** [review]

**Comment by AE49** [comment]
@mihouc You can approve and merge

**Pull request merged**
