### PR TITLE
nuget/nuget/-/Blazorise.Icons.FontAwesome/0.9.3.4

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Auto

**Summary:**
nuget/nuget/-/Blazorise.Icons.FontAwesome/0.9.3.4

**Details:**
Add MIT license

**Resolution:**
Automatically added versions based on https://github.com/clearlydefined/curated-data/pull/10666
 - 0.9.3.5

Matching license file(s): LICENSE.md

**Affected definitions**:
- [Blazorise.Icons.FontAwesome 0.9.3.5](https://clearlydefined.io/definitions/nuget/nuget/-/Blazorise.Icons.FontAwesome/0.9.3.5)

### CODE REVIEW

**Comment by capfei** [comment]
Closing; already declared as MIT.

**Comment by MichaelTsengLZ** [comment]
@capfei  I saw 0.9.3.5 has not been declared as MIT yet? 

> Closing; already declared as MIT.

**Comment by capfei** [comment]
@MichaelTsengLZ It is already declared correctly on the ClearlyDefined site. If they are correctly declared, then we don't need PRs for these versions. 
https://clearlydefined.io/definitions/nuget/nuget/-/Blazorise.Icons.FontAwesome/0.9.3.5

**Comment by MichaelTsengLZ** [comment]
@capfei  Hmm, looks like this logic is missing in the code. I will create a work item for it. Thanks for your feedback.

**Pull request closed without merging**
