### PR TITLE
ariel11_181026_194736.657

### PR DESCRIPTION
**Pull request by ariel11**
**Type:** Missing

**Summary:**
Missing License

**Details:**
https://www.nuget.org/packages/Microsoft.PowerBI.Api/3.0.0 has no “License” or “Project” and is unlisted. 

**Resolution:**
The closest version is “MIT” - https://www.nuget.org/packages/Microsoft.PowerBI.Api/2.0.14. Declaring "MIT" but maybe we should leave blank?

**Affected definitions**:
- Microsoft.PowerBI.Api 3.0.0

### CODE REVIEW

**Comment by fossygirl** [comment]
@capfei @ariel11 Do we need to talk about this further? Looks like it might be out of the bounds of our guidelines so I'd like to update them if possible. Let me know what we should do to resolve.

**Comment by capfei** [comment]
I'm not sure with this one. The guidelines say to go with the nearest version, however, my holdup is that this version is unlisted.

**Comment by fossygirl** [comment]
@jeffmcaffer Thoughts on what a good guideline in this case would be?

**Comment by jeffmcaffer** [comment]
The reference version is listed and has a version so seems reasonable to use. Note that we can also look at the source code if it can be identified.

**Comment by ariel11** [comment]
@jeffmcaffer - The version we are declaring the license for is "unlisted" - https://www.nuget.org/packages/Microsoft.PowerBI.Api/3.0.0.  Should we do anything special or different for "unlisted" packages?  There is no project link on the page to look at source code.

**Comment by jeffmcaffer** [comment]
don't see any reason to treat unlisted packages differently. As long as the package can be accessed and used by teams then we have to deal with the licensing etc.

**Comment by ariel11** [comment]
@capfei - I think Jeff answered the open question, above, yes?  Sounds like OK to check in MIT.  Let me know if I have any further action item here.  Thanks!

**Pull request merged**
