### PR TITLE
Added npm/npmjs/@kudoai/chatgpt.js.yaml

### PR DESCRIPTION
**Pull request by adamlui**

### CODE REVIEW

**Comment by capfei** [comment]
When reviewing these versions, I noticed that they had not been harvested yet. Ran them through the harvester and the declared license came back as MIT for all versions. Closing PR since it is no longer needed.
https://clearlydefined.io/definitions/npm/npmjs/@kudoai/chatgpt.js/2.6.3
https://clearlydefined.io/definitions/npm/npmjs/@kudoai/chatgpt.js/2.6.4
https://clearlydefined.io/definitions/npm/npmjs/@kudoai/chatgpt.js/2.6.5
https://clearlydefined.io/definitions/npm/npmjs/@kudoai/chatgpt.js/2.6.6
https://clearlydefined.io/definitions/npm/npmjs/@kudoai/chatgpt.js/2.6.7
https://clearlydefined.io/definitions/npm/npmjs/@kudoai/chatgpt.js/2.6.8

**Comment by adamlui** [comment]
hey @capfei so curations is only for if a pkg wasn't harvested? if so, how do I check first?

**Comment by capfei** [comment]
@adamlui Curations are for correcting or providing missing information after it has been harvested like incorrect declared license information, incorrect copyright info, missing source locations, etc.. You can try finding the component and version on https://clearlydefined.io.

If it hasn't been harvested, the badge will state it. Example of a new version that hasn't been harvested: https://clearlydefined.io/definitions/nuget/nuget/-/Soenneker.Tests.FixturedUnit/2.1.696
image

Looking at version 2.6.3 of @kudoai/chatgpt.js, it now shows "Partially Harvested" and lists the declared as MIT.
https://clearlydefined.io/definitions/npm/npmjs/@kudoai/chatgpt.js/2.6.3
image
image

If you want to harvest a component, you can do that at https://clearlydefined.io/harvest or https://api.clearlydefined.io/api-docs/#/harvest. You should be able to find most components at https://clearlydefined.io/harvest. If you can't find it, then https://api.clearlydefined.io/api-docs/#/harvest will let you provide the coordinates manually.

Does that help? Let me know if you have any other questions about the curation process!

**Comment by adamlui** [comment]
Yes @capfei that was indeed helpful! If I use the webapp to curate, will it create a PR in my GitHub name?

**Comment by capfei** [comment]
@adamlui I ***believe*** if you provide a token, it should show as you or whatever account associated to the token as the submitter. I do know PRs submitted without authentication show up with clearlydefinedbot as the submitter. Feel free to submit test PRs to https://github.com/clearlydefined/curated-data-dev.

**Comment by adamlui** [comment]
@capfei I'm tried harvesting https://github.com/adamlui/autoclear-chatgpt-history now:

image

clearlydefined.io homepage search result still doesn't show it after ~10 min now:

image

Is it because I didn't enter a hash? Because the Harvest button being on the same row as platform > user > component selector made it seem like that was all was required. Also, should I just enter the latest commit hash even if there weren't any changes in it?

**Comment by capfei** [comment]
@adamlui I haven't tried harvesting without providing that info. Not sure if it will work or will just pull the latest. 🤔

Yes, using the latest commit will definitely work since it is not about if there are changes but what is contained in the component at the point.

Sadly, harvesting can take a while depending upon how much is queued, how big the component is. It can take an hour or so but can go a couple of days on the worst end. Rarely have I had component go longer than a week.

**Comment by adamlui** [comment]
But when I enter hash it doesn't seem like anything is happening, like nothing in the screen changes after pasting, so it's unclear if clicking Harvest is relying on this new input


https://github.com/clearlydefined/curated-data/assets/10906554/c5b0298d-0004-4152-a0f8-13c89aa99e28

Is this how you harvest using commit hash? Do you usually see something happen when you type it in?

**Comment by capfei** [comment]
@adamlui For GitHub repos, if the commit is associated to a tag, it should show up in a list to select. Otherwise, you would have to provide the commit. Packages should generate a list to select the version.

I'm sorry harvesting is not a good experience. The lack of helpful information on the harvest page has been an issue for a long time. It is not a great experience since the only confirmation is "Harvest started" ....and that's it. I have made the lack of info here known and requested features like estimated harvest times or seeing the queue be added but we have had limited dev support for the last couple of years.

We do have help now but they have been focused on the fixing the bigger service issues, updating processes, adding new supported components.

I will check on https://clearlydefined.io/definitions/git/github/adamlui/autoclear-chatgpt-history/30f90e0358d1e2d40519872175dfda226b75b9fc tomorrow to see if it completed harvesting.

**Pull request closed without merging**
