### PR TITLE
SpecRun.Runner 3.5.22

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
SpecRun.Runner 3.5.22

**Details:**
Add BSD-3-Clause License

**Resolution:**
License Url: 
https://github.com/SpecFlowOSS/SpecFlow/blob/master/LICENSE.txt

Description:
company provided EULA: https://specflow.org/plus/eula/ and the referenced license on their OSS repo aligns with New BSD License.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [SpecRun.Runner 3.5.22](https://clearlydefined.io/definitions/nuget/nuget/-/SpecRun.Runner/3.5.22)

**Automatically added versions:**
- 3.1.44
- 3.1.48
- 3.1.53
- 3.2.7-beta
- 3.2.13
- 3.2.15
- 3.2.22
- 3.2.31
- 3.3.17
- 3.3.41
- 3.4.12
- 3.4.51
- 3.6.2

Matching license file(s): LICENSE
Matching metadata: manifest.licenseUrl: 'https://aka.ms/deprecateLicenseUrl'

### CODE REVIEW

**Comment by capfei** [comment]
This should be curated as OTHER since the NuGet license link points to https://specflow.org/plus/eula, which is a EULA.

**Comment by scottgorlick** [comment]
This is used by SpecFlow+, but is a library you must have included (or it's really a secondary dependency of the OSS parts of SpecFlow) to use SpecFlow even without SpecFlow+ - this library enables use of SpecFlow+

**Comment by capfei** [comment]
@AE49 What do you think? Should this be OTHER?

**Comment by capfei** [comment]
Updating to OTHER based on https://github.com/clearlydefined/curated-data/pull/11145

**Comment by scottgorlick** [comment]
Thank you very much for handling this issue, I appreciate your help.

**Pull request merged**
