### PR TITLE
Telesign 2.2.5

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Missing

**Summary:**
Telesign 2.2.5

**Details:**
Add MIT License

**Resolution:**
License Url:
https://github.com/TeleSign/csharp_telesign/blob/master/LICENSE.txt

Description:
This is a license file taken from the official repository of the library https://www.nuget.org/packages/Telesign

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [Telesign 2.2.5](https://clearlydefined.io/definitions/nuget/nuget/-/Telesign/2.2.5)

### CODE REVIEW

**Review by obohaciak — APPROVED** [review]
Looks good, verified on project page

**Comment by obohaciak** [comment]
@capfei Might I ask for your review?

**Comment by obohaciak** [comment]
Me and my coworkers use clearlydefinedbot to open curations. Would it be possible for one of us to train to become an official curator that could approve changes?

**Review by capfei — APPROVED** [review]

**Comment by capfei** [comment]
@obohaciak Thank you for your interest in ClearlyDefined and wanting to help curate. A place to start is the curation guidelines to get familiar with what is considered a declared license vs discovered, valid license locations, source locations, getting familiar with looking through commit history (since we need info from the time a version or commit was published and not what is listed in a master/main branch), reviewing the different package types, etc.. 
https://docs.clearlydefined.io/docs/curation/curation-guidelines

**Comment by obohaciak** [comment]
Thank you @capfei for your kind help and for getting me started on the curation path!

**Pull request merged**
